### ISSUE TITLE
Insufficient Permissions error!

### ISSUE THREAD

**Issue by YoungNFoolish** [Swati4star/Images-to-PDF#1]
Hi swati,
I got a Huawei Honor 4c running Android 6 and installed the app from f-droid and gave it the permissions at the first run. Then i selected some images and once i tapped "Create PDF", it shows me a toast saying "insufficient permissions".
What's the matter?

sorry for my bad english :sweat_smile:

**Comment by Swati4star** [comment]
Thank you for pointing it out.
There was some problem in code with runtime permissions stuff.
Fixed by https://github.com/Swati4star/Images-to-PDF/commit/773eb6fd416c4a00dd4f11a4bcf3927165ee224b

**Comment by poppypundit** [comment]
I'm still getting this error...all the time.

**Comment by Swati4star** [comment]
You must be downloading the app from fossdroid.
I need to update the app on fossdroid.

If you download the app by building it from latest code, or from this [link](https://dl.dropboxusercontent.com/s/ugpju98f0y2t947/app-debug.apk), you won't get this error.

**Comment by poppypundit** [comment]
Thank you. Yes, I did download from fossdroid. By no means a builder... Cheers
