### ISSUE TITLE
Rotated pdf photos on Samsung Galaxy S5 

### ISSUE THREAD

**Issue by mihudevcom** [Swati4star/Images-to-PDF#10]
Loading a simple image does create a regular pdf file. But loading a picture taken with Samsung Galaxy S5(and I have a feeling that with most samsung devices) the end result is rotated.

It's probably a camera issue since I've seen it before on other apps. Should I take care of it?

Here is an example.
![20170407_130122](https://cloud.githubusercontent.com/assets/7577378/24957003/df8e390e-1f92-11e7-901a-f00a36eae629.jpg)
[beer_upside_down[1].pdf](https://github.com/Swati4star/Images-to-PDF/files/916425/beer_upside_down.1.pdf)

**Comment by mihudevcom** [comment]
UPDATE
Pictures take from the app are not rotated. Just the ones taken with the device camera.

**Comment by iMouath** [comment]
Maybe this was caused because of com.gun0912.tedpicker.ImagePickerActivity library

**Comment by Swati4star** [comment]
So, the images you take from the app are good?

**Comment by mihudevcom** [comment]
@Swati4star No, what I meant was that pictures, normal pictures, not photos, work okay. Just photos taken with my device seem to get rotated.

**Comment by mihudevcom** [comment]
@iMouath It might be. I'll investigate and let you know.

**Comment by mihudevcom** [comment]
@iMouath Yep, the issue is with the image picking library.
@Swati4star How should we proceed with this?

**Comment by iMouath** [comment]
@mihudevcom why not use the native camera and gallery API? I tried to implement the camera but facing issues cause my programming skills are limited, got the picture taken but couldn't process it.

**Comment by Swati4star** [comment]
@mihudevcom @iMouath Should we use native camera and gallery API? OR should we wait for updates in TedPicker.

**Comment by mihudevcom** [comment]
@Swati4star I'll report it on the tedpicker library and after they will fix it we should update the library version and it should be fixed here as well.

**Comment by mihudevcom** [comment]
The TedPicker is using a deprecated library : 

> This library suffers from some fundamental problems. New projects should look elsewhere, and existing projects should plan on migrating to something else. This library is discontinued and deprecated.

We should probably implement something else. What do you think @Swati4star ?

**Comment by Swati4star** [comment]
@mihudevcom Do you have any other library in mind, or should we create something on our own from scratch?

**Comment by mihudevcom** [comment]
@Swati4star There must be some library that can do this. If not, I believe we should do it. It's not that complicated to do. I'll check back in a few days with what I believe would be the easiest way to do it.

**Comment by Swati4star** [comment]
Sure. I will also look into it by the time.

**Comment by Swati4star** [comment]
We now have an 'Image Enhancement option' which allows us to crop & rotate images. The user can confirm the images from there. I think this should not be a problem now.
