### ISSUE TITLE
Update app on fdroid

### ISSUE THREAD

**Issue by cewbdex** [Swati4star/Images-to-PDF#1000]
The last app release was more than two years ago, at least on F-Droid, maybe make a new release? About 50 commits have been made since.

**Comment by Swati4star** [comment]
There was some issue with one of the libraries previously. I'll check again and try if it is possible to update on Fdroid. This may take some time. thanks!

**Comment by TPS** [comment]
v8.8.1 is released on F-droid 6-17-21!  Close FTW?

**Comment by ShashaankHari** [comment]
Does the play Store and fdroid ones have the same features?
Since on fdroid is 8.8.1 and on play Store it's 8.84
