### ISSUE TITLE
Highlight bug

### ISSUE THREAD

**Issue by Kolwyntjie581** [Swati4star/Images-to-PDF#1001]
The extra options in the menu such as "Settings" are not highlighted.

### Steps to reproduce
1. download app
2. open menu
3. click on any non-extras options (the option will be highlighted)
4. open menu
5. click on extras options "Settings"
6. "Settings" are not highlighted

I have attached the gif in https://media.giphy.com/media/1WD62sZNAGmjOSjOs8/giphy.gif

### Expected behaviour
"Settings" are highlighted

### Actual behaviour
"Settings" are not highlighted, instead it highlights the previous option.

**Comment by codegsaini** [comment]
@Kolwyntjie581 Sir, it looks like you're working on old version of repository. **You should fetch latest version**, then try to produce this bug.
Thanks
