### ISSUE TITLE
Synchronous scrolling error

### ISSUE THREAD

**Issue by Kolwyntjie581** [Swati4star/Images-to-PDF#1002]
When I scroll down/up the menu, the back content is also scrolling.

### Steps to reproduce
1. open menu
2. scrolling down

I have attached the gif in https://media.giphy.com/media/1jUQwe5tNahZahScXZ/giphy.gif

### Expected behaviour
The back content should be still when scrolling menu.

### Actual behaviour
The back content is scrolling synchronously.

**Comment by codegsaini** [comment]
Looks like you are working on a old version of code, **Please fetch latest!**
