### ISSUE TITLE
Store access issue

### ISSUE THREAD

**Issue by vikassaini** [Swati4star/Images-to-PDF#1009]
Describe your issue here.

when app newly installed on device it after permission granted and try to convert any pdf file it show error in document directory create

i am facing this issue in android 10, 6 & 9

when i created Documents directory in internal storage. app working fine.

**Comment by saigoud25** [comment]
Can I work on this issue?

**Comment by Swati4star** [comment]
Sure @saigoud25

**Comment by saigoud25** [comment]
Ma'am I am getting some build issues while try to run the App. Where can I get help Ma'am

**Comment by atinagrawal** [comment]
I am also facing this issue, but it works perfectly on Android 11.
Any solution?

**Comment by codegsaini** [comment]
@vikassaini If you are working with latest changes in the project? As the app available at play store is outdated and some issue may already be resolved in the latest version of this repo.
