### ISSUE TITLE
Add "Hindi" and "Marathi" translation for App strings

### ISSUE THREAD

**Issue by MSid01** [Swati4star/Images-to-PDF#1014]
I have seen many people like to set their **native language** in device's setting.
I have good command over Hindi and Marathi.

**Comment by MSid01** [comment]
I would be happy if you assign this issue to me..
I am just starting out with open source contribution.

**Comment by Swati4star** [comment]
Sure, you can send out a pull request with these translations

**Comment by niranjangirhe** [comment]
I have added the support for Hindi, Please check my pull request #1015.

Thank you.

**Comment by aishwaryasonavane79** [comment]
Hello, I've added support for Marathi. I have good command over Marathi. Please check my PR #1096 . 

Thank you.
