### ISSUE TITLE
When applying the theme, I can't see the text in Help.

### ISSUE THREAD

**Issue by baekyumi** [Swati4star/Images-to-PDF#1034]
When applying the theme(Dark or Black), I can't see the text in Help.
Can I work on this issue?
![image](https://user-images.githubusercontent.com/67865411/140046391-f13db885-735d-4864-b937-95aa690285db.png)
![Help](https://user-images.githubusercontent.com/67865411/140046604-f1029449-be7a-47f4-ad2e-bff4e6b60c8e.JPG)

**Comment by baekyumi** [comment]
@Swati4star @codegsaini 
Can I work on this issue?

**Comment by codegsaini** [comment]
@baekyumi Yes, you can work on it. but I think these fragment should be removed and these slides should be shown in single activity. (May be horizontal recyclerview or changing src of imageview and changing text of textView with slide gesture or something like that). You can try that. And of course, you can work on the issue of white text color in white background [this issue].
