### ISSUE TITLE
Add option to Password Protect PDF after its creation

### ISSUE THREAD

**Issue by tanvidadu** [Swati4star/Images-to-PDF#106]
I think it would be useful if provide users to add passwords to their files even after they have been created. 
Option for this can be in the dialog box itself.
<img src="https://user-images.githubusercontent.com/29161745/41677857-2ba3806a-74e7-11e8-8fa1-e738ecb01466.png" width = "50%" height="50%" />

**Comment by sholkay** [comment]
I guess we can use `passwordProtectPDF` method here that @anandkumarkparmar created after making certain changes to it.

**Comment by shiv07tiwari** [comment]
Can I work on this issue ?

**Comment by Swati4star** [comment]
Sure @shiv07tiwari 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/134 👍
