### ISSUE TITLE
Add a basic tutorial to explain user the functioning of app

### ISSUE THREAD

**Issue by tanvidadu** [Swati4star/Images-to-PDF#108]
Add a basic tutorial explaining user the functionality of app using material showcase.

**Comment by Swati4star** [comment]
Great idea.
Here are some other libraries for this: 
https://github.com/wooplr/Spotlight
https://github.com/iammert/MaterialIntroView

This tutorial library also looks good: 
https://github.com/msayan/tutorial-view
( we can implement something similar on our own, we don't want to be dependent on more libraries)

**Comment by uemarica** [comment]
Hey, i would like to work on it.

**Comment by Swati4star** [comment]
Sure. You can start on it.

**Comment by Swati4star** [comment]
@uemarica Any updates?

**Comment by uemarica** [comment]
Yeah, working on it
Used various libraries but nothing seem to be that impressive so finally will be using fragments like "ola" does

**Comment by Swati4star** [comment]
It's been a week. If you face any problem, comment here only.

**Comment by Swati4star** [comment]
This library looks good, if anyone want to use for this issue: https://github.com/apl-devs/AppIntro

**Comment by mursyidah** [comment]
May i try for this issue?

**Comment by Swati4star** [comment]
Sure @mursyidah  👍
