### ISSUE TITLE
Potentially vulnerable PDF library used

### ISSUE THREAD

**Issue by SkewedZeppelin** [Swati4star/Images-to-PDF#1083]
I am going though apps that use old native libraries on F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11496/

Your app uses `com.itextpdf:itextg:5.5.10` from 2016-10-07, which seems to have ~5 known security issues.
https://github.com/Swati4star/Images-to-PDF/blob/8.8.1/app/build.gradle#L98

Newer versions are available: https://github.com/itext/itextpdf/releases

**Comment by Tiklyt** [comment]
Hello, I fixed this issues with the #1097 PR, can you check it ? :)

**Comment by SkewedZeppelin** [comment]
@Tiklyt 
that gets it done!

**Comment by jondo** [comment]
I guess this issue is the reason why F-Droid marks version 8.8.1 from 2021 as "undesirable".
Please create a new release.

**Comment by Moostek** [comment]
Hello, F-Droid still reporting that the app is "vulnerable". How about this issue, please? Is there anybody to fix it, please?

**Comment by Swati4star** [comment]
Fixed with #1097
