### ISSUE TITLE
Marked 'Has Security vulnerabilities' in foxydroid (F-droid repo)

### ISSUE THREAD

**Issue by Ranger-NF** [Swati4star/Images-to-PDF#1125]
![f-droid anti-feature.png](https://github.com/Swati4star/Images-to-PDF/assets/78952725/8dd2a8f4-b3d3-45b4-b231-1165033d8ff7)

Why is it showing like that? Were you aware of it earlier?

**Comment by Swati4star** [comment]
Previously, the issue was due to itext library which was fixed by https://github.com/Swati4star/Images-to-PDF/pull/1097

Need to see why is this coming up in new version

**Comment by Ranger-NF** [comment]
I might as well keep this issue opened untill its fixed

**Comment by Swati4star** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/3002

**Comment by Ranger-NF** [comment]
The issue seems to have been fixed in F-Droid. Closing the issue 👍🏻
