### ISSUE TITLE
Files with the same name

### ISSUE THREAD

**Issue by sholkay** [Swati4star/Images-to-PDF#114]
Whenever we create a file with the same name as an existing file, the content of the previous files gets overwritten.

**Comment by Swati4star** [comment]
Good finding!

When user fills the filename, show a dialog (an alert informing the user that this filename already exists? and if he wishes to overwrite that one).

**Comment by sholkay** [comment]
I am working on it.

**Comment by Swati4star** [comment]
Great! 👍

**Comment by sholkay** [comment]
I have a doubt.

- If  the file exists then we will display a new dialog which will warn the user and say that file already exists do you want to overwrite. If he clicks yes, it will overwrite the file and what to do when he clicks no?

**Comment by Swati4star** [comment]
What you are doing right now is good. Show the dialog to rename the file.

**Comment by vyankatesh24** [comment]
I would like to work on it.

**Comment by Swati4star** [comment]
Sure @vyankatesh24

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/193
