### ISSUE TITLE
Change the word "Choice Image" on the screen when clicking an image.

### ISSUE THREAD

**Issue by raghavpuri31** [Swati4star/Images-to-PDF#115]
When you go in "Select Images" option, you can see the word "Choice Image" below notification bar. Correct this word.

![imgpdf](https://user-images.githubusercontent.com/15330327/41812334-b2ca3968-773e-11e8-98f4-02436824c57d.jpeg)

**Comment by sholkay** [comment]
Should I change the text to "Select Image"?

**Comment by Swati4star** [comment]
`Select Images`

**Comment by syedjahangirpeeran** [comment]
I would like to work on this!

**Comment by raghavpuri31** [comment]
@syedjahangirpeeran, Maybe @sholkay is already working on it. You can work on another issue.

**Comment by syedjahangirpeeran** [comment]
i guess he is already working on #114  currently.

**Comment by raghavpuri31** [comment]
@syedjahangirpeeran Go ahead then!

**Comment by sholkay** [comment]
@syedjahangirpeeran Sorry, but I already fixed this bug and also created a pull request for it.

**Comment by Kirti0808** [comment]
I would like to work on this issue if noone is working on it

**Comment by raghavpuri31** [comment]
@Kirti0808 Sorry it's been fixed, but you can go ahead and check other issues..

**Comment by Swati4star** [comment]
No @raghavpuri31, the issue has not been fixed (otherwise it would have been closed)

@Kirti0808 you can start with this issue. (You can take help from #122 )

**Comment by Kirti0808** [comment]
Yes sure...i will be working on it then.
Thank you.

**Comment by Kirti0808** [comment]
Should I update the image in Step 2 of README.md ([https://github.com/Swati4star/Images-to-PDF/blob/master/README.md](url))
