### ISSUE TITLE
Hide the Password while setting it for protection.

### ISSUE THREAD

**Issue by raghavpuri31** [Swati4star/Images-to-PDF#117]
When Password Protecting your PDF file, the password is visible. Change that text field into password field.
You can make UI for it like this:

![paschan](https://user-images.githubusercontent.com/15330327/41812638-6358d2ee-7744-11e8-85e9-156c824a11cf.jpeg)

<img width="190" alt="121" src="https://user-images.githubusercontent.com/15330327/41812630-4653dafe-7744-11e8-8d00-94baa13dca2b.png">

**Comment by Swati4star** [comment]
`The user can click on the eye icon to hide or show the password.

**Comment by shiv07tiwari** [comment]
I would really love to start working on this issue under GSSoC !

**Comment by Swati4star** [comment]
Sure. You can 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/126
