### ISSUE TITLE
Add information to the pdf list 

### ISSUE THREAD

**Issue by tanvidadu** [Swati4star/Images-to-PDF#119]
Add information like date of creation  and size of file in the list view

**Comment by shiv07tiwari** [comment]
Can I start working on this issue ?

**Comment by Swati4star** [comment]
Sure. You can. 👍

**Comment by shiv07tiwari** [comment]
@Swati4star  In the date last modified, should I display only the date or time as well ?

**Comment by Swati4star** [comment]
@shiv07tiwari Can you post a screenshot of how it is looking right now?

**Comment by shiv07tiwari** [comment]
![img_20180628_120333](https://user-images.githubusercontent.com/38163725/42017003-321568ac-7acb-11e8-8963-7796cd79657d.JPG)

**Comment by Swati4star** [comment]
add comma(,) after `thu`
and write time as well (would love to see the screenshot first; hope it doesn't look messy)

**Comment by shiv07tiwari** [comment]
Okay, what should be the format for time
![img_20180628_122051](https://user-images.githubusercontent.com/38163725/42017620-5f9e9292-7acd-11e8-8d55-d955089ddd43.JPG)

@Swati4star  Added time

**Comment by Swati4star** [comment]
Is the time in 24 hr format?

**Comment by shiv07tiwari** [comment]
@Swati4star  Yes.

**Comment by Swati4star** [comment]
There is a space between Thu & ,
Remove that.
Other than that, it looks good

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/128
