### ISSUE TITLE
Task Done Appearance

### ISSUE THREAD

**Issue by ishaandhamija** [Swati4star/Images-to-PDF#12]
After the PDF is created, Done appears as a simple text on the white area of the activity. It will be better if it will appear as a Toast or in a snackbar !

**Comment by Swati4star** [comment]
Sure! If you want, you can work on this issue.

**Comment by ishaandhamija** [comment]
Ok,  great :)

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/16
