### ISSUE TITLE
Add option to search PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#129]
- In `View files`, add a search bar on the action bar
- Add option to search PDF

**Comment by ac491** [comment]
I would like to try to solve this issue

**Comment by ac491** [comment]
I have added the search icon which when clicked opens edit text.
![screenshot_2018-06-30-00-27-20-696_swati4star createpdf](https://user-images.githubusercontent.com/31413484/42109951-13cd3c84-7bfd-11e8-8c9f-c9e1d3ac6d5f.png)

As the user types the search query, the listView is dynamically updated

![screenshot_2018-06-30-00-26-38-442_swati4star createpdf](https://user-images.githubusercontent.com/31413484/42109970-237650e4-7bfd-11e8-9d84-282a12963e1b.png)

![screenshot_2018-06-30-00-26-45-240_swati4star createpdf](https://user-images.githubusercontent.com/31413484/42109900-e9ce2d76-7bfc-11e8-8975-073b0417092f.png)

when the cross is clicked, the complete list is loaded again

**Comment by Swati4star** [comment]
@ac491 This looks amazing!
Just one thing, when user has clicked on the search bar, shouldn't we hide the `delete` and `sort` icon. There appears to be so many icons on the action bar at that time.

**Comment by ac491** [comment]
It's a submit button

**Comment by Swati4star** [comment]
Okay :+1:

**Comment by ac491** [comment]
I tried to implement onClick listener with searchView to remove the other icons when the search icon is pressed but it doesn't seem to work with searchView. Do you have some suggestions on how should I implement it

**Comment by Swati4star** [comment]
Move search icon to leftmost. Don't hide sort or delete for now. We'll move them to extra settings options ( 3 dots on the right)

**Comment by ac491** [comment]
![screenshot_2018-06-30-16-24-58-022_swati4star createpdf 1](https://user-images.githubusercontent.com/31413484/42124578-c02da592-7c82-11e8-9785-84901ab04796.png)

![screenshot_2018-06-30-16-25-03-798_swati4star createpdf 1](https://user-images.githubusercontent.com/31413484/42124566-9c13eb58-7c82-11e8-90e0-638363b96e22.png)

**Comment by Swati4star** [comment]
Awesome! @ac491 You can create a PR for this 👍

**Comment by ac491** [comment]
Where should I display a message when no PDF matches the search query?

**Comment by Swati4star** [comment]
A toast or snackbar would be enough.
