### ISSUE TITLE
Include Android unit testing for FileUtils class

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#132]
- Add unit tests for all the functions in the `FileUtils` class
- Include `./gradlew test` in .travis.yml

**Comment by jwojciec** [comment]
PR opened: https://github.com/Swati4star/Images-to-PDF/pull/464

**Comment by jddeep** [comment]
@Swati4star I would like to work on this before #164 . Can I proceed?

**Comment by Swati4star** [comment]
sure @jddeep

**Comment by Swati4star** [comment]
Are you working on this @jddeep

**Comment by jddeep** [comment]
Nope. This needs refactoring work in the FileUtils class.

**Comment by jddeep** [comment]
Before it can be tested.

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/464
