### ISSUE TITLE
Create directory type structure in view files

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#136]
Following should be implemented in this feature:
- The `View Files` should have an option to create a directory
- The user should be able to move PDFs inside that directory or from that directory to home directory
- Removing the directory option should also be there
- By default, new PDF should be created where it is getting created right now

**Comment by ac491** [comment]
I would like to try to solve this issue.

**Comment by Swati4star** [comment]
Sure :D

**Comment by ac491** [comment]
Can I use sharedPreference to store the different directory names locally so that I can retrieve the files from these directories in populateListView() method?

**Comment by Swati4star** [comment]
Go ahead with this implementation.
 Just remember, even if the user clears app data, then also the list files should behave same.

**Comment by Swati4star** [comment]
The text file will also be completely under the control of the user.
you can get a list of the folders under a folder through other methods also.

**Comment by ac491** [comment]
Removing the directory should move the files back to home directory or delete the files too?

**Comment by Swati4star** [comment]
Don't move the files to home directory 
Just show an alert `The folder is not empty. Do you want to delete the containing files?`
If user selects yes, delete everything, else do nothing.

**Comment by ac491** [comment]
Should I also add an option "Move to home Directory" to move files present in some directory to home directory?

**Comment by Swati4star** [comment]
Yes. add a move option also.
