### ISSUE TITLE
Show conversions history

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#137]
- Add a new option in the navigation bar `History`
- It should have the following type of operations performed by the user in chronological order : 
     - PDF created
     - PDF renamed
     - PDF deleted
     - PDF printed
     In each time, show the name of the PDF & the date when the operation was performed.
- Add an option on the action bar to delete this history also. ( Add a confirmation dialog )

**How to do?**
Maintain a database of the operations performed by the user. Whenever user do any of the above operation, add it to that database.

**Comment by shiv07tiwari** [comment]
I am working on this issue @Swati4star

**Comment by Swati4star** [comment]
Sure! And use Android room persistence library for storing the conversions.

**Comment by shiv07tiwari** [comment]
Ya sure !

**Comment by Swati4star** [comment]
@shiv07tiwari First fix the app shortcuts issue. Then move on to this one.

**Comment by vyankatesh24** [comment]
@Swati4star 
Shall I work on it, or is anyone working?

**Comment by Swati4star** [comment]
You can work on it. It's up for grabs :)

**Comment by vyankatesh24** [comment]
Ok
