### ISSUE TITLE
Disable "Create PDF" Button when no image is selected.

### ISSUE THREAD

**Issue by raghavpuri31** [Swati4star/Images-to-PDF#142]

**Comment by ShrreyaBehll** [comment]
Hi! Once 'Create PDF' button is clicked(when no images are selected) a snackbar shows up,does this is issue involves only disabling of the button or any other enhancement too?

**Comment by Swati4star** [comment]
No. just disable the button when there are no images selected.

**Comment by ShrreyaBehll** [comment]
May I work on this?

**Comment by Swati4star** [comment]
Sure @ShrreyaBehll 👍
