### ISSUE TITLE
Prevent navigation of "Main" to "Choose image", when name of the PDF file is left blank.

### ISSUE THREAD

**Issue by raghavpuri31** [Swati4star/Images-to-PDF#144]
When images are selected and we leave blank for the name of PDF file it goes back to choose images activity.  It should stay on same activity.

**Comment by Swati4star** [comment]
@raghavpuri31 I am not able to reproduce this issue. I did the following steps:
- Select `Select Images`. Select few images
- Select `Create PDF`.
- Don't write anything in the filename & press ok.

### Actual output
- I remain on the same activity only & a snackbar is displayed saying `Name cannot be blank`

**Comment by raghavpuri31** [comment]
@Swati4star Oh yes, so I think this issue is solved, but it was going back to "Select Images" activity.
