### ISSUE TITLE
Improving UI for devices with 5.x Inch or smaller screen

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#146]
UI should be improved for devices with 5.x Inch or smaller screen, I attached screenshots I took on such device i.e. Galaxy S5. The UI feels very cramped if you see camera output on UI. Also the portion of XML where "No Image is written" is taking up a lot of screen space.
![screenshot_pdf_converter_20180703-104317](https://user-images.githubusercontent.com/17274550/42200074-4fcaf28a-7eaf-11e8-92df-043e7d5cf024.png)
![screenshot_pdf_converter_20180703-105031](https://user-images.githubusercontent.com/17274550/42200075-501ec004-7eaf-11e8-90ee-b6948fbb04c3.png)

**Comment by Swati4star** [comment]
@kvsjxd The explanation is not that clear. Give specifics of what you want in the issue.

PS: Don't add GSSoc in issue name. It is open to other people also to take up. I have added GSSoC label

**Comment by kvsjxd** [comment]
Sorry for not being clear, as you can see in the new image, I have marked the areas where the screen space is being wasted.
1) The black area that I marked in the box is wasting screen space, can we expand camera canvas to cover up the black area?
2) The white area in the bottom that I marked is very large, can we minimize that area horizontally and give more screen space to the camera canvas?

![screenshot_pdf_converter_20180703-113518](https://user-images.githubusercontent.com/17274550/42201733-ae20c006-7eb6-11e8-996e-ae50f28d869c.png)

Also I was adding [GSSoC] in the title for you to identify that the issue is made by mentor. As you wish, I won't add it in future issues.

**Comment by Swati4star** [comment]
Right now, we are using a library TedPicker for above screen. I don't think we can add it these enhancements in that library.
So, we'll have to implement the whole image picker & camera clicking UI ourselves, if we want it to be this much customizable.

**Comment by Swati4star** [comment]
I'll add a topcoder tag. It's gonna take up a lot.

**Comment by Swati4star** [comment]
We have started using a new library (Mattise). That application uses device's primary camera only when clicking images.
