### ISSUE TITLE
Add app shortcuts for Android 7.0 and up

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#147]
Define shortcuts to specific actions in app. These shortcuts can be displayed in a supported launcher. Shortcuts let your users quickly start common or recommended tasks within the app. You can see the screenshot for reference. We can add shortcuts for actions like:
1) Select PDF (The action will make user select images first)
2) View Files
3) Merge PDF
4) [Any other feature]

For more information you can checkout https://developer.android.com/guide/topics/ui/shortcuts
![shortcuts](https://user-images.githubusercontent.com/17274550/42218862-8ba53332-7ee7-11e8-90c2-9fef04e95b1f.png)

**Comment by Swati4star** [comment]
The following library can be used for this purpose : https://github.com/MatthiasRobbers/shortbread

**Comment by kvsjxd** [comment]
According to me it should be tagged as cake walk. Also we don't really need a library to do this.

**Comment by Swati4star** [comment]
I'll make in intermediate.

**Comment by shiv07tiwari** [comment]
I am working on this issue.

**Comment by Swati4star** [comment]
Sure @shiv07tiwari

**Comment by Swati4star** [comment]
This issue is open for other's to take up now.

**Comment by vyankatesh24** [comment]
Would like to work it.

**Comment by Swati4star** [comment]
Sure @vyankatesh24 👍
