### ISSUE TITLE
Use same font throughout the whole app

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#149]
In View Files layout a different font is being used. Please keep a standard font throughout the whole app.
![screenshot_pdf_converter_20180703-174529](https://user-images.githubusercontent.com/17274550/42219609-1d33f0fc-7eea-11e8-804f-bcaf97f7615b.png)

**Comment by Swati4star** [comment]
Remove all the custom fonts used in the app. Let there be default font only, everywhere.

**Comment by vyankatesh24** [comment]
@Swati4star 
I did not any other layout with such font if you know 
Let me know.

**Comment by Swati4star** [comment]
We have used many different fonts in View Files fragment. Just remove those fonts.

**Comment by Swati4star** [comment]
@vyankatesh24 Are you working on this one?

**Comment by Swati4star** [comment]
In this file, https://github.com/Swati4star/Images-to-PDF/blob/a77c1aceb508cc7cf17fabde8d85b918d8b81bf9/app/src/main/res/layout/item_file.xml

Remove the `fontFamily` & `textStyle` attributes

**Comment by vyankatesh24** [comment]
Yes I am working on it.

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/192
