### ISSUE TITLE
Add ability to remove the existing password from a PDF file

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#152]
Adding the ability to remove the password from an existing PDF file either created using this app or some other app (of course user must know the password of the file before doing this operation). After removing the password of the file, the app can offer the user to overwrite the existing PDF file or save unlocked PDF as an another PDF file.

**Comment by Swati4star** [comment]
Reference : https://developers.itextpdf.com/examples/security-itext5/encrypting-decrypting-pdfs#1056-decryptpdf.java

**Comment by shiv07tiwari** [comment]
Can I start working on this issue ? @Swati4star

**Comment by Swati4star** [comment]
Yeah sure. Add this option in the view files section only.

When I click on the PDF, add the option `Remove Password`.
Do check that the PDF should already be a password protected PDF. Then, show an alert with the password. 
If everything is correct, create a new pdf (abc_unencrypted.pdf)

**Comment by shiv07tiwari** [comment]
Should i force the user to enter password if he wants to decrypt the pdf ?

**Comment by Swati4star** [comment]
You won't be able to decrypt the PDF with the password.

Regards,
Swati Garg

**Comment by shiv07tiwari** [comment]
No, I am saying for security purpose, i can allow the user to decrypt only when he enters the password

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/178
