### ISSUE TITLE
Remove some TextViews from Merge PDF

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#153]
Remove the following TextViews from Merge PDF since they are destroying the aesthetics of the app since they don't seem to be useful:

1) File Path for PDF one
2) File Path for PDF two
3) Files present on SD Card are supported.

Alternatively we can use SharedPreferences to detect if the user is viewing the Merge PDF screen for the first time and show 3rd TextView in that case or even show it as a Toast.
![screenshot_pdf_converter_20180703-181446](https://user-images.githubusercontent.com/17274550/42221071-751699e2-7eee-11e8-9986-19424859520c.png)

**Comment by Swati4star** [comment]
Sure @eddygta17

**Comment by Swati4star** [comment]
Also, reduce the size of these 2 big buttons. You can change their orientation also (whichever UI you feel looks better)

**Comment by eddygta17** [comment]
![screenshot_2018-07-22-18-20-27](https://user-images.githubusercontent.com/24777071/43045739-07da4af2-8ddc-11e8-9856-8ab84a8e3fbb.png)

**Comment by Swati4star** [comment]
The green color looks too bright.

**Comment by eddygta17** [comment]
I am using `Color.GREEN` , which color to use?

**Comment by Swati4star** [comment]
Define a new color. A bit darker shade of green.
And use that.

**Comment by eddygta17** [comment]
![screenshot_2018-07-22-21-31-38](https://user-images.githubusercontent.com/24777071/43047587-f2847df6-8df6-11e8-8ee2-41d96e64dd6d.png)

**Comment by Swati4star** [comment]
Go with this one. This looks better.
