### ISSUE TITLE
[Bug] Nothing happens when we try to add password to already password protected PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#154]
### Steps to reproduce
- Go to `View Files`
- Click on any pdf ( abc.pdf for example)
- Click `Add password`. Write a password
- A new pdf `abc_encrypted.pdf` is created
- Now, click on `abc_encrypted.pdf`
- Click `Add Password`. Type a password.
- Snackbar shows `Password added`, but nothing happens in the listing.

### Expected behaviour
- Show a snackbar with the error message `Password could not be applied to the PDF. Please check the PDF again`

**Comment by vyankatesh24** [comment]
@Swati4star 
May I work on it?

**Comment by Swati4star** [comment]
Sure!

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/190
