### ISSUE TITLE
Make refresher appear in front of all the widgets in View Files layout

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#155]
As you can see in the screenshot, the pull down refresher appear behind the yellow circle in View Files layout when pulling down to refresh. Make it appear in front of the circle when pulling down (for reference I'm using 5.1 inch screen device).
![screenshot_pdf_converter_20180703-191618](https://user-images.githubusercontent.com/17274550/42225473-3ec78cd2-7efa-11e8-97ec-bafb8650e076.png)

**Comment by vyankatesh24** [comment]
I would like to work on this

**Comment by Swati4star** [comment]
Sure @vyankatesh24 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/168
