### ISSUE TITLE
Use a button instead of a simple TextView in  View Files

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#157]
As you can see view files in the screenshot, you should remove the "Get Started Now" TextView and instead use a button to select images (the same thing that is performed by using select images button in Create PDF layout).
![screenshot_pdf_converter_20180703-191629](https://user-images.githubusercontent.com/17274550/42225734-df584a42-7efa-11e8-939b-9032bf9497cd.png)

**Comment by eddygta17** [comment]
Can I be assigned this?

**Comment by Swati4star** [comment]
Sure!

**Comment by eddygta17** [comment]
The buttons, created here are not clickable. I do not know why.

**Comment by Swati4star** [comment]
It's just a textview only right now. What's the problem?

**Comment by Swati4star** [comment]
I'll have to see the code. I can't figure out what's the problem this way.

**Comment by Swati4star** [comment]
@eddygta17 Is the issue resolved?

**Comment by Swati4star** [comment]
@eddygta17 I have figured out the solution:
Remove mSwipeView.bringToFront(); && it'll work fine

**Comment by Swati4star** [comment]
Looks good! Also remove the toast, "No PDFs right now"

**Comment by Swati4star** [comment]
Looks good! @eddygta17 Create a PR
