### ISSUE TITLE
[Bug] Encrypted PDF gets overwritten in case same pdf is encrypted again

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#158]
### Steps to reproduce
- Go to View Files
- Click on any pdf ( abc.pdf for example)
- Click Add password. Write a password
- A new pdf `abc_encrypted.pdf` is created
- Again, click on abc.pdf & select `Add password`
- Type new password & click ok
- The previous file `abc_encrypted.pdf` is overwritten

### Expected behavior
Create a new `abc_encrypted[some unique number].pdf`. Don't overwrite existing file.

**Comment by shiv07tiwari** [comment]
I am working on this issue @Swati4star .

**Comment by Swati4star** [comment]
Sure 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/181
