### ISSUE TITLE
Add ability to select images from a zip archive and create a PDF out of those images

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#159]
The app should be able to to select images from a zip archive and create a PDF out of those images.

Tip: The order of images to create PDF can be found easily by examining the order of images by their file names i.e. alphabetical order.

Note: There is a high possibility of images to have numerals and symbols in their file names, so look out for those conditions too!

**Comment by Ni3verma** [comment]
@Swati4star, I'll try to solve it.

**Comment by Ni3verma** [comment]
I have extracted the images out of zip file to a temp directory.
Now how do I use images to pdf fragment to make pdf out of these images?

**Comment by sidhuparas** [comment]
What problem are you facing? Have you taken a look at `createPdf()` function and `mImagesUri`?

**Comment by Ni3verma** [comment]
I solved it.
But I have a new one... Should I also add bottom sheet in this fragment? If yes, how do I populate it with zip files?

**Comment by vyankatesh24** [comment]
> I solved it.
> But I have a new one... Should I also add bottom sheet in this fragment? If yes, how do I populate it with zip files?

No need of bottom sheet.

**Comment by Ni3verma** [comment]
okay
