### ISSUE TITLE
Add support to convert PDF to and from other file formats 

### ISSUE THREAD

**Issue by gibcheesepuffs** [Swati4star/Images-to-PDF#160]
The app should be able to do the following tasks in this issue:
1) Convert PDF to and from below given file formats.
2) Join group of images together in the given file formats.
3) Convert the below given file formats to PDF.
4) Extract images from the below given file formats.
5) Extract images from the below given file formats and archive them to zip.
6) Convert the PDF to set of images and archive them to zip.

.zip    https://fileinfo.com/extension/zip

More information about file formats is also given, please refer to it.

.epub   https://fileinfo.com/extension/epub
.cbr    https://fileinfo.com/extension/cbr
.cbz    https://fileinfo.com/extension/cbz
.mobi   https://fileinfo.com/extension/mobi
.doc   https://fileinfo.com/extension/doc
.docx   https://fileinfo.com/extension/docx
.ppt   https://fileinfo.com/extension/pptx
.pptx   https://fileinfo.com/extension/ppt
.odt   https://fileinfo.com/extension/odt

NOTE: Refrain from using .rar format since it is non-free.

Tip 1: CBZ is actually just a zip archive, to do the task you may need to rename the files in order i.e. 1.jpg, 2.jpg, 3.jpg, 4.jpg and so on, and the archive them to zip. After that finally you can just rename the file to [filename].zip to [filename].cbz .

Tip 2: CBR is just a rar archive if you find any evidence of it being non-free (since it's rar) please do comment, we can remove it from this issue.

**Comment by aishwaryavasu0509** [comment]
hey, I am interested in this can I help?

**Comment by shady2027** [comment]
I would like to work on this feature, can you assign it to me?
Thank you!
