### ISSUE TITLE
Add about screen

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#162]
Add about screen in the app to display important information like:

* Developer name/profile
* Version
* Libraries used
* Report issue
* Contact
* GitHub repository link
* Google Play/F-Droid link
* Contributor list
* License/Restrictions
Etc.

**Comment by Swati4star** [comment]
Can you provide a sample UI for this? @kvsjxd

**Comment by kvsjxd** [comment]
You can take reference from these apps
![screenshot_fasthub-libre_20180704-225021](https://user-images.githubusercontent.com/17274550/42290069-bd456e58-7fe0-11e8-9fb5-c92fddcd0bef.png)
![screenshot_fasthub-libre_20180704-225026](https://user-images.githubusercontent.com/17274550/42290073-c07beeda-7fe0-11e8-9428-36260376ae5a.png)
![screenshot_xda_20180704-225043](https://user-images.githubusercontent.com/17274550/42290074-c0f2a9d0-7fe0-11e8-9ed7-0a24b9b0fa7b.png)

**Comment by shiv07tiwari** [comment]
Working on this ! @Swati4star

**Comment by Swati4star** [comment]
@shiv07tiwari  Some information you might need for this:
- LIcense link : https://github.com/Swati4star/Images-to-PDF/blob/master/LICENSE.md
- Privacy policy : https://sites.google.com/view/privacy-policy-image-to-pdf/home
- playstore link: https://play.google.com/store/apps/details?id=swati4star.createpdf
- website link : http://swati4star.github.io/Images-to-PDF/
- Send an email : Use my email id (swati4star@gmail.com)
- Join slack : https://goo.gl/J6Hrd4

Ask me if you need any other info
