### ISSUE TITLE
Add cloud storage support

### ISSUE THREAD

**Issue by gibcheesepuffs** [Swati4star/Images-to-PDF#164]
Add support for the following features:
* Selecting images from cloud storage services.
* Uploading PDF(and other file formats) natively from this app to cloud storage services.

Cloud Services that can be supported:

* Google Drive
* MEGA
* OneDrive (SkyDrive)
* Dropbox
* Box
* Amazon Cloud Drive
* GMX
* MediaFire
* pCloud
* SugarSync
* ownCloud
* Flickr

Resources:
https://developers.google.com/drive/api/v3/downloads
https://docs.mega.nz/sdk/doc/api.html
https://developer.microsoft.com/en-us/onedrive
https://www.dropbox.com/developers
https://developer.box.com/
https://developer.amazon.com/docs/amazon-drive/ad-sdk-android.html
https://www.mediafire.com/developers/
https://docs.pcloud.com/sdks/java.html
https://www.sugarsync.com/dev/using-api.html
https://doc.owncloud.org/
https://www.flickr.com/services/api/
https://code.google.com/archive/p/flickrj-android/
https://github.com/boncey/Flickr4Javaes/CloudStorage;serviceIds=Dropbox;platformId=Android

**Comment by Swati4star** [comment]
Is there any library or service which can provide this support?

**Comment by kvsjxd** [comment]
I updated the issue

**Comment by kvsjxd** [comment]
I updated the issue.

**Comment by kvsjxd** [comment]
Any update on "under-review" tag?

**Comment by lgoloh** [comment]
Hi! Could I add these features for Google Drive?

**Comment by Swati4star** [comment]
Sure @lgoloh 👍

**Comment by vyankatesh24** [comment]
@lgoloh Are you still working on it?

**Comment by jddeep** [comment]
@Swati4star I would like to work on it. But before that please review #645

**Comment by jddeep** [comment]
@Swati4star I am working on this issue first and then will go back to #132 .
