### ISSUE TITLE
Add image marking/doodling support

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#165]
Add image marking/doodling support in Edit Images and PDFs. You can take reference from the difference between the two attached images.
![screenshot_pixel_launcher_20180704-083111](https://user-images.githubusercontent.com/17274550/42254746-b75f2de8-7f37-11e8-9cef-2a9945c477ef.png)
![img-20180704-wa0002](https://user-images.githubusercontent.com/17274550/42254796-f38f8fb0-7f37-11e8-87d1-da6ab5dd2e81.jpg)

**Comment by tanvidadu** [comment]
Is there any specific library that can be used?

**Comment by kvsjxd** [comment]
Try using DrawingView class

**Comment by kvsjxd** [comment]
There is a tutorial on that, see if it helps https://code.tutsplus.com/tutorials/android-sdk-create-a-drawing-app-touch-interaction--mobile-19202

**Comment by Swati4star** [comment]
We are already using this library for image filters. This only can be used image doodling support also:
https://github.com/burhanrashid52/PhotoEditor

**Comment by shiv07tiwari** [comment]
@Swati4star  where exactly should we add this option ?

**Comment by Swati4star** [comment]
This can be added in `Filter images`. In the bottom strip, we can have 2 options: Doodle, filters.
On filters, the filters should open up.
On selecting doodle option, doodling should get enabled on the image

**Comment by shiv07tiwari** [comment]
Working on this @Swati4star
