### ISSUE TITLE
3 dot menu is only shown in View Files activity

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#169]
3 dot menu is only shown in View Files activity and not shown on:
* Main Screen
* Merge PDF
Make it accessible via these two activities too.

**Comment by Swati4star** [comment]
@kvsjxd The issue is not clear. What do you want in the 3 dot menu for the main screen & merge PDF?
There is a reason the menu is not there (because we don't have any settings to be applied for these screens)

**Comment by kvsjxd** [comment]
I meant that the 3 dot menu is visible only on View Files screen, how about moving compression settings to a new activity and make that activity accessible via menu? Because assuming most of the users won't be changing default compression settings anyway.

**Comment by Swati4star** [comment]
The compression setting should be on main page only. That setting is required while creating PDF. So, it should definitely be on main page only.

**Comment by Swati4star** [comment]
The issue is not very informative. Create separate issue for the specific option you want in different screens to be present on a particular screen and it's purpose.
