### ISSUE TITLE
Camera Rotation

### ISSUE THREAD

**Issue by milisharma27** [Swati4star/Images-to-PDF#172]
There should be an availability of camera rotation. As in, when we change the orientation of the mobile screen to click an image in a portrait form, the camera should be flexible enough to flip itself according to the movement of the phone.

**Comment by Swati4star** [comment]
Are you talking about the black space that comes before & after the picture area? Because, I think camera is rotating well as per the needs.

**Comment by Swati4star** [comment]
@milisharma27 ?

**Comment by kvsjxd** [comment]
Issue not clear enough.

**Comment by Swati4star** [comment]
Similar to this then https://github.com/Swati4star/Images-to-PDF/issues/146

**Comment by milisharma27** [comment]
Maybe. It is kind of a part of #146.
