### ISSUE TITLE
Allow users to edit images in preview mode

### ISSUE THREAD

**Issue by milisharma27** [Swati4star/Images-to-PDF#173]
After cropping the clicked or selected image, a preview of the edited image should be visible to the user so that he/she can check the image accordingly before converting to PDF.

**Comment by Pratul1997** [comment]
@milisharma27 These features are good, can you highlight me whether we require another layer of confirmation of edited image before we finalize the conversion to PDF?

**Comment by milisharma27** [comment]
@Pratul1997 Yes, we do require one more step of confirmation before converting to PDF because once the PDF is created, we won't have an option to edit it later on.

**Comment by Swati4star** [comment]
@milisharma27 is your issue different from https://github.com/Swati4star/Images-to-PDF/issues/88?

**Comment by milisharma27** [comment]
@Pratul1997 Yes, a little bit. #88 is an issue to preview the PDF in making before the final conversion. I have put an issue to have a preview of the edited(cropped/rotated) image before saving the changes to the image before using it for PDF conversion.

**Comment by Swati4star** [comment]
I think it's exactly the same issue. Both have the same purpose. Both allows user to view final images just before creating PDF.

**Comment by milisharma27** [comment]
@Swati4star I mean, if the user is dissatisfied with the edited image, he/she can change at that moment before viewing the rough module of PDF to be converted.

**Comment by Swati4star** [comment]
I don't think showing 2 different previews is gonna be helpful. The rough PDF preview is also going to show what final images will look like & your preview is also going to do that only.

**Comment by Pratul1997** [comment]
@milisharma27 @Swati4star but while trying to crop the image I was not able to manually crop my image and see the image after cropped and being converted to PDF?

**Comment by Swati4star** [comment]
I am updating the issue title & description.

The issue is:

User should be allowed to edit images in preview mode. (This can only be implemented after the preview mode is ready)

**Comment by milisharma27** [comment]
Okay @Swati4star 
Kindly make the required changes in the way the issue can be more elaborative to the audience.

**Comment by Swati4star** [comment]
We have added the preview feature & it allows users to rearrange images.
A user can always come back to home screen & edit images (crop, apply filter). It doesn't make sense to add these options again in the preview feature.
