### ISSUE TITLE
[New Feature] Convert webpage to PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#176]
Add option to convert a webpage to PDF.
The process should be like this:
- Add a new option in the navigation drawer `Webpage to PDF`
- There should be an option to enter a URL
- If the URL is invalid, show appropriate error message
- If it's a valid URL, open a dialog for user to enter the name of PDF.
- When PDF is created, show the snackbar (similar to what happens on home page)

Reference:
https://developers.itextpdf.com/content/itext-7-converting-html-pdf-pdfhtml/chapter-7-frequently-asked-questions-about-pdfhtml/can-i-generate-pdf-url-instead-file-disk

**Comment by shiv07tiwari** [comment]
Can I work on this issue ?

**Comment by Swati4star** [comment]
Sure @shiv07tiwari

**Comment by Swati4star** [comment]
The itextpdf doesn't seem to do this task properly.
