### ISSUE TITLE
[New Feature] Convert text to PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#177]
Add option to convert a webpage to PDF.
The process should be like this:
- Add a new option in the navigation drawer `Text to PDF`
- There should be an option to select text file
- On clicking it, the file picker should open up
- When PDF is created, show the snackbar (similar to what happens on home page)

Reference:
https://developers.itextpdf.com/content/itext-7-examples/itext-7-differences-itext-5/text-pdf

**Comment by shiv07tiwari** [comment]
Working on this issue @Swati4star .
