### ISSUE TITLE
Display number of images selected

### ISSUE THREAD

**Issue by milisharma27** [Swati4star/Images-to-PDF#183]
In order to enhance the app, we could show the number of selected images for PDF conversion.

**Comment by Swati4star** [comment]
@vyankatesh24 Are you working on this issue?

**Comment by vyankatesh24** [comment]
@Swati4star 
I will work on it

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/191

**Comment by vyankatesh24** [comment]
![image](https://user-images.githubusercontent.com/18503975/42612798-fbd6757e-85ba-11e8-9c81-9a7d2cfb8fa1.png)

@Swati4star 
I forgot to remove No of images textview after pdf creation
Shall I fix this in current PR
Or will you create new issue.

**Comment by Swati4star** [comment]
Create a new issue. Either I'll do it by tonight, or you can also open one now
