### ISSUE TITLE
UI changes in `Filter images` screen

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#185]
Currently, the `filter images` screen looks like this:
<img width="320" alt="screen shot 2018-07-09 at 11 38 51 am" src="https://user-images.githubusercontent.com/9164477/42433386-c39c24ba-836c-11e8-8549-f5eb5776a10b.png">

### Make following enhancements to it:
- Add a greyish background color to bottom strip
- Change the filter icons (`None`, `Sepia`, `Black & white`) to look like this:
![img_20180709_114657](https://user-images.githubusercontent.com/9164477/42433720-2a8ba208-836e-11e8-9afa-2c948c213269.jpg)
(Use any sample image of a flower & show it on none, sepia & black-white icons below in circular images, & write the name of effect below those images)
- Change the backgroung color of `Save Current` button to orange (our app's color) & text color to white
- Change the right arrow icon to something which doesn't have greyish background.
- In the action bar, change the done text to tick mark icon
- Use two way list view to add filters in the bottom strip (so that it becomes easier to add more filters )

**Comment by Sabihashaik** [comment]
@Swati4star I would like to work on this issue. 
Can you clarify what you mean by the Two way list view?

**Comment by Swati4star** [comment]
I was actually referring to this one : https://github.com/lucasr/twoway-view
(But this repository seems to be archived now)
The purpose of this was horizontal list view.

I think we can create horizontal list view using recycler view also. So, you may use that only.

**Comment by Sabihashaik** [comment]
@Swati4star Ok, So something such as this?  [Horizontal list view using Recycler view ](https://stackoverflow.com/questions/28460300/how-to-build-a-horizontal-listview-with-recyclerviewl)

**Comment by Swati4star** [comment]
Yes @Sabihashaik 👍

**Comment by Swati4star** [comment]
@Sabihashaik Any updates?

**Comment by Sabihashaik** [comment]
Yes. Working on it. Will send a PR quite soon.

**Comment by Sabihashaik** [comment]
@Swati4star I have a question, I have set everything up, a Recycler View with circle images and such. However, I'm facing a problem when trying to access my previously made functions (None filter, Sepia etc) through which position is being clicked.
I'm checking which position is being clicked in a new class called RecyclerViewAdapter and then passing the value to PhotoEditor class where I have a function to match the position with the corresponding filter function. 
Also, Here is a screenshot of the updated layout.
![updated layout](https://user-images.githubusercontent.com/21033484/42695310-09635d0e-86c6-11e8-8e61-5d1e59564b51.jpeg)

**Comment by Sabihashaik** [comment]
@Swati4star  I'm able to get the position of the item being clicked, but not able to set the Image View with the new image once clicked.
It shows a null pointer exception when I try to set it from the Recycler View Adapter, like if item position is 0, I call the none function from photo editor but it returns a null pointer exception. 

Googling seems like I have to set up an interface to handle callbacks?

**Comment by Swati4star** [comment]
What you can do it...

- Create a new interface class `OnFilterItemClickedListener` & add a new function to it to handle clicks (https://github.com/Swati4star/Images-to-PDF/tree/master/app/src/main/java/swati4star/createpdf/interfaces)
- Make the `PhotoEditor.java` implement it
- Pass an instance of OnFilterItemClickedListener to the new adapter

**Comment by Sabihashaik** [comment]
@Swati4star Thank you! That works! :)
