### ISSUE TITLE
[New Feature] Convert excel to PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#186]
### What to do?
- Add a new option in the navigation drawer `Excel to PDF`
- In that fragment, allow users to select an existing excel file
- Ask for the output PDF name

### Reference:
http://thinktibits.blogspot.com/2012/12/POI-iText-Convert-XLS-to-PDF-Java-Program.html

**Comment by manjutapali** [comment]
Can I work on this?

**Comment by Swati4star** [comment]
Sure @manjutapali

**Comment by manjutapali** [comment]
@Swati4star 
Hi,
To convert Excel to PDF, I need to read the excel file and tabulate it to write in PDF file. The link which you suggested uses Apache POI library. The library is available as jar file and needs to remove the dependencies from it to use in android. Here is what I found,

https://stackoverflow.com/questions/24442758/how-to-satisfy-dependencies-for-apache-poi-on-android

Can you please confirm and guide me to use in the project.

**Comment by manjutapali** [comment]
I am not sure about reading excel file using iText7.
I meant Apache POI is used to read the excel file and use Itext7 to write it in PDF.

**Comment by manjutapali** [comment]
I referred the following link - https://stackoverflow.com/a/45907948/4865744
Please read the first comment.

**Comment by manjutapali** [comment]
Ok.. Thank you. I'll try to do the same as you said.

I just want to clarify how many rows and columns can be added in the page. If it's relative to the number of columns then it's not good to do for a large number of column sheets.

**Comment by Swati4star** [comment]
What do you mean by how many rows & columns can be added? you can read that from excel sheet.

**Comment by manjutapali** [comment]
I thought PDF conversion should be of A4 size sheet.

**Comment by manjutapali** [comment]
Hi @Swati4star,

Reading an excel file as a text file with input stream doesn't give the values of the rows and columns in a formatted style. Since it has a proprietary binary format which can be read using Workbook which is available in the Apache POI library. I did try to go through many links, everywhere they used Apache POI library. If you have any specific links to refer please share.

I have attached the output of reading excel sheet.

<img width="1230" alt="screen shot 2018-10-04 at 4 55 29 pm" src="https://user-images.githubusercontent.com/9125374/46471444-721aab00-c7f7-11e8-9c70-cce1ee80df58.png">

**Comment by Swati4star** [comment]
Will have to include apache POI library only then. I don't know how to integrate that in the project, will have to google only.

**Comment by manjutapali** [comment]
Ok. I'll try to do it and let u know if something breaks up.

**Comment by santoshhiremani** [comment]
I'm also looking solution on Apache POI in #250. Once we figure out something we can convert all MS docs using this library, I tried including all dependent jars of POI which was around 15-20 MB but still failed.  Library has native java awt dependency a lot thats making  trouble.

**Comment by jddeep** [comment]
@Swati4star @vyankatesh24 I would like to work on this.

**Comment by jddeep** [comment]
@Swati4star please merge #648 and add APP_ID from your side and test it. Thanks.

**Comment by vyankatesh24** [comment]
> @Swati4star @vyankatesh24 I would like to work on this.

Wait till your PRs get merged.

**Comment by Swati4star** [comment]
@jddeep You can start working on this one now! 👍
