### ISSUE TITLE
[Code Cleanup] Create a PDFOptions class

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#196]
### What to do?
- Create a new package [here](https://github.com/Swati4star/Images-to-PDF/tree/master/app/src/main/java/swati4star/createpdf) named `objects`
- Create a new class `PDFOptions` in `objects`
- This class should have 
```
imagesUri :  ArrayList<String>
fileName : String
isPasswordProtected : boolean
password : String
quality : integer
pageSize : com.itextpdf.text.Rectangle
```
- Use this class in `CreatePdf` function

**Comment by milisharma27** [comment]
@Swati4star 
I do not get it. 
What will it do?

**Comment by Swati4star** [comment]
This is just for code cleanup. Adding class. It will make adding more options for PDF formatting easier.

**Comment by milisharma27** [comment]
Okay.

**Comment by vyankatesh24** [comment]
@Swati4star 
May I work on it?

**Comment by Swati4star** [comment]
@vyankatesh24 
I actually did create a PDFOptionsClass (https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/java/swati4star/createpdf/model/PDFOptions.java)
but haven't used it anywhere. You can either use this one or create a new one(and delete this one)

What I expect in this issue is:

- You create a base PDFOptions Class (have common functions in this one)
- From this class, we'll have 2 derived classes 
     - ImageToPDFOptions (this can have image specific properties)
     - TextToPDFOptions (this can have text specific one's)

Use this class to in the code then, to create PDF

**Comment by vyankatesh24** [comment]
Ok

**Comment by vyankatesh24** [comment]
All three classes in 'objects' package right?

**Comment by Swati4star** [comment]
@vyankatesh24  Don't create a new package, add it to `model` package only.

**Comment by vyankatesh24** [comment]
Ok
