### ISSUE TITLE
Retain the order selected by user in View files

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#197]
### Steps to reproduce
- Go to `View Files` section
- Select the sort icon in action bar

### Actual behaviour
There is some random by which the files are displayed by default

### Expected
- Retain the order selected by the user in view files
- For example, if I select `Sort by name` once, the files should always be selected by name, unless I select some other option.

<img width="325" alt="screen shot 2018-07-12 at 9 02 23 pm" src="https://user-images.githubusercontent.com/9164477/42643616-313d5fa0-8617-11e8-9c01-3fdbd5ac4cad.png">

**Comment by vyankatesh24** [comment]
@Swati4star 
I would like to work on it.

**Comment by vyankatesh24** [comment]
What Sorting order to be kept default?

**Comment by Swati4star** [comment]
Sure. By name.

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/204
