### ISSUE TITLE
Set page size dialog opens up on Filter Images click

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#202]
When we click on Filter images Set page size dialog opens up also.

**Comment by vyankatesh24** [comment]
@Swati4star 
I will work on it.

**Comment by vyankatesh24** [comment]
shall I?

**Comment by Swati4star** [comment]
Sure

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/206
