### ISSUE TITLE
Can select image multiple times

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#205]
## Steps to reproduce
 * Click on Select Images.
 * Select Gallery Option
 * Select Image
 * Click on Check-mark in Action bar
 * Again Click on Select Images.
 * Selected Image will again available to select

**Comment by Swati4star** [comment]
Does the final PDF also have multiple instances of image?

**Comment by vyankatesh24** [comment]
Yes.

**Comment by Swati4star** [comment]
Then, I guess it's fine. Doesn't seem to be an issue.

**Comment by vyankatesh24** [comment]
Ok. Shall I Close?

**Comment by Swati4star** [comment]
Yes!
