### ISSUE TITLE
Add a new option in `View Files` Section for `Select all`

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#208]
- Open `View Files` from the navigation drawer

### What to do?
- Add a new option in the action bar for `Select all`
- On clicking that, all the PDF files should be selected

<img width="334" alt="screen shot 2018-07-13 at 9 30 58 pm" src="https://user-images.githubusercontent.com/9164477/42701518-6acbbdca-86e4-11e8-99e9-3cf9b490e8a3.png">

**Comment by milisharma27** [comment]
:+1: Yes, a good point not to be missed. :)

**Comment by shiv07tiwari** [comment]
Can I work on this @Swati4star

**Comment by Swati4star** [comment]
Sure @shiv07tiwari

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/210
