### ISSUE TITLE
Supporting tablets in landscape view.

### ISSUE THREAD

**Issue by Azooz2014** [Swati4star/Images-to-PDF#21]
Hi , this is my first time contributing to an open source software and i tried this app and its pretty good , but i noticed that it's doesn't rotate to landscape when the device is in landscape, so i came up with two layout designs , the first one is pretty simple but it has a lot of empty space.

![design 1](https://user-images.githubusercontent.com/7429229/31225205-a78254b0-a9d9-11e7-8dc4-9fc276dc6c4b.jpg)

The second design i think it suits a tablet more than the first one, but i don't know how to implement the idea yet.

![design 2](https://user-images.githubusercontent.com/7429229/31225278-fa3489da-a9d9-11e7-9059-70848c33c13f.jpg)

So what do you think?!

**Comment by Swati4star** [comment]
Hi @Azooz2014 
It's a great suggestion.
In my opinion, it would be easier to implement the first right now, because, we are using TedPicker for Camera/gallery operations.

also, in the  left, are you displaying the already existing PDFs?

**Comment by Azooz2014** [comment]
yes

**Comment by Azooz2014** [comment]
@Swati4star
Yes

**Comment by Swati4star** [comment]
Okay. You can start with it 👍

**Comment by Azooz2014** [comment]
@Swati4star Hi, 
I have finished putting the layout together, i had to make few modification to MainActivity.java and AndroidManifest.xml.

In MainActivity i have created a new method that checks wither the device is in landscape or portrait in order to choose the right layout to display.

In AndroidManifest i had to change both android:screenOrientation from portrait to sensor.

I hope you don't mind those changes , should i pull request directly to your project or should i commit the changes to my forked version first for you to review the project before pulling request to your main project?

**Comment by Swati4star** [comment]
Do some changes. Create a PR. I will review that, and in case, it requires some changes, keep pushing the code into that branch.

**Comment by Azooz2014** [comment]
What branch should i create PR to it?

**Comment by Swati4star** [comment]
make it to master only.

**Comment by Azooz2014** [comment]
It's done please check the pull request 👍🏻

**Comment by Swati4star** [comment]
Being solved by https://github.com/Swati4star/Images-to-PDF/pull/22
