### ISSUE TITLE
change few icons

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#212]
- Change heavy tick mark icon. This looks a lot bold as compared to the search icon
<img width="328" alt="screen shot 2018-07-14 at 3 46 55 pm" src="https://user-images.githubusercontent.com/9164477/42723530-2aabd880-877d-11e8-9d44-eff309365970.png">

- Change the compress the image icon to something more relevant to compression
<img width="173" alt="screen shot 2018-07-14 at 3 48 16 pm" src="https://user-images.githubusercontent.com/9164477/42723549-63d18812-877d-11e8-9ae2-c1f47f3f898a.png">

**Comment by vyankatesh24** [comment]
![image](https://user-images.githubusercontent.com/18503975/42820510-fd961788-89f3-11e8-883e-83a1604af76c.png)
@Swati4star 
Shall I use this icon

**Comment by Swati4star** [comment]
@vyankatesh24 It looks good. Just change the color of the icon

**Comment by vyankatesh24** [comment]
Ok

**Comment by vyankatesh24** [comment]
![image](https://user-images.githubusercontent.com/18503975/42825119-f6320f00-89fe-11e8-9ebb-4980b6c88301.png)



After Selection
![image](https://user-images.githubusercontent.com/18503975/42824416-708a67d6-89fd-11e8-873a-a644e5c52c04.png)


Before Selection
![image](https://user-images.githubusercontent.com/18503975/42824462-80e4838c-89fd-11e8-83d8-42c87912cd47.png)

is this ok?
Shall I add Deselect all feature or will you create a new issue?

**Comment by Swati4star** [comment]
Looks good!
add selection/deselection also in this issue only. I'll increase the difficulty level of this issue.

**Comment by vyankatesh24** [comment]
Ok
