### ISSUE TITLE
[Bug] Create PDF button is disabled even when an image is selected

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#213]
### Steps to reproduce
- Go to any other gallery app. Select any image.
- Select share button. Choose `PDF Converter` application.
<img width="344" alt="screen shot 2018-07-14 at 3 58 29 pm" src="https://user-images.githubusercontent.com/9164477/42723618-f2318b24-877e-11e8-9390-99bc97dd523a.png">

The above view opens up. The `Create PDF` button should not be disabled.

**Comment by eddygta17** [comment]
@Swati4star I have been unable to rectify the problem, any button placed on that screen is not able to click, but in other screens buttons can be clicked. Rest of the functions work properly.

**Comment by Swati4star** [comment]
@eddygta17 I have figured out the solution:
Remove `mSwipeView.bringToFront();` && it'll work fine

**Comment by vyankatesh24** [comment]
Hi @Swati4star 
I would like to work on it

**Comment by Swati4star** [comment]
Sure.
