### ISSUE TITLE
Add set as default option in Page Size dialog

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#214]
<img width="309" alt="screen shot 2018-07-14 at 4 00 55 pm" src="https://user-images.githubusercontent.com/9164477/42723627-2cb266e2-877f-11e8-89e6-4619ad4d3b51.png">

Add a checkbox at the bottom : `Set as default`

If that checkbox is checked, set the current selected page size as default option. & show that option in the first radio box from next time onwards.

**Comment by vyankatesh24** [comment]
Would like to work on it
