### ISSUE TITLE
UI changes in View Files fragment

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#215]
<img width="328" alt="screen shot 2018-07-14 at 4 02 42 pm" src="https://user-images.githubusercontent.com/9164477/42723639-647f9504-877f-11e8-96f1-13455a7e6520.png">

We have a lot of options in the dropdown menu.

### What to do?

- Create a new strip at the top
- It should have name & icons for following : New directory, Move files, move files to home directory, delete directory.
- The functioning should be same as before
- Remove these options from drop down menu,

**Comment by shiv07tiwari** [comment]
The strip should be just above the pdf list, and below the Toolbar, right ? @Swati4star

**Comment by Swati4star** [comment]
Yes. & the PDF list should start below that.

**Comment by shiv07tiwari** [comment]
Okay, Can I work on this ?

**Comment by Swati4star** [comment]
Sure @shiv07tiwari 👍
