### ISSUE TITLE
Show previous image button also in filter image screen

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#216]
The filter image screen currently has this UI:
<img width="337" alt="screen shot 2018-07-14 at 4 51 05 pm" src="https://user-images.githubusercontent.com/9164477/42723902-1f99d164-8786-11e8-9e10-1865b433ee52.png">

- Add a previous arrow button also by the left of `Showing 1 of 1 images`
- It should allow users to edit previous image

**Comment by vyankatesh24** [comment]
I would like to work on it.

**Comment by Swati4star** [comment]
Sure @vyankatesh24 👍
