### ISSUE TITLE
Show directory structure in View files section

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#217]
- Currently, we can move files to a newly created directory
- But, after the files are moved, there isn't any change in the UI
- A directory type structure should be there in view files. It means we should have folders also in the list view. On selecting the particular folder, it's content should open up.

<img width="327" alt="screen shot 2018-07-14 at 4 55 01 pm" src="https://user-images.githubusercontent.com/9164477/42723943-abb86af2-8786-11e8-9406-13164b34cc36.png">

**Comment by Swati4star** [comment]
Use any of the library:
https://github.com/TellH/RecyclerTreeView
https://github.com/bmelnychuk/AndroidTreeView

**Comment by Lilus** [comment]
Hi, is anybody working on this issue?

**Comment by Swati4star** [comment]
No..

**Comment by Lilus** [comment]
Okay, then I will take this issue. Thank you

**Comment by Swati4star** [comment]
@Lilus Did you do any work related to this issue?

**Comment by Ni3verma** [comment]
@Swati4star I didn't understand the issue :confused: 
what do you mean by this?
>Currently, we can move files to a newly created directory

and all of the files are stored in PDFfiles folder in phone storage. so why do you want a directory structure?

**Comment by Swati4star** [comment]
We can leave this issue.

@Ni3verma We used to have a functionality to move PDFs to a new directory in `view Files`. But now, I have removed it, as it was creating confusion with the users
