### ISSUE TITLE
Edit option not working

### ISSUE THREAD

**Issue by milisharma27** [Swati4star/Images-to-PDF#220]
Once the PDF is created, the edit option is not working.
![edit option](https://user-images.githubusercontent.com/33100116/42725935-ef266d3e-87a9-11e8-9e95-e1f96f954987.jpg)

**Comment by Swati4star** [comment]
In which application are you viewing this PDF?

**Comment by milisharma27** [comment]
WPS Office

**Comment by Swati4star** [comment]
So, that's the issue with your app only. We are just creating the PDF. The PDF viewer is not managed by us

**Comment by milisharma27** [comment]
Okay, got it.
