### ISSUE TITLE
Show the text file name after file is selected

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#221]
<img width="325" alt="screen shot 2018-07-15 at 12 40 48 am" src="https://user-images.githubusercontent.com/9164477/42727703-081fd4c8-87c9-11e8-8555-2cc74ab2f73c.png">

### Steps to reproduce
- Select `Text to PDF` from navigation drawer
- Click on `Select Text file`
- A file chooser opens up. Selct a file. Nothing changes in the UI

### Expected behaviour
- Just like, we show image count after the images is selected, show the selected txt file name in this screen. `Text file : <file name>`

<img width="346" alt="screen shot 2018-07-15 at 12 52 57 am" src="https://user-images.githubusercontent.com/9164477/42727750-715a9734-87c9-11e8-8caa-758558ec5b55.png">

**Comment by vyankatesh24** [comment]
I would like to work on it.

**Comment by Swati4star** [comment]
Sure @vyankatesh24 👍
