### ISSUE TITLE
Add More Enhancement Section in Text to PDF fragment 

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#223]
### What to do?
- Just like, we have `More Enhancement options` in home fragment, create similar in `Text to PDF` also.
- For now, add only 1 option to it, `Edit Font size`. It's 11 by default. (Show default value also, just like Compress the image option in home fragment)
- On clicking this option, a dialog should open up. `Enter font size`
<img width="342" alt="screen shot 2018-07-15 at 12 57 34 am" src="https://user-images.githubusercontent.com/9164477/42727778-154fb180-87ca-11e8-8d33-e92b62e098a2.png">

**Comment by shiv07tiwari** [comment]
Working on this @Swati4star .

**Comment by Swati4star** [comment]
@shiv07tiwari Sure!
