### ISSUE TITLE
Add action to snackbar when text is converted to PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#224]
The snackbar when we create a PDF is:
<img width="411" alt="screen shot 2018-07-15 at 2 28 59 pm" src="https://user-images.githubusercontent.com/9164477/42732245-75df1c54-883b-11e8-8416-0abd1c43139e.png">

It has an action to view the PDF. This opens up the newly created PDF.

### What to do?
- Add the same action to snackbar after the text os converted to PDF.
- Currently we have just a normal snackbar with `PDF created` message

**Comment by shiv07tiwari** [comment]
Can I do this @Swati4star  ?

**Comment by Swati4star** [comment]
Sure!
