### ISSUE TITLE
Do not allow spaces as PDF name.

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#23]
Right now, the user can pass space or tabs as pdf name. This should not be allowed. Just add a check for it, and notify the user.

**Comment by blottn** [comment]
I can take a look at this.

**Comment by Swati4star** [comment]
This is already being worked on  by @AshanthaLahiru
https://github.com/Swati4star/Images-to-PDF/pull/27

**Comment by AshanthaLahiru** [comment]
Completed.
