### ISSUE TITLE
Add more filters in filter images screen

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#234]
This is a list of filters that can be applied using PhotoEditor library we are using:
https://github.com/burhanrashid52/PhotoEditor/blob/b32e40c091f336d4123da45da901feacb66972fd/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/PhotoFilter.java

We currently have only 2 filters : None, black & white, sepia
<img width="321" alt="screen shot 2018-07-16 at 7 40 09 pm" src="https://user-images.githubusercontent.com/9164477/42763260-2aa8511a-8930-11e8-88e4-13c9f20d58ff.png">

Add the filters listed in above link also to the application

**Comment by shiv07tiwari** [comment]
I am working on this @Swati4star
