### ISSUE TITLE
Files are getting Overwritten in Text To PDF

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#238]
If we create a file with the same name in Text To PDF, the file contents are getting overwritten.

**Comment by vyankatesh24** [comment]
May I work on it?

**Comment by Swati4star** [comment]
Sure @vyankatesh24

**Comment by Swati4star** [comment]
We have done similar thing in images to PDF also, you can use the same function in fileutils to check for file with same name

**Comment by vyankatesh24** [comment]
Ok

**Comment by vyankatesh24** [comment]
@Swati4star 
Is Text to PDF working correctly at your side?
It's crashing on my side on create pdf click.

**Comment by vyankatesh24** [comment]
I think the problem is with Font Size.

**Comment by Swati4star** [comment]
It was working fine for me. If there's some crash, create a new issue for that. You can submit a PR for that first.

**Comment by vyankatesh24** [comment]
@Swati4star 
I will work on that issue later the issue is the default font size not set needs to give every time.
