### ISSUE TITLE
Persist selection of images

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#24]
Steps to reproduce this bug.
1. Select some images
2. Click on tick mark
3. Click again on select images.

It shows no selected images already.

**Comment by blottn** [comment]
If nobody is already looking at this I can.

**Comment by Swati4star** [comment]
Sure. Go ahead with this. :+1:

**Comment by blottn** [comment]
Should be fixed, see PR #29

**Comment by Swati4star** [comment]
Fixed.
