### ISSUE TITLE
Few UI changes

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#242]
- Change the black border to white in `View Files`
<img width="329" alt="screen shot 2018-07-19 at 11 14 04 am" src="https://user-images.githubusercontent.com/9164477/42923792-020381be-8b45-11e8-9daa-5d6b9b509e7d.png">

- Make the UI of `Text to PDF` similar to `Create PDF`
<img width="334" alt="screen shot 2018-07-19 at 11 16 21 am" src="https://user-images.githubusercontent.com/9164477/42923847-3dbd0342-8b45-11e8-8e78-b7d29dbdc185.png">
<img width="338" alt="screen shot 2018-07-19 at 11 16 55 am" src="https://user-images.githubusercontent.com/9164477/42923867-4f6fcde0-8b45-11e8-8aef-9990bba0e55b.png">

Add a horizontal line before enhancement options
Remove extra left margin in `Font Size` option
Remove the margin between the 2 buttons (Select text file & create PDF)

- Remove left margin in `(Default:<>)` option
<img width="313" alt="screen shot 2018-07-19 at 11 20 54 am" src="https://user-images.githubusercontent.com/9164477/42923985-e10aa860-8b45-11e8-8262-09b6b6512ed2.png">

**Comment by vyankatesh24** [comment]
I would like to work on it.

**Comment by Swati4star** [comment]
Go ahead with this one.

**Comment by vyankatesh24** [comment]
![image](https://user-images.githubusercontent.com/18503975/42932667-8f0b3370-8b60-11e8-9274-9841b891f2cf.png)

![image](https://user-images.githubusercontent.com/18503975/42932683-97431fd0-8b60-11e8-89a5-ca40cd303cd5.png)

![image](https://user-images.githubusercontent.com/18503975/42932691-9bdc82c0-8b60-11e8-87f8-b0f73f983b4c.png)

**Comment by Swati4star** [comment]
Looks good. 

Can you also change the input type on font size dialog to number, so that numbers keyboard comes up.

**Comment by vyankatesh24** [comment]
Ok
