### ISSUE TITLE
Add an option to set default font size

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#243]
<img width="313" alt="screen shot 2018-07-19 at 11 20 54 am" src="https://user-images.githubusercontent.com/9164477/42924006-fbc4aaa2-8b45-11e8-9484-e809b00f24f4.png">

- Add a new checkbox in this dialog (`Set as default`)
- On clicking this, make the entered size as default

**Comment by vyankatesh24** [comment]
Shall I work on it?

**Comment by Swati4star** [comment]
Sure!

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/253
