### ISSUE TITLE
Wrong filename is shown in text to PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#247]
![screenshot_20180719-170757](https://user-images.githubusercontent.com/9164477/42940746-3380c7be-8b78-11e8-82bf-b851781a9053.jpg)

### Steps to reproduce
- Download some txt file. My file's name was `sample.txt`
- Open our app. Select `Text to PDF`
- Select the above-downloaded file
- The file name shown in the above view is some random number. 

### Expected behaviour
- The actual file name should be shown (In this case, it should be `sample.txt`)

**Comment by Swati4star** [comment]
what was the name of the file you selected?

**Comment by eddygta17** [comment]
dumbo.txt

**Comment by shiv07tiwari** [comment]
Again, this issue is also not visible in my Vivo device (android 6.0), but is easily observed in another device. @Swati4star

**Comment by Swati4star** [comment]
must be the issue of internal & external storage issue.

**Comment by eddygta17** [comment]
![screenshot_2018-07-21-11-59-44](https://user-images.githubusercontent.com/24777071/43032863-c67592fa-8cdd-11e8-91e5-1f47d574397f.png)


This is from my external storage with filename duck.txt , I am using the latest build of the app.
