### ISSUE TITLE
Allow PDFs to be send via Whatsapp

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#25]
Modify the current option 'E-mail file' to share the file, and allow it to be shared via WhatsApp, Gmail and other document sharing apps.

**Comment by AshanthaLahiru** [comment]
Working on this.!

**Comment by IamMukulTaneja** [comment]
Hey, please Look into pull request #31 regarding this issue.
Thanks.

**Comment by Swati4star** [comment]
Fixed by be7a4ccceed681aa111a9f3a74144dfe8f914665.
Thanks @IamMukulTaneja 👍
