### ISSUE TITLE
Create PPT to PDF feature

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#250]
### What to do?
- Create a new section in the navigation drawer `PPT to PDF`
- Create similar UI as text to PDF
- The user should be able to select ppt & pptx files on clicking `Select Files` option
- `Create PDF` should be disabled when no file is selected
- On selecting, `Creat PDF`, a dialog should open up for filename
- If the filename does not exist already, create the PDF with the mentioned name
- Show the animation by the time PDF is getting created (similar to images to pdf option)
- After PDF is created, show a snackbar `Your PDF is read`, with an action `Open file`. On clicking that, the PDF should open up.

### Reference:
https://github.com/yeokm1/docs-to-pdf-converter/blob/master/docs-to-pdf-converter/src/com/yeokhengmeng/docstopdfconverter/PptxToPDFConverter.java

**Comment by shiv07tiwari** [comment]
I am working on this  @Swati4star

**Comment by Swati4star** [comment]
Sure @shiv07tiwari

**Comment by santoshhiremani** [comment]
Still open ?

**Comment by Swati4star** [comment]
Yes. It's open

**Comment by santoshhiremani** [comment]
Can i check this

**Comment by Swati4star** [comment]
Sure.

**Comment by santoshhiremani** [comment]
Will to keep only password, set page size, preview,  border and greyscale i. e related to PDF, I don't think image properties are required here to process images out of PPT.

**Comment by Swati4star** [comment]
Yeah. Keep only the relevant properties

**Comment by Swati4star** [comment]
@santoshhiremani Any updates here?

**Comment by santoshhiremani** [comment]
Its in progress....will update with PR.

**Comment by santoshhiremani** [comment]
I'll be using compile `com.droidninja:filepicker:2.1.5` for file picker since 

> Matisse

 doesn't support other than images.

**Comment by Swati4star** [comment]
Also, you can show a list of all the ppts on user's device in the bottom sheet (that's what we are doing for the PDFs on user's system)

**Comment by santoshhiremani** [comment]
![](https://user-images.githubusercontent.com/644341/46664364-6b68ab00-cbde-11e8-85be-432077fb4451.png)

**Comment by Swati4star** [comment]
@santoshhiremani This looks good! You can send a PR.

**Comment by santoshhiremani** [comment]
@Swati4star, Have some issue in pdf creation since POI library doesn't support android and i did not get other alternative in android for PPT to PDF....

**Comment by Swati4star** [comment]
Is there any other alternative?

**Comment by santoshhiremani** [comment]
Creating custom jars out of apache POI, lets see..

**Comment by vyankatesh24** [comment]
@santoshhiremani Are you still working on it?

**Comment by santoshhiremani** [comment]
@vyankatesh24 Currently i'm not working on this

**Comment by jddeep** [comment]
@Swati4star @vyankatesh24 I would like to work on this,

**Comment by vyankatesh24** [comment]
Sure, Go ahead :+1:

**Comment by imran613** [comment]
i am working on it using android x

**Comment by imran613** [comment]
have some issues on android x hope it will resolve soon.

**Comment by Swati4star** [comment]
Removing this feature as I can't find any open source library for this which doesnt have watermark.
