### ISSUE TITLE
[Bug] Default font size is not getting changed in the UI

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#256]
### Steps to reproduce
- Go to `Text to PDF`
- Select `Font Size`
- Set font size to, let's say, 13
- check `Set as default` option
- again, select `Font Size`
- Observe  the text on the dialog

### Expected behaviour
should show **(Default: 13)**

### Actual behaviour
It shows **(Default: 11)**
[the previous default font size]

**Comment by eddygta17** [comment]
Can I take this?

**Comment by Swati4star** [comment]
Sure @eddygta17 👍

**Comment by eddygta17** [comment]
![screenshot_2018-07-21-11-11-11](https://user-images.githubusercontent.com/24777071/43032588-512861c6-8cd8-11e8-90de-131c34ca172e.png)

**Comment by Swati4star** [comment]
looks good @eddygta17
