### ISSUE TITLE
[Preview Images] Allow users to arrange images alphabetically

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#257]
- Add a new option in `Preview images` screen named `Sort Images`
- Open a new dialog on clicking this.
- This option should allow users to sort images
     - alphabetically increasing
     - alphabetically decreasing
     - date created (increasing)
     - date created (decreasing)
- On clicking, any of the above option, the images array should get updated accordingly & preview screen should also get updated.

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Sure
