### ISSUE TITLE
Searching In view files changes button position

### ISSUE THREAD

**Issue by eddygta17** [Swati4star/Images-to-PDF#259]
Searching In view files when there are no files changes button position and it aligns with the keyboard.

**Comment by eddygta17** [comment]
![screenshot_2018-07-21-10-00-34](https://user-images.githubusercontent.com/24777071/43032122-f1a6f826-8ccc-11e8-95b3-bc849410cd96.png)

**Comment by eddygta17** [comment]
Can I work on this?

**Comment by Swati4star** [comment]
Sure @eddygta17 👍

**Comment by eddygta17** [comment]
![screenshot_2018-07-23-22-02-37](https://user-images.githubusercontent.com/24777071/43090193-55159f22-8ec4-11e8-80d0-119651ba38e8.png)

**Comment by Swati4star** [comment]
Looks good @eddygta17 👍

**Comment by eddygta17** [comment]
Shall I send a pull ?

**Comment by Swati4star** [comment]
Yeah sure
