### ISSUE TITLE
View Files UI fault.

### ISSUE THREAD

**Issue by shiv07tiwari** [Swati4star/Images-to-PDF#260]
When no pdfs are present, the view files should show a different layout, but it is still showing the ui same as when w ehave some pdfs in our list. @Swati4star 
![screenshot_20180721_102500](https://user-images.githubusercontent.com/38163725/43032250-1c964138-8cd0-11e8-9b01-e975b5b2a539.jpg)

**Comment by Swati4star** [comment]
In which case is it happening? I am not able to reproduce this issue.

**Comment by shiv07tiwari** [comment]
Whenever we are going to that fragment with no pdfs.
Delete all the PDFs in your list 
Then go to some other fragment and then return to view files fragment.

**Comment by Swati4star** [comment]
I did the following steps & not able to reproduce this error. Let me know if I am doing something wrong,
- Go to view files fragment. Delete all the files
- Go to some other fragment from navigation drawer.
- Come back to view files again

**Comment by shiv07tiwari** [comment]
I just checked on my another device (Redmi note 5 pro Oreo), and I am not able to see the error, but I am easily able to reproduce the error in my Vivo device (android 6.0)

**Comment by shiv07tiwari** [comment]
I am working on this @Swati4star
