### ISSUE TITLE
Few changes in preview screen

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#262]
### How to open preview screen?
- Select few images
- Select `Preview images` option

### What to do?
- In the preview screen, right now, the whole view gets swiped 
- Make following changes
    - Keep only imageview in the viewpager only
    - The bottom 2 text line (`showing x of x` & `swipe right to view more images`) should not get swiped. Make them a part of viewpager view
    - The bottom text should get updated when image is swiped

**Comment by eddygta17** [comment]
Can you post a screenshot?

**Comment by Swati4star** [comment]
See the below screenshot. I selected 2 images:
![screenshot_20180723-222921](https://user-images.githubusercontent.com/9164477/43091554-fa46b64a-8ec7-11e8-9fc4-4278a948fca3.jpg)


When I swipe the screen, the whole screen gets swiped. I just want the image to get swiped.
