### ISSUE TITLE
Create GIF to PDF feature

### ISSUE THREAD

**Issue by milisharma27** [Swati4star/Images-to-PDF#273]
Along with images of JPG format, there can be an option to include GIF format images for conversion to PDF. @Swati4star

**Comment by Swati4star** [comment]
This feature already exists. I downloaded a gif & I was able to convert it into a PDF.

**Comment by milisharma27** [comment]
But this feature is not working. It accesses only some images from gallery. It is not able to access GIF type of image.

**Comment by kvsjxd** [comment]
Are you referring to animated gifs?

**Comment by milisharma27** [comment]
Yes, animated as well as inanimate.
