### ISSUE TITLE
[Merge PDF] Full file path is not coming up on the buttons

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#285]
Observe this gif:
![my](https://user-images.githubusercontent.com/9164477/43274923-1ccae0a8-911e-11e8-96df-cf69e12f4b9f.gif)

### Expected behaviour
The full path (along with filename) should be there on the buttons

**Comment by eddygta17** [comment]
![screenshot_2018-07-27-06-24-09](https://user-images.githubusercontent.com/24777071/43295906-bbd707d4-9165-11e8-9ea6-ce028a5a3225.png)

Does having just the filename improve the experience?

**Comment by Swati4star** [comment]
I think, we should have the full path. (Path + name)

**Comment by eddygta17** [comment]
How about just changing the text size if filename exceeds character length?

![screenshot_2018-07-28-04-27-28](https://user-images.githubusercontent.com/24777071/43349623-c2748de6-921e-11e8-8bb5-432c49593028.png)

**Comment by eddygta17** [comment]
Yes
![screenshot_2018-07-28-07-57-36](https://user-images.githubusercontent.com/24777071/43352115-38652e44-923c-11e8-8e20-426ff2356270.png)

**Comment by Swati4star** [comment]
Okay then. Create a PR.

**Comment by eddygta17** [comment]
![whatsapp image 2018-07-28 at 8 03 34 am](https://user-images.githubusercontent.com/24777071/43352155-e43372ee-923c-11e8-8308-62c2a6914541.jpeg)


#282 still exits

**Comment by Swati4star** [comment]
Let's focus on one issue only first.

**Comment by Swati4star** [comment]
This PR is just changing the text size. The problem was that the whole file path was not coming. 

I'll check it locally. I don't think this will solve the issue.,

**Comment by vyankatesh24** [comment]
@Swati4star 
This issue is not valid now, as we have removed those buttons.

**Comment by Swati4star** [comment]
Oh yes! Thanks for noticing!
