### ISSUE TITLE
Change in UI of preview screen options

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#290]
Currently, the options screen look like this:
<img width="323" alt="screen shot 2018-07-28 at 9 45 14 am" src="https://user-images.githubusercontent.com/9164477/43353000-ff2140e6-924a-11e8-840a-880e4bdfb8a7.png">

### Expected behaviour
- Add a heading to this view `Image Rearranging options`
- Change the view to circular. Something like this: (Instead of blue, it should be our app's primary color)
<img width="106" alt="screen shot 2018-07-28 at 9 47 05 am" src="https://user-images.githubusercontent.com/9164477/43353017-399a89f8-924b-11e8-8436-5d1d1b2718cd.png">
- Below this circular image, type the name of the option. In this case, `Rearrange`

**Comment by vyankatesh24** [comment]
Shall I work on it?

**Comment by Swati4star** [comment]
Yeah sure!,

**Comment by Swati4star** [comment]
Looks good. Create a PR.

**Comment by vyankatesh24** [comment]
![image](https://user-images.githubusercontent.com/18503975/43354820-7099d592-9270-11e8-9ba4-610fdc8e5930.png)

**Comment by Swati4star** [comment]
@vyankatesh24 IT's great
