### ISSUE TITLE
UI changes in image rearrange screen

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#294]
### Steps : 
- Select few images. Select `Preview PDF`
- select rearrange option. 
- Following view comes up:
<img width="327" alt="screen shot 2018-07-28 at 2 14 55 pm" src="https://user-images.githubusercontent.com/9164477/43354837-c628bb7c-9270-11e8-851b-318ef74cc17c.png">

### Expected behavior:
- Add the page number at the top right corner of each page
- Change the icons view to something similar to this (circular background with icon):
<img width="184" alt="screen shot 2018-07-28 at 2 17 11 pm" src="https://user-images.githubusercontent.com/9164477/43354855-f3be4430-9270-11e8-886f-9e9f1a461f97.png">

**Comment by vyankatesh24** [comment]
Shall I work on it?

**Comment by Swati4star** [comment]
Sure.

**Comment by vyankatesh24** [comment]
![image](https://user-images.githubusercontent.com/18503975/43358779-cab5a594-92b4-11e8-94a7-6880f9446eef.png)

**Comment by Swati4star** [comment]
The icons look good. Just change the color of page number on greyish button to white.

**Comment by vyankatesh24** [comment]
![image](https://user-images.githubusercontent.com/18503975/43358865-4316e52e-92b6-11e8-924f-d975bab8c50d.png)

**Comment by Swati4star** [comment]
Yes. This looks good. Just one more thing. Decrease the right margin on the page number icon. Align with the arrow icons...and then, you can create a PR.

**Comment by vyankatesh24** [comment]
Ok
