### ISSUE TITLE
Lot of work in main thread

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#3]
The app is doing a lot of work in main thread.
Needs to be moved to Async task.

**Comment by ShivamArora** [comment]
I see this might have been already handled as the pdf is being created within an AsyncTask called creatingPdf which is executed in the createPdf() method.

Is there anything else to be done?

**Comment by Swati4star** [comment]
You can move this tasks to Async Tasks.
[View Files](https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/java/swati4star/createpdf/ViewFiles.java#L62)

**Comment by mihudevcom** [comment]
@Swati4star You need a loading dialog as well? Or just moving those to an AsyncTask will be enough? And why do you need an AsyncTask for this? I don't think it's loading that slow but maybe I'm missing something?

**Comment by Swati4star** [comment]
Just adding the tasks to AsyncTasks would be enough. Also, adding a dialog would be an enhancement.

The addition of this is just for worst case scenarios. It might take a significant amount of time in slower phones or if there is some exception. This is just for those cases.

**Comment by mihudevcom** [comment]
@Swati4star Okay, sounds logical. Can I take care of this?

**Comment by Swati4star** [comment]
@mihudevcom Sure. Go ahead with this. If there is some issue, let me know. :+1:

**Comment by mihudevcom** [comment]
@Swati4star Any other issues for this case?

**Comment by Kartik2016** [comment]
I am new t open source. Can i go ahead with the issue?

**Comment by khokharnikunj8** [comment]
I think its time for closing this issue . .. @Swati4star  @mihudevcom

**Comment by mihudevcom** [comment]
@khokharnikunj8 Let's wait for @Swati4star and see what she says.

**Comment by Swati4star** [comment]
@khokharnikunj8 @mihudevcom Yes, I think I should close this issue.
