### ISSUE TITLE
Add `Set Page size` option in text to PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#302]
We have `Set Page size` option in images to PDF. 
<img width="297" alt="screen shot 2018-07-28 at 10 10 46 pm" src="https://user-images.githubusercontent.com/9164477/43358682-1ce8b786-92b3-11e8-8606-beefde4a3326.png">

### Expected behaviour
- Add same option in `Text to PDF` screen
- Don't just copy paste the code from ImagesToPDFrgament. Create a new utlity file (or add a new function in existing utils file) & use that code at both the place (imagestopdf & texttopdf)

**Comment by vyankatesh24** [comment]
I would like to work on it.

**Comment by Swati4star** [comment]
Sure @vyankatesh24
