### ISSUE TITLE
Edit Images doesn't work after selecting filter images

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#306]
### Steps to reproduce
- Select few images
- Select `Filter images`. 
- Do nothing, press back
- Selec `Edit images`

### Actual behaviour
Nothing happens

### Expected behaviour
Edit images screen should open up

**Comment by vyankatesh24** [comment]
I would like to work on it.

**Comment by Swati4star** [comment]
Sure. :+1:
