### ISSUE TITLE
Use consistent date format

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#309]
Date format is different in `View Files` and `history` section
<img width="350" alt="screen shot 2018-07-29 at 5 11 50 pm" src="https://user-images.githubusercontent.com/9164477/43365958-8490da9a-9352-11e8-987a-2bf12d241992.png">
<img width="349" alt="screen shot 2018-07-29 at 5 11 56 pm" src="https://user-images.githubusercontent.com/9164477/43365959-84b8ac5a-9352-11e8-8733-146e2b2621b1.png">

### Expected behaviour
Change the date format in history section to that in the view files

**Comment by shiv07tiwari** [comment]
Working on this @Swati4star

**Comment by Swati4star** [comment]
Okay!
