### ISSUE TITLE
Back button on any navigation bar activity closes the app

### ISSUE THREAD

**Issue by vishalkalra9** [Swati4star/Images-to-PDF#321]
The back button on any side navigation bar closes the activity and user has to open the app again to access again

**Comment by Swati4star** [comment]
Which activity are you taking about? 

We don't have back button on navigation drawer in MainActivity. For other activities, it is supposed to finish that.

**Comment by vishalkalra9** [comment]
I was actually mentioning the screens which are opened from navigation drawer. For eg if I open "About us" screen and press back to go to previous screen shouldn't I be taken back to home/Default page in case current one isn't as that's generic user behaviour?

**Comment by Swati4star** [comment]
This issue is same as https://github.com/Swati4star/Images-to-PDF/issues/268
It has been fixed.

**Comment by vishalkalra9** [comment]
Okay. I couldn't find the same in the latest build from your master that's why. Anyhow, closing it.

**Comment by Swati4star** [comment]
Sorry, This issue is actually not resolved. I checked in the app.

**Comment by vishalkalra9** [comment]
Yeah. I'll work on this. Also, shouldn't we prompt the user to press back twice to close the app?

**Comment by Swati4star** [comment]
The issue is still not solved. The behaviour is very weird now.
The fragments are getting stacked on top of each other & we need to press back so many times

**Comment by Swati4star** [comment]
Fixed by beed200bd4bb09ede59cdef2a33b9e4ad2c9aebe

**Comment by vishalkalra9** [comment]
How exactly is it reproducible? I checked again it's fine. Following is the use case I followed:

1. Opened app -> Selected View files from drawer -> pressed back -> pressed back twice on home -> Closes app

2. Opened app -> Selected View files -> Selected History -> pressed back -> pressed back twice on home -> Closes app

**Comment by Swati4star** [comment]
@vishalkalra9 Actually, the fragments were getting stacked on the top of each other & the view was turning out to be weird.

I don't any screenshots right now to post.
