### ISSUE TITLE
Don't show the `View Files` option in Merge PDF, when there are no files

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#330]
Hide the view files option in Merge PDF, when there are no files to show

<img width="329" alt="screen shot 2018-08-03 at 7 02 28 pm" src="https://user-images.githubusercontent.com/9164477/43645557-eb715996-974f-11e8-80e8-7287bd9ee9dd.png">

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Sure
