### ISSUE TITLE
An empty PDF is created in `Text to PDF` when we don't have any file selected

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#331]
### Steps to reproduce
- Go to `Text to PDF`
- Select `Create PDF`
- A PDF with size 0 is created

### Expected behaviour
The `Create PDF` should be disabled (and greyish in color) when we don't have any text file selecte

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Go ahead.
 I am traveling & I don't have access to my laptop, that's why there is a delay in merging your current PR, but you can go ahead with this one!

**Comment by vyankatesh24** [comment]
Do I have to disable the 'More Enhancement Option' also or Just `Create PDF` button?

**Comment by Swati4star** [comment]
Just `Create PDF`

(Similar to `images to PDF` fragment)

**Comment by vyankatesh24** [comment]
Ok.
