### ISSUE TITLE
Don't change the background color of `Disable doodle effect` button, when it is selected

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#334]
the UI looks like this:
Not selected
<img width="336" alt="screen shot 2018-08-03 at 7 18 36 pm" src="https://user-images.githubusercontent.com/9164477/43646260-109d5024-9752-11e8-82db-af04cabf350e.png">

Selected
<img width="324" alt="screen shot 2018-08-03 at 7 18 40 pm" src="https://user-images.githubusercontent.com/9164477/43646280-1aac10dc-9752-11e8-9536-f3ef3e60fd08.png">

**Comment by shiv07tiwari** [comment]
working on this @Swati4star
