### ISSUE TITLE
Bug in File History when File is renamed

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#343]
### Steps
- Create a file name `abc.pdf`
- Rename it to `xyz.pdf` 
- The history looks like this :
![unnamed](https://user-images.githubusercontent.com/9164477/43686685-96acc1ae-98e7-11e8-9120-6e04d3047652.jpg)

- When we click on the file, it says, `Pdf doesn't exist.`

### Expected behavior:
On renaming the file, update the file URI also in the database. It should point to the new file after renaming.

**Comment by vyankatesh24** [comment]
If we change the `Uri` to new, it will show the new file name on a screen.
Because we are extracting a name from the `Uri`
Will that be Ok?

**Comment by Swati4star** [comment]
Yes. The new file name should be displayed

**Comment by vyankatesh24** [comment]
OK, Shall I work on it?

**Comment by Swati4star** [comment]
Sure. Go ahead @vyankatesh24
