### ISSUE TITLE
Bug in filter screen

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#344]
Bug in filter screen

### Steps
- Select few images
- Select `Filter images`
- apply some filter to the image
- (Don't click on `Save current`)
- select check icon on the top bar

### Expected behavior
The filter should be applied on the image.

### Actual Behavior
Filter is not applied

### What to do?
When user clicks on check icon (with few unsaved changes), show a snackbar saying `The filter on current image is not saved. Do you want to continue without saving?` if user clicks ok, let the behavior be as is, but if user clicks cancel, dismiss the dialog.

**Comment by vyankatesh24** [comment]
@Swati4star 
Please check once, after merging #362 this bug situation is not occurring.

**Comment by Swati4star** [comment]
I'll check it in a while.

You can work on some other issue by the time.

**Comment by vyankatesh24** [comment]
Yeah Sure.

**Comment by Swati4star** [comment]
@vyankatesh24 The issue is still here.

**Comment by Swati4star** [comment]
Sure @vyankatesh24
