### ISSUE TITLE
Disable the scroll on image when Doodle effect is selected

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#346]
### Steps
- Select images
- Select `Filter images`
- Select `Enable Doodle Effect`

### Issue
The doodle effect does not get applied properly when trying to create a vertical line (the image scrolls)

### Expected behaviour
Disable the scroll on image, when doodle effect is selected

**Comment by Arbalest007** [comment]
I would like to work on this!

**Comment by Swati4star** [comment]
Sure @Arbalest007 👍

**Comment by Swati4star** [comment]
@Arbalest007 Doodle effect is brush effect only.

**Comment by vyankatesh24** [comment]
@Swati4star is anyone working on it?

**Comment by vyankatesh24** [comment]
@Arbalest007  Are you still working on it?

**Comment by Swati4star** [comment]
@vyankatesh24 We are dependent on library for fixing this issue. Check https://github.com/Swati4star/Images-to-PDF/pull/477
