### ISSUE TITLE
Files are getting Overwritten while renaming the file

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#350]
Files are getting Overwritten while renaming the file from `View files` Fragment

**Comment by Swati4star** [comment]
What do you mean by overwritten?

**Comment by vyankatesh24** [comment]
Another file having the same name as the Entered new name, gets overwritten.

**Comment by Swati4star** [comment]
oh 👍

**Comment by Swati4star** [comment]
@vyankatesh24 Are you working on this one?
