### ISSUE TITLE
Reset the values on Merge PDF, when PDF is created

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#351]
### Steps
- Go to `Merge PDF`
- Select first & second PDF
- Select `Merge Files`. 
- PDF is created

### Actual behaviour
UI looks like this:
<img width="333" alt="screen shot 2018-08-05 at 8 18 58 pm" src="https://user-images.githubusercontent.com/9164477/43687098-4ee8c254-98ed-11e8-87df-807c3e09306d.png">

### Expected behaviour
- The values on buttons should reset (and grey colored)
- `Merge Files` should be disabled

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Sure
