### ISSUE TITLE
Values should reset when PDF is created in `Text to PDF`

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#352]
### Steps
- Select `Text to PDF`
- Create PDF

### Actual behaviour
When we click `Create PDF` second time, another PDF is created

### Expected behaviour
The `Create PDF` should be disabled
There should not be any txt file selcted

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Go ahead :+1:
