### ISSUE TITLE
Set Page Size value is not retained

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#353]
### Steps
- Go to `Images to PDF` or `Text to PDF` section
- Select `Set Page Size`
- Set it to anything, other than Default value (Let's say: Legal) 
- Select `Set Page Size` again. 

### Expected behaviour
`Legal` should be selected in Page size dialog

### Actual behaviour
`Default` option is selected always

 
Fix it for `Images to PDF` as well as `Text to PDF` section

**Comment by vyankatesh24** [comment]
@Swati4star 
Working on this.

**Comment by Swati4star** [comment]
Sure!
