### ISSUE TITLE
Add Password Protection option in Text to PDF also

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#354]
Similar to the Password Protection option we have in `Images to PDF` section, add it to `Text to PDF` also.

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Sure @vyankatesh24 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/363
