### ISSUE TITLE
Use `Bottom Sheet` for `View Files` in `Merge PDF`

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#356]
### Steps
- Go to `Merge Files` from the navigation drawer. There is a `View Files` option at the bottom
- Right now, when we click on `View Files`, a view opens up & hides, when we select it

### Expected behaviour
- Use `Persistent Bottom Sheet` for `View Files`. For example:
<img width="751" alt="screen shot 2018-08-06 at 11 21 09 pm" src="https://user-images.githubusercontent.com/9164477/43732472-71134d12-99cf-11e8-90fa-ed637d5a4137.png">

- In non exapnded state, `View Files` text should be visible
- In expanded state, show the list of the files

### Reference:
https://www.androidhive.info/2017/12/android-working-with-bottom-sheet/

**Comment by vyankatesh24** [comment]
I would like to try it.

**Comment by Swati4star** [comment]
Sure @vyankatesh24 
Let me know if you face any problem

**Comment by vyankatesh24** [comment]
Yeah Sure!
