### ISSUE TITLE
Random file selection behaviour in view files

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#365]
### Steps:
- Go to `View Files`
- Select few files (by selecting checkbox) [let's say first top 2]
<img width="314" alt="screen shot 2018-08-09 at 9 00 00 pm" src="https://user-images.githubusercontent.com/9164477/43909107-3473c4b4-9c17-11e8-9966-d4f23cf43f65.png">

- Now, click on some other file (not on checkbox, on the filename)
- A dialog opens up. Don't select any option. PRess back. Dialog closes
- Some random files also get selected : 
<img width="328" alt="screen shot 2018-08-09 at 9 00 26 pm" src="https://user-images.githubusercontent.com/9164477/43909137-4389cb42-9c17-11e8-803f-92a574a79f1f.png">

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Sure @vyankatesh24
