### ISSUE TITLE
[Merge PDF - View Files] Show lock icon if PDF is encrypted

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#372]
### What to do?
Show a lock icon to the encrypted files in this view:
<img width="318" alt="screen shot 2018-08-11 at 9 24 53 pm" src="https://user-images.githubusercontent.com/9164477/43993566-0d57a728-9dad-11e8-85e5-e458fac70f60.png">

Similar behaviour is already there in view files
<img width="336" alt="screen shot 2018-08-11 at 9 25 40 pm" src="https://user-images.githubusercontent.com/9164477/43993574-2024d10a-9dad-11e8-8481-b46673aae789.png">

**Comment by vyankatesh24** [comment]
Would like to work on it

**Comment by Swati4star** [comment]
Sure @vyankatesh24
