### ISSUE TITLE
[Filter images UI] Alert is shown even if we don't apply any filter

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#374]
### Steps
- Select few images
- Go to `Filter images`
- Don't do anything. Select ◀️ (back arrow icon on top left of action bar)

### Actual behaviour
This alert is shown
<img width="285" alt="screen shot 2018-08-11 at 9 33 28 pm" src="https://user-images.githubusercontent.com/9164477/43993638-3791f416-9dae-11e8-9854-a9c1d2c4ed24.png">

### Expected behaviour
Don't show the alert if no changes are made to any image

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Sure! @vyankatesh24
