### ISSUE TITLE
[Compress PDF] Add an option to compress PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#379]
### What to do?
- Add a new option in navigation drawer : `Compress PDF`
- This fragment should have : 
  - a button to `select PDF`, and a button to `Compress PDF`
  - a `View Files` bottom sheet (similar to merge Files)
  - when PDF is selected, open up a dialog to enter compression level . (between 0 to 100)
  - when ok is pressed, create a pdf with name `<filename>_compressed<level>.pdf`

### References
http://what-when-how.com/itext-5/pdf-and-compression-itext-5/

**Comment by shiv07tiwari** [comment]
Working on this @Swati4star

**Comment by Swati4star** [comment]
Sure @shiv07tiwari

**Comment by Swati4star** [comment]
@shiv07tiwari Updates?

**Comment by Swati4star** [comment]
Add this option in `View Files` only. Not as separate option in navigation drawer
