### ISSUE TITLE
Add an option to remove image in rearrange screen

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#380]
### Steps
- Select few images. Go to `Preview PDF`
- Go to `rearrange`

### What to do? 
- Add a new icon on this screen. Add a cross icon at the top right corner of each image.
<img width="329" alt="screen shot 2018-08-12 at 3 42 33 pm" src="https://user-images.githubusercontent.com/9164477/44000936-605bdb58-9e46-11e8-9002-9938e8dcdb3c.png">

- When this icon is clicked, show an alert `Are you sure you want to remove this image?`.
- This alert should also have `Don't show again` checkbox. If this checkbox is set, don't show alert next time

**Comment by vyankatesh24** [comment]
Shall I work on it?

**Comment by Swati4star** [comment]
Yes @vyankatesh24

**Comment by Swati4star** [comment]
Looks good!!
