### ISSUE TITLE
[New Feature] Allow users to rotate pages of an existing PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#400]
- `Rotate Pages` :  Add a new option in the dialog in `View Files` (The dialog opens up when we select a PDF)
- On selecting this option, open up a dialog asking user the angle by which they want to rotate their pages.
- On selecting `ok`, save the PDF with name `<pdf_name>_rotated<angle>.pdf`

### Reference:
https://developers.itextpdf.com/question/how-rotate-page-90-degrees

**Comment by vyankatesh24** [comment]
Would like to work on it

**Comment by Swati4star** [comment]
@vyankatesh24 Go ahead! 👍
