### ISSUE TITLE
[Merge PDF] Allow users to merge multiple files

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#404]
- Remove the select first PDF & select second PDF option from `Merge Files`
- Move Merge Files button to top
- Add a `Select PDF` button below it
- After the file is selected, add it to the list (below the Merge Files button)

- In the bottom sheet also, remove the dialog & just keep adding PDF to the list (when user clicks it), and just show a snackbar `PDF has been added to the list`

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Sure.
