### ISSUE TITLE
Camera switching impossible while clicking images from the app

### ISSUE THREAD

**Issue by kvsjxd** [Swati4star/Images-to-PDF#409]
Camera switching is impossible while clicking images from the app itself. Add an option to switch from primary camera to secondary camera from the app.

Reason for supporting this functionality is that some OEMs mess up configuration (in rare cases) of their devices while building android image and does not even fix it later with updates. Another reason is that, some tablets only have front camera and no back camera and OEMs set those tablets camera as secondary camera which means those tablets won't be able to click images with this app.

**Comment by Swati4star** [comment]
The library we have doesn't provide support for this. So, this issue can only be solved after https://github.com/Swati4star/Images-to-PDF/issues/146 is done.

**Comment by Swati4star** [comment]
We have started using device camera only, while selecting images (after integration of new Matisse library)
