### ISSUE TITLE
[New feature] Add images to existing PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#413]
### What to do?
- Add a new option in the navigation drawer `Add Images`
- Make this fragment similar to reorder pages . (with button to select file, bottom sheet, and create PDF button)
- In addition to that, add a button to allow users to select images (similar to home page). Also add a text view, `The images you select will be added to the end of selected PDF.`

- when user selects `create PDF`, prompt user to enter file name
 show the animation dialog, (add the selected images to the end of existing PDF)

**Comment by Giuseppe250** [comment]
Can I take this task? Is it still free?

**Comment by marika9** [comment]
Hi, can I take this task?

**Comment by Swati4star** [comment]
Sure @marika9 👍
