### ISSUE TITLE
Image editing options : filters

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#42]
Allow user to apply effects/filters to images.

**Comment by Pritom14** [comment]
I would like to work on this. May I know what type of effects/filters are needed

**Comment by Swati4star** [comment]
I think we can start with the basic ones like black & white and sepia.

**Comment by Pritom14** [comment]
Could you please guide me as to how to proceed in this issue. I was
thinking of putting the option for the filters when the user clicks on a
certain file(PDF), along with the options : `Open File` , `Delete File` ,
`Rename File` , `Print File` , `Share File` . When the user clicks on
`Apply Filter` three options will be there black, white and sepia.
Is it ok if I proceed in this way?

**Comment by Swati4star** [comment]
Yeah sure. Just comment here in case of any doubts.

The problem for your case will be, you are editing the images in PDF after it is created. I want to apply filters before creating PDF.

So, my suggestion for doing this is by,
after user has selected few images, show an option on home screen only 'Apply Filters'. Upon clicking on this option, user should be able to apply the filter to the images, and preview it & select whichever he likes. And, the created PDF should contain this.

**Comment by Sabihashaik** [comment]
@Swati4star Hi! I'd like to give this feature a try. :)
I was thinking of using a library for the filters, [Zomato Android Photo Filters.](https://github.com/Zomato/AndroidPhotoFilters)

**Comment by Swati4star** [comment]
@Sabihashaik 
The library looks good! You can start with this one 👍

**Comment by Sabihashaik** [comment]
@Swati4star I might have to use a new activity with a few fragments on it to get the sliding view for the filters like in instagram. Is that okay? Since I noticed as of now there is only 1 activity (The main Activity).

**Comment by Sabihashaik** [comment]
@Swati4star I think you accidentally referenced the wrong issue.  You were supposed to reference #49

**Comment by Swati4star** [comment]
oh yes! @Sabihashaik I'll reword that commit.

**Comment by Swati4star** [comment]
You can this library also : https://github.com/burhanrashid52/PhotoEditor

**Comment by Sabihashaik** [comment]
@Swati4star Yes, I came across this one as well.

**Comment by Sabihashaik** [comment]
@Swati4star The library you mentioned only takes images from resources, file or (Picasso/Glide). So If I'm trying to set the Images which are already selected to have filters, since the library sets the image/drawable to the ImageView and then applies filter to it, I'm not quite sure how to make it accept URIs, could you please clarify a little bit?

So far, I'm able to apply Filters to images. Just taking the images selected in previous activity seems to be slightly a problem.

**Comment by Swati4star** [comment]
@Sabihashaik you can get file path from Uri, and can convert it to bitmap. You can then set it to imageview. After the filter is applied, you may save the new image (with effects) in user's gallery. and use the new Uri.

Am I able to solve the problem or is there any confusion?

**Comment by Sabihashaik** [comment]
@Swati4star  Thank you, I'll give this method a try.

**Comment by Sabihashaik** [comment]
@Swati4star I figured out the error. Sorry for any delay, I'll send a PR quite soon :)

**Comment by Swati4star** [comment]
Awesome!
