### ISSUE TITLE
[Split PDF] Allow random file splitting

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#420]
Currently, the split PDf option splits the selected PDF into PDFs of single page

### What to do?
Allow users to split files randomly also

**Comment by anirudh8860** [comment]
Will try to do it

**Comment by Swati4star** [comment]
Sure @anirudh8860 👍

**Comment by Shivamdhuria** [comment]
I'd be glad to work on this if no one else is.However can you please explain more what "allow users to split files randomly" is? As in splitting into PDF's of more than 1 page?

**Comment by Swati4star** [comment]
Yes @Shivamdhuria 
So, currently on splitting the PDF, all the pages are converted to single page PDFs.
What if user wanted to split the PDF into 2 only. 
So, allow users to select the page range in which they want to split PDF

**Comment by Shivamdhuria** [comment]
Alright I'll start working on it

**Comment by ajax333221** [comment]
> 
> 
> Yes @Shivamdhuria
> So, currently on splitting the PDF, all the pages are converted to single page PDFs.
> What if user wanted to split the PDF into 2 only.
> So, allow users to select the page range in which they want to split PDF

that doesn't include randomness at all mm, I don't know the right word for being able to split it that way, but I'm positive is not _random_.
