### ISSUE TITLE
[New Feature] Allow users to scan QR code

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#427]
### Scan QR code
- This should open up a QR code scanner
- Show the output.
- Allow users to save the QR code information as pdf or text file.

Use this library : 
https://github.com/zxing/zxing

**Comment by santoshhiremani** [comment]
Zxing supports both QR and Barcodes..

**Comment by Swati4star** [comment]
@santoshhiremani We can have the facility for both then.

**Comment by Swati4star** [comment]
Not in `Create PDF`. Add it as a seperate fragment in the navigation drawer. 

In the home page, just add an icon for it in other options.

**Comment by santoshhiremani** [comment]
Is there any implemented method to write string to pdf ? Since i can see its only from text file path.
