### ISSUE TITLE
[Merge PDF enhancement] Show checkboxes on selected files

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#431]
- In merge PDF, users can select multiple files to be merged

### What to do?
- Add checkbox before each filename in the bottom sheet
- On checking that, it should be added for merge.
- On unchecking, remove it.

**Comment by sc450ew** [comment]
Hi
can i do on this issue ?

**Comment by Swati4star** [comment]
Sure @sc450ew 👍

**Comment by Swati4star** [comment]
@sc450ew Any updates?

**Comment by sc450ew** [comment]
@Swati4star  problem with Android studio, still work on it,
next week the issue can be fix, and push 


> @sc450ew Any updates?
