### ISSUE TITLE
Butterknife in master

### ISSUE THREAD

**Issue by Pl4gue** [Swati4star/Images-to-PDF#44]
I have got a question: Why don't use Butterknife in the master branch?

**Comment by Swati4star** [comment]
I remember adding it but was facing some issue.
Feel free to integrate it in the code.

**Comment by Pl4gue** [comment]
Alright, will do that.

**Comment by Pl4gue** [comment]
@Swati4star I will integrate it as soon as you merged my other PR 👍

**Comment by Swati4star** [comment]
Fixed by @Pl4gue
