### ISSUE TITLE
Add Merge PDF option in View Files

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#440]
### What to do?
The user can select multiple multiple files in `View Files` fragment. 
- When more than 1 file is selected, show a new option in the action bar: `Merge PDF` (show it's icon)
- If the user selects that option, show a dialog to allow user to enter file name
- Merge the selected PDFs into a single PDF

**Comment by sandraprog** [comment]
It's not taken yet? When I'd like to take it

**Comment by Swati4star** [comment]
Yes @sandraprog ! You can take up this one 👍
