### ISSUE TITLE
Add `Remove password` and `Add password` option in navigation drawer

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#441]
The option to `add` and `remove` password is already there in view files.
- Add this option in navigation drawer
- The view should be similar to `compress PDF`....with a button to select file, a bottom sheet with file list populated & a button to add/remove password
- On selecting the button, ask user to enter password
- If everything goes fine, create the required PDF

**Comment by Rimjhim28** [comment]
@Swati4star Can I work on this issue?

**Comment by Swati4star** [comment]
@Rimjhim28 Updates?

**Comment by Vanethos** [comment]
HI @Swati4star I picked up this Issue since there was no further updates

I added the two buttons to the drawer and linked them to the current Add and Remove Password screens, is that okay?

**Comment by Swati4star** [comment]
Do you mean to the `View Files` fragment?

**Comment by Vanethos** [comment]
Yes @Swati4star, exactly. 

In the meantime I added the PR https://github.com/Swati4star/Images-to-PDF/pull/498

I can change it to create the layout that you desire later

**Comment by Swati4star** [comment]
Change it to the desired layout...

**Comment by Vanethos** [comment]
I won't be able to solve this today, but I will solve it asap

Sorry for the misunderstanding on my part... 😞

**Comment by Swati4star** [comment]
No problem! You can complete the other PR for now!
