### ISSUE TITLE
please change version name & increase version code for each release

### ISSUE THREAD

**Issue by DJCrashdummy** [Swati4star/Images-to-PDF#442]
according to [this issue](https://gitlab.com/fdroid/fdroiddata/issues/1378) can you please ensure to change the version name and increase the version code for each release, to make automatic updates work at [f-droid](https://f-droid.org/packages/swati4star.createpdf/).

thank you very much!

**Comment by DJCrashdummy** [comment]
> the application is not set to autoupdate on f-droid.

as you can [see here](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/swati4star.createpdf.txt#L47), it is now setup for auto-updating (it's just a matter of time until build 2.5 appears).
[but release 2.5.1 won't be detected](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/swati4star.createpdf.txt#L49) because - according to the linked issue - the release was tagged before bumping version code.

if you are interested in more background for auto updating at fdroid you can have a look at [this doc starting at "Update Check Mode"](https://f-droid.org/en/docs/Build_Metadata_Reference/#Update-Check-Mode). if something does not work as intended, please open an issue at the [data repo of fdroid](https://gitlab.com/fdroid/fdroiddata), the people at fdroid are helping willingly.

**Comment by Swati4star** [comment]
I have created a new release now. Is this fine?
I hope the latest version would be available on fdroid soon.

**Comment by Swati4star** [comment]
https://github.com/Swati4star/Images-to-PDF/releases

**Comment by Swati4star** [comment]
It's still version 1.0 available here : https://fossdroid.com/a/pdf-creator-2.html

**Comment by DJCrashdummy** [comment]
@Swati4star yes, as added afterwards to the 1st paragraph of my last comment: it can take some time ~1-3 days until a new release is recognized, build and published... probably even a little longer until it gets to fossdroid.

...so lets wait and see if auto-update works and 2.5 & 8.0.0 appear. :wink:

**Comment by DJCrashdummy** [comment]
since 2.5 is in f-droid for more than a week and according to https://gitlab.com/fdroid/fdroiddata/issues/1394 it should just be a mater of time until 8.0.0 and 8.3.3 is also online... so i guess this issue can be closed?

**Comment by Swati4star** [comment]
Sure! 👍
