### ISSUE TITLE
Allow users to add margins while creating PDF from images

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#443]
- Add a new option in Images to PDF : `Add custom margin`
- On clicking this, a new dialog should open up, which allows user to enter 4 values : top, bottom, right, left margin

### Reference
https://developers.itextpdf.com/examples/itext5-building-blocks/page-size

**Comment by yuval105** [comment]
I'll give it a try.

**Comment by Swati4star** [comment]
Sure @yuval105 👍
