### ISSUE TITLE
[New feature] Extract text from PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#445]
### What to do?
- Add a new option in the navigation drawer: `Extract text`. Add this to home page also.
- Allow user to select a PDF (using a button, as well as, bottom sheet)
- Add another button : `Extract text from PDF`
- On clicking above button, ask user to enter file name. Create txt file from text in the PDF

### Reference
https://stackoverflow.com/a/11317420/3623128

**Comment by getsanjeev** [comment]
@Swati4star May I work on this?

**Comment by Swati4star** [comment]
Sure @PseudoAj 👍 
You can work on this.

**Comment by Swati4star** [comment]
@PseudoAj Updates?

**Comment by Swati4star** [comment]
I have mentioned a link in the issue description. We already are using itext for a number of other features also, we can itext only for text extraction also.

**Comment by PseudoAj** [comment]
Would be interesting to see accuracy vs performance between them. But I will go with your recommendation for now @Swati4star.

**Comment by PseudoAj** [comment]
Made some progress over the weekend added UI components and basic functionality. Fixing some bugs with the file selection. Will send the PR shortly @Swati4star.

**Comment by Swati4star** [comment]
Awesome @PseudoAj 💯

**Comment by Swati4star** [comment]
@PseudoAj are you working on this?

**Comment by PseudoAj** [comment]
Hey @Swati4star,

Apologies for the delay. I am yet to fix the issue with file selection. I will try to make some progress over the next few days.

**Comment by Swati4star** [comment]
You can create a work-in-progress PR. I'll help with the file selection issue.

**Comment by PseudoAj** [comment]
Sounds good. Will post WIP PR.

**Comment by Swati4star** [comment]
@PseudoAj are you working on this?

**Comment by PseudoAj** [comment]
Still interested to finish it up @Swati4star.

**Comment by Swati4star** [comment]
If you are really interested, create a partial PR 
(atleast!)

**Comment by vyankatesh24** [comment]
@PseudoAj Any updates?

**Comment by PseudoAj** [comment]
@vyankatesh24 @Swati4star Couldn't spend time to rebase and make any progress. Apologies for hogging this task for so long. If someone is interested feel free to re-assign.

**Comment by jddeep** [comment]
@Swati4star @vyankatesh24 I would like to work on this.

**Comment by Swati4star** [comment]
Sure @jddeep 👍

**Comment by jddeep** [comment]
@Swati4star Please give a difficulty tag
