### ISSUE TITLE
[PDF enhancement options] Add page number of PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#446]
- Add a new option `Show page number` in `More enhancement option` in `images to PDF`
- On selecting above, show a dialog to Allow users to select from some page number formats like : 
  - Page X of N
  - Page X
  - X

### Reference
https://stackoverflow.com/questions/5717981/show-page-numbers-in-pdf-using-itext

**Comment by bunhann** [comment]
I'll complete this.

**Comment by Swati4star** [comment]
@bunhann Any updates here?

**Comment by Doubl3MM** [comment]
Hi,

since there is no progress on this issue, can I work on this?

**Comment by Swati4star** [comment]
Fixed by 59271469cb10c5bd0d1144a9d521f742207baea7
