### ISSUE TITLE
Few issues in Bottom sheet

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#452]
- The lock icon is white in color [See the last PDF] : Inreorder/remove/compress/split/merge PDF, there is a bottom sheet. If PDF is password protected, a lock icon is displayed
<img width="337" alt="screenshot 2018-10-04 at 11 17 27 am" src="https://user-images.githubusercontent.com/9164477/46455102-189a8800-c7c7-11e8-96e1-681199407f7e.png">

- Show `fetching files..` message in the bottom sheet while the PDFs are being fetched. Currently, nothing is displayed

**Comment by konstzv** [comment]
question on the first point - do you want to change the color of the icon to make it more visible or no?
Explain this point pls

**Comment by Swati4star** [comment]
I want to make it more visible. [black in color]

**Comment by Swati4star** [comment]
@konstzv Also, take care that we have different themes also. (Go to settings from the navigation drawer)

In white theme, the icon color should be black
but, in dark & black theme, it should be white.
