### ISSUE TITLE
The current fragment is not getting highlighted when we select fragment from home page

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#453]
## Steps to reproduce
- Go to home page. Select any option
- check the navigation drawer, still home is selected

### Expected behaviour
The corresponding fragment should get selected

**Comment by konstzv** [comment]
Question:
The main screen has more actions than the navigation menu has  (for example Add password)
What should be selected for missing actions?

**Comment by Swati4star** [comment]
I'll write down the expected selected fragment : 
- For first, second, fourth & fifth row, it's pretty clear from the name
- For thrid row, select view files fragment for each of the three.
