### ISSUE TITLE
[Bottom sheet] Show animation while files are getting loaded

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#456]
Show this animation while the files are getting loaded:
https://www.lottiefiles.com/2269-search-file

[Take care of animation color in different themes]

Currently, only a text `fetching files` is displayed.

**Comment by nitinnatural** [comment]
@Swati4star Can you explain this.. like at which screen need to implement this.

**Comment by Swati4star** [comment]
Check this PR. https://github.com/Swati4star/Images-to-PDF/pull/455
I am talking about the bottom sheet. While the files are getting fetched, only `fetching files` is displayed. I want it to be replaced with animation
