### ISSUE TITLE
[Merge PDF] Merge PDF button remains white after File selection.

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#458]
# Merge PDF button remains white even after File selection.
## how to reproduce
* Home -> Merge PDF
* Add Files 
* Merge PDF button enables and color remains white.

## Expected Behaviour
* Color of the `Merge PDF` button should be same as of `Select Files` button

**Comment by vyankatesh24** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Sure. Go ahead :+1:

**Comment by Swati4star** [comment]
Fixed!
