### ISSUE TITLE
[Bottom Sheet arrow icon] Add animation to bottom sheet arrow icon when it is getting slide up or down

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#460]
The bottom sheet in merge/split/reorder/remove   pages....and many other options, has a arrow icon.
The icon gets change to down & up. Add animation to it.

### Reference
https://android.jlelse.eu/choreographic-animations-with-androids-bottomsheet-fef06e6ecb81
[Check 2nd one here : Image animation]

**Comment by amy6** [comment]
Hey @Swati4star I'd like to take this up!

**Comment by Swati4star** [comment]
Sure @amy6 👍
