### ISSUE TITLE
Delete Selected / Delete All files features.

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#47]
Add an option on the action bar (along with the filter icon).
Upon clicking that option, checkboxes should appear on the left of PDF file names. ( should allow selecting the PDF files)
On clicking the delete icon on action bar, a dialog for confirmation should appear & files should be deleted.

**Comment by Pl4gue** [comment]
Working on that 👍

**Comment by Swati4star** [comment]
Thanks @Pl4gue for fixing this 👍 🎆

**Comment by Swati4star** [comment]
This issue still needs work. The UI should be as specified in the description.
