### ISSUE TITLE
[Welcome Activity] Add more fragments

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#471]
- Add more fragments on Welcome activity related to,
  - text to PDF & qr code to PDF
  - remove, reorder, extract images from PDF

**Comment by AndresMx35** [comment]
Hi. I would like to try to solve this one, can I?

**Comment by Swati4star** [comment]
Sure @AndresMx35 👍

**Comment by Swati4star** [comment]
Status update @AndresMx35 ?

**Comment by Rita-Okonkwo** [comment]
Hi @swati4star..can the fragments be blank?

**Comment by Swati4star** [comment]
No. They cant be blank. They are supposed to contain the information about the features our app has.

**Comment by Rita-Okonkwo** [comment]
Okay thank you for the reply. Does it mean that I should put the information in view pager and tab layout format? Because I'm quite confused. Very sorry if I'm stressing you

**Comment by Swati4star** [comment]
If you have issues on how to code this, should continue the chat on slack.

**Comment by Swati4star** [comment]
@Rita-Okonkwo Are you working on this one?

**Comment by jddeep** [comment]
@Swati4star I would like to work on this.

**Comment by jddeep** [comment]
Please review #620 before that. Thanks,

**Comment by Swati4star** [comment]
Sure @jddeep
