### ISSUE TITLE
View Files 

### ISSUE THREAD

**Issue by sandraprog** [Swati4star/Images-to-PDF#479]
In View Files fragment checkbox in the ActionBar remains unchecked even after file selection.
**How to reproduce:**
- Home -> View Files
- Click on a checkbox in the ActionBar
- All files are checked, but checkbox remains unchecked

**Expected Behaviour:**
- Checkbox should change its state
	
I would like to fix it

**Comment by Swati4star** [comment]
You can work on fixing it 👍
