### ISSUE TITLE
Show a button also to open the created PDF in Reorder/Remove/Compress PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#482]
### Steps
- Go to Reorder/Remove/Compress PDF
- Select the PDF, fill up the entries.

### Actual behaviour
Only a snackbar with `view` action is displayed to open the PDF

### Expected behaviour
Add a button also on the screen `Open PDF` after the PDF is created.

**Comment by Diksha2008** [comment]
@Swati4star I would like to take this up!

**Comment by Swati4star** [comment]
Sure @Diksha2008 👍
