### ISSUE TITLE
Lock icon color in view files

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#489]
- Go to  view files
- The encrypted PDFs have a lock icon at top right

### Issue
The icon color is white, so it is not visible

## Fix
Change the icon color to black in white theme.
Take care of icon color in different themes too.

**Comment by sandraprog** [comment]
Hi, it seems ViewFiles is my favorite fragment :D Can I take this issue?

**Comment by soulspark666** [comment]
Can you please point me out to the drawables. I can take on this issue if @sandraprog is not interested now.

**Comment by Swati4star** [comment]
Sure! @sandaprog you can take it up! :)
