### ISSUE TITLE
New feature : compress image

### ISSUE THREAD

**Issue by liuatgit** [Swati4star/Images-to-PDF#49]
Would you add "compress image" function in it? The PDF file is too big.

**Comment by Swati4star** [comment]
Sure. We will work on a new feature in 'Image enhancement options'.
That will include the level of compression.

**Comment by Swati4star** [comment]
For reference : https://developers.itextpdf.com/examples/image-examples-itext5/reduce-image

**Comment by shiv07tiwari** [comment]
Can I start working on it @Swati4star  ?

**Comment by Swati4star** [comment]
Sure @shiv07tiwari 👍

**Comment by shiv07tiwari** [comment]
Exactly where should I add this feature ?

**Comment by Swati4star** [comment]
In the home page only, where we have crop images & password protect PDF option

**Comment by shiv07tiwari** [comment]
Okay !

**Comment by shiv07tiwari** [comment]
Some doubts  :
1. The pdf can be compressed only when the pdf is already created, so I should add a toast asking the user to first create the pdf , if they press the option without doing so (as the option is below password protect pdf) ?
2. We have to keep both(compressed and uncompressed) files or just compressed file ?
(If both, what should be the name of compressed one ?)

**Comment by Swati4star** [comment]
@shiv07tiwari Sorry for putting up the wrong reference link. This feature will be added in `Other enhancement options` in the home page only.
'Compress image`: By default it should be 100%.
The user should be allowed to enter (in %) the compression level of image. Compress the images accordingly then, before creating PDF

(Reference: https://stackoverflow.com/questions/18545246/how-to-compress-image-size)

**Comment by shiv07tiwari** [comment]
@Swati4star  I saw the reference, and found a nice library for image compression.
https://github.com/zetbaitsu/Compressor
Can I use this library ?

**Comment by Swati4star** [comment]
Sure @shiv07tiwari 
Use the library
