### ISSUE TITLE
The animation in bottom sheet (while the files are getting fetched), doesn't look good in different themes

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#494]
Here are the screenshots:
<img width="310" alt="screenshot 2018-10-11 at 11 20 08 pm" src="https://user-images.githubusercontent.com/9164477/46823625-4e81d280-cdac-11e8-9329-cad10e49128a.png">
<img width="309" alt="screenshot 2018-10-11 at 11 20 26 pm" src="https://user-images.githubusercontent.com/9164477/46823626-4f1a6900-cdac-11e8-8416-143710ecbb15.png">
<img width="336" alt="screenshot 2018-10-11 at 11 20 47 pm" src="https://user-images.githubusercontent.com/9164477/46823627-4f1a6900-cdac-11e8-844e-34abfc6b785f.png">

- The animation is in a aquare white block. Remove that white block

**Comment by antercepter** [comment]
@Swati4star I'll do this

**Comment by Swati4star** [comment]
Sure @antercepter 👍

**Comment by antercepter** [comment]
@Swati4star Can you please please provide steps to reproduce this issue?

**Comment by Swati4star** [comment]
you will have to look into the code. If there are few PDFs on your device, you might not be able to see this animation (as it is being shown while files are getting loaded)

Here [ https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/java/swati4star/createpdf/util/PopulateBottomSheetList.java ] - the background task is being called

https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/java/swati4star/createpdf/util/PopulateBottomSheetList.java#L31 : when this is called, https://github.com/Swati4star/Images-to-PDF/blob/28928ee4602dccf9545d29a7d58a7641e4067a6f/app/src/main/java/swati4star/createpdf/fragment/SplitFilesFragment.java#L166 (..this is in a number of other fragments too), the animation is set to gone, and bottom sheet items are getting displayed

**Comment by antercepter** [comment]
@Swati4star I'm sorry again, but I  can't reproduce this issue. Can you please provide some video when bug happened?

**Comment by sandraprog** [comment]
I'm afraid when the white block will be removed the animation will be almost invisible on a black background.

**Comment by Swati4star** [comment]
I think, for the black themes, we should change the animation file colors.

**Comment by sandraprog** [comment]
It seems that one does not simply change background color of animation to transparent:
https://github.com/sonaye/lottie-editor/issues/12
And i'm not sure that there is a way to set it programmatically

**Comment by mohammaduvez** [comment]
Any progress here?
I want to take this.

**Comment by Swati4star** [comment]
No progress here. You can take it up 👍 @mohammaduvez
