### ISSUE TITLE
FAQs and Privacy Policy Statement.

### ISSUE THREAD

**Issue by HarryHeights** [Swati4star/Images-to-PDF#495]
Hello, I'm Harry. I'm a content creator and a copywriter and I engage in contributing to open source projects by creating documents I feel is necessary. Documents I create range from Terms of service, privacy policy to FAQs.
For your project, if it's needed by you, I could help to create FAQS and Privacy Policy for your project.
I'd love to hear your thoughts on this. Thanks

**Comment by Swati4star** [comment]
Hi Harry, 
We already do have a privacy policy : https://sites.google.com/view/privacy-policy-image-to-pdf/home

You can check this, and if you feel like some change is required. Do let me know.
Also, would be happy to have a FAQ

**Comment by HarryHeights** [comment]
Alright then. I'll work on the FAQs and send a pull request.
