### ISSUE TITLE
Create an instant App version of PDF Converter

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#496]
Reference:
https://codelabs.developers.google.com/codelabs/android-instant-apps/index.html#0

Refactor the code as mentioned above...

**Comment by Vanethos** [comment]
I'm going to try this, and will update if I can get it to work :D

**Comment by Swati4star** [comment]
Sure @Vanethos 👍

**Comment by Vanethos** [comment]
Added PR https://github.com/Swati4star/Images-to-PDF/pull/500

**Comment by IndianKoder** [comment]
Hi..can I take this up?

**Comment by Vanethos** [comment]
@IndianKoder I have been working on the instant app, and went through creating the link for the main activity, in PR #500
