### ISSUE TITLE
Add a previous button in image cropper activity

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#507]
<img width="316" alt="screenshot 2018-10-18 at 10 50 25 pm" src="https://user-images.githubusercontent.com/9164477/47172130-3ff56700-d328-11e8-8997-85eb0b1507cb.png">

Currently, user can't go to previous image.

### Expected behaviour
Add a left arrow icon in the bottom bar (before `crop image no. x`)
On clicking this, the image should change to previous one.

**Comment by karimerikanto** [comment]
Hi, just installed this app (looking nice). I could take a look at this issue :)

**Comment by Swati4star** [comment]
Sure @karimerikanto !
Just create a PR :)

**Comment by Swati4star** [comment]
Hey @karimerikanto ! Thanks for appreciating. This issue is already fixed by https://github.com/Swati4star/Images-to-PDF/pull/508 from @vbvjain!
You can pick up some other issue, or create a new one 👍
