### ISSUE TITLE
Broken F-Droid build ("Insufficient Permissions" error)

### ISSUE THREAD

**Issue by phuyuk** [Swati4star/Images-to-PDF#51]
Why are you linking to a broken 2016 F-Droid build ("Insufficient Permissions" runtime error)?  Even the Google Play link is sketchy - it's categorized under "education" and is more or less unsearchable on Google Play.

The F-Droid and Google Play badges infer credibility to your app; please fix/update/explain (or remove) them.  Thx.

**Comment by Swati4star** [comment]
I will fix the F-droid build soon. By the time, you can download the app from playstore
https://play.google.com/store/apps/details?id=swati4star.createpdf

**Comment by Swati4star** [comment]
Removed the fdroid link now. 
Now, we have playstore link for those who wish to try out the app without building the code.
