### ISSUE TITLE
[New feature] Invert PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#512]
### what to do?
- add a new option in home page, as well as in navigation drawer: `Invert PDF`
- On clicking this, open up a new fragment : UI similar to remove pages
- As name suggests, the output PDF should have inverted colors.

**Comment by dixi3** [comment]
I'll try this

**Comment by Shivamdhuria** [comment]
Hey, Is this in progress?I'd be glad to take over if not.

**Comment by Swati4star** [comment]
Yeah sure. You can take it up. 👍

**Comment by Shivamdhuria** [comment]
Hey,
While inverting colors, Should I invert all the colors or just black & white?

**Comment by Swati4star** [comment]
All the colors.

Regards,
Swati Garg

**Comment by Shivamdhuria** [comment]
Implemented with all colors then.
:)
