### ISSUE TITLE
[New feature] Remove duplicate pages from a PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#514]
- Add a new option in the navigation drawer & home page : `Remove duplicate pages`
- Allow users to select a PDF file, and then create a new PDF with duplicate pages removed from that PDF

**Comment by Shivamdhuria** [comment]
Would love to get started on this.

**Comment by Swati4star** [comment]
Sure @Shivamdhuria

**Comment by Swati4star** [comment]
I dont have any. You can pick...

**Comment by Shivamdhuria** [comment]
Hey,I am almost done with the feature, except the icon for this.Currently I am using just one of the resource file (same that of merge) .Can you let me know where did you find the rest of the icons ?

**Comment by Swati4star** [comment]
I found most of the icons from the Android Studio only, and few from the online resources. If you didn't find anything relevant, you can make a PR with placeholder icon only. @Shivamdhuria 👍

**Comment by Shivamdhuria** [comment]
Hey ,I tried making a PR but got overwhelmed by merge conflicts. I am trying to move forward by referring to this article 
http://ronanmoriarty.com/uncategorized/git-basics-by-example-05-resolving-merge-conflicts/
Does this seem an appropriate way to get rid of merge conflicts?

**Comment by Swati4star** [comment]
@Shivamdhuria Yes, this is a correct way. 
You can try this to remove merge conflicts.

**Comment by Shivamdhuria** [comment]
Hey,
I have sent a PR, however I am not sure if it's the right way(this is my first).If this doesn't work I can clone again and make changes.

**Comment by Shivamdhuria** [comment]
Hey,
I think I ruined my repository,I'll clone again and make changes and send a PR in a couple of days.

**Comment by Swati4star** [comment]
@Shivamdhuria Any updates?

**Comment by Shivamdhuria** [comment]
Hey,
When I run ./gradlew aseemble,I get a ton of issues regarding sdk version and few more.(files that I never edited.)
I just ran the same command on your master branch and I still got those errors(overview attached)
[Lint Report.pdf](https://github.com/Swati4star/Images-to-PDF/files/2691829/Lint.Report.pdf)
Is there something I am missing?

**Comment by Swati4star** [comment]
I ran your PR locally. I have already mentioned the issues on PR.

**Comment by Shivamdhuria** [comment]
Hey,
I have sent in a new PR,some issues crept in while I was resolving merge conflicts.I made this a new repo from scratch.Also it's still failing ./gradlew assemble but everything else seems to be working.

**Comment by Shivamdhuria** [comment]
Hi,I have removed all unwanted comments and typos ,Thanks for being so patient!
:)
