### ISSUE TITLE
Canceling grayscale PDF bug

### ISSUE THREAD

**Issue by ajax333221** [Swati4star/Images-to-PDF#515]
1. Go to "Images to PDF".
2. Select one or more images.
3. Click on "Create grayscale PDF".
4. Cancel the "Create grayscale PDF" prompt box.

At this ponit the bug happens, you still see X image(s) selected but they are *likely gone.

*Note: there is a 10% chance the bug won't occur.

5. Click on "Add margins" to see if the images are gone (if not, go to step 3 and try again).

6. Click on "Create new PDF".
7. Type a name and "Accept".

An error of "Error on creating application folder" will be shown.

Here if you select more images, the image count will be compossed only by these newly added images, and the PDF can now be created with them.

Additional possibly important info:
-version 8.3.8
-just installed it / first run
-installed it via F-Droid

**Comment by Swati4star** [comment]
Hi, thanks for reporting the bug & giving such a detailed explanation! 
Will surely fix it in next update 💯
