### ISSUE TITLE
Add a whats new fragment

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#516]
- Whenever the app is updated (for each new app version), show a `What's New` dialog
- This dialog should have bullets with heading, content & icon (optional)
- The UI should be similar to this:
![screenshot](https://user-images.githubusercontent.com/9164477/47613986-5fc22300-dabe-11e8-8117-779bda72227e.png)

- The data should be parsed from a local json file (whatsnew.json) [ there is no json for now. Just add a sample json file]

PS, Don't use any library for this.

**Comment by Swati4star** [comment]
Sure @SaMumcu 👍

**Comment by SaMumcu** [comment]
Hello again. I could implement this issue with closing the checkstyle rules. I open today before to request PR but I couldn't understand the errors about checkstyle. It is referencing this path app/build/reports/checkstyle/checkstyle.html. Am I missing some point about the rules like camelCase or something like that?

**Comment by Swati4star** [comment]
Did you checked this html file: `app/build/reports/checkstyle/checkstyle.html` in your repo.

It'll show you a list of errors. We have a set of checkstyle rules to maintain coding standard.
You can open a PR, I'll tell the fixes.
