### ISSUE TITLE
Sorting option should not only be accesible via Preview

### ISSUE THREAD

**Issue by ajax333221** [Swati4star/Images-to-PDF#523]
For a second, I thought the app couldn't **Sort**¬ by image name/date, since I was looking for it inside the **Rearrange Images** section. I gave up looking it in there, then thought maybe it had a section on its own on the main tools? Nope.

It was not until I went to **Preview** that I found the **Sort**¬ option (next to **Rearrange Images**).

Not sure if it should have a section on its own, or a sub-section inside **Rearrange Images**, or something. But definitely not only accessible via **Preview**.

**¬ Note:** I am not entirely sure if the name is _Sort_, as in my language (Spanish) is labeled as _"Ordenar"_.

**Comment by Swati4star** [comment]
Your doubt is clearly valid. Let's add a sort option in `Rearrange images` section also.

**Comment by ondro2208** [comment]
I could look at this issue

**Comment by Swati4star** [comment]
Dont remove the option in `Preview images` section. Add it to rearrange images too 👍
