### ISSUE TITLE
Spanish (ES) translation to strings.xml

### ISSUE THREAD

**Issue by ajax333221** [Swati4star/Images-to-PDF#526]
Can someone review this updated version of the Spanish (ES) **strings.xml** I made?

https://github.com/ajax333221/Images-to-PDF/tree/master/app/src/main/res/values-es

Spanish is my first language, I'm pretty confident this is a solid translation and I plan on keep reviewing it a bit more for consistency. But this should be a good starting point, took me 3-4 hours, hope it works.

**Note:** if further action is needed from me, I need to say that I really don't know how to use GitHub, as in, create pull-requests or build the graddle test thingy (but this is just some changes on a xml, nothing should break... right?)

**Comment by Swati4star** [comment]
@ajax333221 I have created a PR on your behalf only (using your forked repo)

Can you just verify in the PR(https://github.com/Swati4star/Images-to-PDF/pull/528) if the changes are fine.

I dont know spanish, so I cant help in translation

**Comment by ajax333221** [comment]
The changes were applied yes. I will do some more testing to see if I accidentally translated something wrongly, (sometimes the verbs and things like that can be tricky in my language).

Anyway, so far so good. (:

**Comment by Swati4star** [comment]
So, is there anything left? 
or should i merge your changes?

**Comment by ajax333221** [comment]
it's fine now :+1:
