### ISSUE TITLE
Some small changes to strings.xml

### ISSUE THREAD

**Issue by ajax333221** [Swati4star/Images-to-PDF#527]
While I was doing a complete translation of the Spanish (ES) strings.xml , I noticed some stuff. I will list them here as **[line-number]** (by the time I noticed it was better to list it as the _name=""_ attribute, it was too late, sorry I did it by line number):

- **[141]**: `"Directory does not exists"`, I think it should be "exist" (https://ell.stackexchange.com/a/23944)
- **[145]**, **[215]**: extra space in `"<space>?"`
- **[163]**: `"Move to<double-space>Home Directory"` double space
- **[372]**: `"2. Select Add<double-space>Watermark"` double space
- **[251]**, **[312]**: are very similar to **[98]**, but these two doesn't include the line `"Files on SD card are supported only currently"` (the 3 of them should have this SD support note thing?)
- **[282]**: doesn't mention the word _default_, should it?
- **[323]**: `"and you can have three type of themes"`, implies we don't have them already?, if we do, maybe use the word _choose_ instead
- **[325]**, **[327]**: change `"pdf"` to PDF for consistency
- **[335]**: `<string name="create_images_success">(...). They have been saved in the PDF Files root directory.</string>` consistency with -> `<string name="extract_images_success">(...). They have been saved in the PDF Files folder in root directory.</string>`

**Edit:** also, **[78]**  `(...) It converts images to PDF so smmothly. :)` typo on "smoothly"

**Comment by Swati4star** [comment]
This is awesome observation! I will fix these soon in my upcoming PRs.
