### ISSUE TITLE
Converting to PDF is too slow 

### ISSUE THREAD

**Issue by zhangzzqq** [Swati4star/Images-to-PDF#53]
Converting to PDF is too slow in Lenovo YT3-X50F and HUAWEIG750-T00. is it the image to big (i see the image is 2M in album ) or others?

you can refer to the websites  :

https://github.com/zetbaitsu/Compressor

https://github.com/zetbaitsu/Compressor

**Comment by zhangzzqq** [comment]
It usually takes 5-10 seconds.

**Comment by zhangzzqq** [comment]
Usually a photo takes 5-10 seconds.

**Comment by zhangzzqq** [comment]
Usually a photo takes 5-10 seconds.

**Comment by Swati4star** [comment]
This seems to be a valid issue. If anyone is interested in taking it up, they can.

**Comment by kmark1625** [comment]
I submitted a pull request for this issue to use the linked compressor instead.  I saw improved performance using a normal sized file (3.74 MB).  Please let me know if you have any questions or if there is anything additional I can add to this investigation.  Thanks!
