### ISSUE TITLE
Allow selection of text files (for text to pdf) in location other than "Downloads"

### ISSUE THREAD

**Issue by Bernmeister** [Swati4star/Images-to-PDF#530]
Would like to convert a text file (visible under the default File Manager app) in say "Phone Storage / Documents" or "Phone Storage / Download" to pdf, but the option of selecting a file only goes to "Downloads" and I cannot find that under the file manager.

Any chance to browse/select a text file in the general phone storage area please?

**Comment by Swati4star** [comment]
Great finding! 
This issue is up for grabs if anyone is interested. 👍

**Comment by arboledasaa** [comment]
Hi, i was checking on my phone and i can see all my files on the phone

![screenshot_20181123-083445_files](https://user-images.githubusercontent.com/7919060/48946308-44023f00-eefb-11e8-92a1-241a52634c88.jpg)

May i know your phone model/rom? to see if it is a version specific issue

**Comment by Swati4star** [comment]
@Bernmeister Even I am able to access the files in other location too. 
Can you please provide more info?

**Comment by Bernmeister** [comment]
Phone is a ZTE Blade A110, Android 5.1

**Comment by Swati4star** [comment]
Good finding @arboledasaa 👍 

I think, a pop-up warning message should work.

**Comment by jddeep** [comment]
@Swati4star I am GSSOC 19 participant and would like to work on this issue. Should I start working now and make a PR. Or should I wait for the coding period to begin?
And is there is a slack channel for this project?
Thanks.

**Comment by Swati4star** [comment]
If you want this PR to be scored in gssoc19 scoring, do it during the coding period only.
Yes, we do have a slack channel. It's link is in the readme only.

Also, if you are gssoc19 participant, you must have got an invite to gssoc19 slack group. We can discuss more over there also.

**Comment by jddeep** [comment]
@Swati4star yes i have already joined the gssoc19 slack channel. Okay will now be joining this projects slack channel too. Thanks.

**Comment by Swati4star** [comment]
Sure. Go ahead
