### ISSUE TITLE
Rotating images usability

### ISSUE THREAD

**Issue by ajax333221** [Swati4star/Images-to-PDF#533]
I find it a bit confussing that:
1) rotating the image(s)
2) pressing the confirm arrow

doesn't actually rotate them, you need to:
i) rotate the image(s)
ii) stretch the crop window to 100% (as to not crop anything, since default window is a bit less than 100%, and for some reason the changes are only saved when the cropping button is pressed)
iii) click on the crop button
iv) press the confirm arrow

I think there should be a way to do this rotating thing wihout doing steps ii and iii

**Comment by Swati4star** [comment]
I agree with you. 

Will it be fine if the window is by default stretched to 100%?
This should fix the issue.

**Comment by ajax333221** [comment]
I think it would be fine if:
-starting at 100%
-adding some visual indicator that shows if changes were made (i.e the button is disabled, and after any rotation or cropping it becomes clickable), but in this case, the crop button should be named something like "apply/apply changes"
-(optional) after applying changes, it moves to the next image (or exit if it is the only image)

**Comment by Swati4star** [comment]
This seems good.

### What to do?

The requirements are then:
- by default, window should be stretched by 100%
- change the name of `crop` button to `Apply`
- The `Apply` button should be disabled by default.
- The button should be enabled, when the crop window is moved, or the image is rotated.
