### ISSUE TITLE
Weird behavior when selecting PDFs on View Files with elements at the beginning

### ISSUE THREAD

**Issue by ajax333221** [Swati4star/Images-to-PDF#537]
In the View Files section, the PDF file list seems to be composed of: "**BuggedStarters**" and "**Normals**" (let's call them like that, I will elaborate more below).

- _BuggedStarters_ can be **the first** 0 to (4?) items from the list.

- _Normals_ will be all the normal non-bugged remaining items from the list.

The "BuggedStarters" seem to appear when the list of view files list is greater than 5 items, and seem to cap at max of 4 of them. Examples:

- 5 items = 0 BuggedStarters + 5 Normals

- 6 items = 1 BuggedStarters + 5 Normals

- 8 items = 3 BuggedStarters + 5 Normals

- 11 items = 4 BuggedStarters + 7 Normals

**How to recognize a BuggedStarter? / What's the problem with them?**

When you select one (or more) BuggedStarters, and then click on the Check/Uncheck box at the top, you will notice that they get unchecked, but the Check/Uncheck box at the top won't disappear (which do happen when one (or more) Normals are selected, when not mixed with BuggedStarters of course). As a side note, when you select a mix of BuggedStarters with Normals, the Check/Uncheck box at the top behaves as expected and disappears.

The bug is _not_ critical, since clicking the non-disappeared Check/Uncheck box at the top will then check all the files **(†)**, and clicking it one more time will uncheck all the files.

I have not done enough testing to see how things aside from the Check/Uncheck box at the top are affected by this.

If no one can replicate this for some reason, or if the replication steps are unclear, I could try to provide some screenshots and create a Gif with them, but I find it a bit bothersome and would only do this if entirely necessary or requested.

**(†)** the number of selected items does not appear in this scenario, not unless you perform a refresh.

**Comment by amy6** [comment]
@Swati4star  I'd like to give this a try.

**Comment by Swati4star** [comment]
Sure @amy6  👍

**Comment by Swati4star** [comment]
any updates @amy6 ?

**Comment by amy6** [comment]
@Swati4star Issue has been resolved. Sending a PR in a few minutes.
