### ISSUE TITLE
Update to Spanish (ES) translation to strings.xml

### ISSUE THREAD

**Issue by ajax333221** [Swati4star/Images-to-PDF#538]
My followup to https://github.com/Swati4star/Images-to-PDF/issues/526 with some corrections + translated a new section that was added after the initial translation.

I don't know how to pull-request, if it can be created on my behalf like last time, I would appreciate.

Here is the forked branch: https://github.com/ajax333221/Images-to-PDF/blob/master/app/src/main/res/values-es/strings.xml

**Comment by Swati4star** [comment]
I have created https://github.com/Swati4star/Images-to-PDF/pull/542 

If there are any more changes to be made, you can do it in your fork only.
