### ISSUE TITLE
PDF to images is not working fine

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#551]
### Steps
- Go to `PDF to images` from navigation drawer or home page
- select a PDF
- Select convert

### Expected behaviour
The images should be as that in the PDF

### Actual behaviour
The images saved have the inverted colors as the actual pages

**Comment by Swati4star** [comment]
Did you checked the images by `View Images` or by sharing/viewing them in gallery.
For this PDF:http://www.africau.edu/images/default/sample.pdf
I am getting output as these images (when i click on `share images`)
![1](https://user-images.githubusercontent.com/9164477/50738517-e7cd5300-11fa-11e9-9155-0bb4a8f2989b.jpeg)
![2](https://user-images.githubusercontent.com/9164477/50738518-e8fe8000-11fa-11e9-8c3d-afbd6ab5fcf4.jpeg)

**Comment by obpacheco** [comment]
I was able to recreate this problem
1. From action bar click >PDF to Images
2. >Select a File
3. Pick a pdf
4. Make sure you pick a PDF that has text data as it seams like the tool handles images fine
5. Anything that has text turns to black while images are converted correctly
Here is an example of the output I was getting
![1337_1](https://user-images.githubusercontent.com/46357909/50799094-915e2400-128f-11e9-9d01-c9a3f58ac7ca.jpg)

**Comment by obpacheco** [comment]
I'll try looking into what is causing this issue
