### ISSUE TITLE
Different icon for remove pages & remove duplicate pages

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#561]
### Steps
- Open navigation drawer
- or go to home page

### Actual behaviour
<img width="343" alt="screenshot 2019-02-17 at 3 00 42 pm" src="https://user-images.githubusercontent.com/9164477/52910963-f2ccd600-32c4-11e9-9fcb-20b2b0ee7a08.png">

### Expected behaviour
- Add different icon for remove pages & remove duplicate pages

**Comment by infiniteoverflow** [comment]
I would like to do this task

**Comment by Rita-Okonkwo** [comment]
Would love to contribute to this

**Comment by Swati4star** [comment]
@infiniteoverflow has already commented. He will be working on this issue.

**Comment by infiniteoverflow** [comment]
@Swati4star Do u have any specific icons that have to be provided or any custom one will do?

**Comment by Swati4star** [comment]
Any custom one will do. Check online.
Don't use pngs, use vector drawables.

**Comment by Swati4star** [comment]
@infiniteoverflow This issue should be completed in 1-2 days. Are you facing any issue? are you working on this?

**Comment by infiniteoverflow** [comment]
@Swati4star Sorry mam for the delay. I had some personal issues. I will complete the task first thing in the morning tmrw.

**Comment by SupreethBaliga** [comment]
Is this issue still open? I am interested in contributing.

**Comment by Swati4star** [comment]
@infiniteoverflow is working on it. @SupreethBaliga You can pick up any other open issue

**Comment by SupreethBaliga** [comment]
Okay. In case he @infiniteoverflow leaves it, please allow me to have a try on it.Thanks.

**Comment by infiniteoverflow** [comment]
Yeah sorry for the delay. I will be completing this today itself :)

**Comment by infiniteoverflow** [comment]
Sorry i wont be able to work on this as i am engaged with some other works.

**Comment by sidhuparas** [comment]
@SupreethBaliga You can start working on this issue.

**Comment by SupreethBaliga** [comment]
Ok. Can I get a bit of info about where exactly I have to make the changes? As in can you tell me the name of the files associated with it? Thanks.

**Comment by Shivamdhuria** [comment]
@SupreethBaliga  Go to resources>layout>fragment_home.
Edit the option_icon property to the new icon.
Do the same for layout file of navigation menu.

**Comment by SupreethBaliga** [comment]
Ok got it. Working on it. Will let you know as soon as I am done. Thanks.

**Comment by SupreethBaliga** [comment]
I have a bit of an issue. I am not being able to test the application. My phone API level is than 20 and hence not being able to test. Also, emulator is really slow and app crashes. What do I do?

**Comment by SupreethBaliga** [comment]
Done.
