### ISSUE TITLE
Add sections and section headers in navigation drawer

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#562]
### Steps
Open navigation drawer
<img width="291" alt="screenshot 2019-02-17 at 3 03 15 pm" src="https://user-images.githubusercontent.com/9164477/52911086-3293bd80-32c5-11e9-99c6-894e21bf38fb.png">

### Actual behaviour
All the items are listed in one big group

### Expected
- Add the items in different sections (in accordance with the home page)

**Comment by AfolabiDonko** [comment]
Hi, I'm going to try this

**Comment by Swati4star** [comment]
Sure @AfolabiDonko  👍

**Comment by Ni3verma** [comment]
@Swati4star can I do it?
(Gssoc P)

**Comment by Swati4star** [comment]
@AfolabiDonko are you working on this issue?
( Please take up only one issue at a time. You have commented on #581 too)

**Comment by AfolabiDonko** [comment]
@Swati4star yes, i am currently working on this issue. I'll begin the #581 after.
