### ISSUE TITLE
Add option to `View images in Gallery` in  PDF to Images and Extract Images

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#564]
- In  PDF to Images and Extract Images, add a new option (after the images are created) - `View Images in Gallery`
- On clicking this, open the folder in which images are created in the gallery

**Comment by jddeep** [comment]
I would like to work on this issue. @Swati4star (gssoc19)

**Comment by Swati4star** [comment]
You'll be assigned only one issue at a time. and you already have one assigned. 
So, comment on other issue when you are done with previous one. @jddeep

**Comment by jddeep** [comment]
@Swati4star Okay. I want to make a PR but I need to wait for 1st March for gssoc19 coding period to start. If there is another way please inform me. Thanks.

**Comment by Swati4star** [comment]
No. There isn't any other way. Create the PR for the other issue first.

Meanwhile, you can work on this also. (If you want)

**Comment by Swati4star** [comment]
@jddeep You comment on multiple issues at a time. Please pick one first, then comment on it & wait before your previous PR is approved.

**Comment by jddeep** [comment]
@Swati4star Sorry for any inconveniences caused.

**Comment by Swati4star** [comment]
Okay @jddeep. Just comment on the issue you are working on currently.
