### ISSUE TITLE
Add Whats New to navigation drawer

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#565]
- We already have a whats new fragment which is shown once, when app is upgraded/downloaded
- Add this option in navigation drawer also ( in Extras)
- On clicking this, a new fragment should open up. It should have a list of all the whatsnews with the versions We keep it in the form of json : https://github.com/Swati4star/Images-to-PDF/blob/1688389c5ce71b5bea046b602142d1ad3eefe59f/app/src/main/assets/whatsnew.json

**Comment by yati1998** [comment]
Hello, can I cintribute to this?

**Comment by yati1998** [comment]
Hey, Can I contribute to this issue?

**Comment by jddeep** [comment]
@Swati4star I would like to look into this issue too as a part of gssoc19.

**Comment by Swati4star** [comment]
Sure @yati1998 

If @yati1998 is not working on it, then you can @jddeep

**Comment by yati1998** [comment]
@swati4star I am working on this issue..can you assign me this issue??

**Comment by Swati4star** [comment]
Sure @yati1998 
You can create a PR for this

**Comment by yati1998** [comment]
But all the PR will be counted after 1st March..so will it be ohk if I make PR on 1st of March

**Comment by Swati4star** [comment]
Fine @yati1998 
Create PR on 1st.

**Comment by Swati4star** [comment]
@yati1998 are you working on this?

**Comment by yati1998** [comment]
yes I am.  Bit confused with the code.  Will try to make the PR as soon as possible

**Comment by sidhuparas** [comment]
@yati1998 It's taking significant amount of time. If you need help, share your problem in #images-to-pdf Slack channel.

**Comment by yati1998** [comment]
@sidhuparas I am sorry for being this late.  I was stuck some where.  I have asked for the help in slack.  Will try to make a Pr by tomorrow.

**Comment by vyankatesh24** [comment]
@yati1998 
Any Progress?

**Comment by theabhishekavi** [comment]
@vyankatesh24 can i work on this?

**Comment by vyankatesh24** [comment]
Sure @theabhishekavi :+1:

**Comment by jddeep** [comment]
> If @yati1998 is not working on it, then you can @jddeep

But @vyankatesh24 @theabhishekavi I am supposed to work on this . See this : https://github.com/Swati4star/Images-to-PDF/issues/565#issuecomment-467502107

**Comment by vyankatesh24** [comment]
Sorry @theabhishekavi !
You may take up some other issue.
