### ISSUE TITLE
build.gradle file error

### ISSUE THREAD

**Issue by Ni3verma** [Swati4star/Images-to-PDF#568]
compile sdk version and support library versions do not match
![bug](https://user-images.githubusercontent.com/20037625/53187333-ec25c200-3628-11e9-8246-d2c5214fd117.png)

**Comment by jddeep** [comment]
@Swati4star I am a gssoc19 Participant and I would like to work on this issue. When should I consider making a PR in this case?

**Comment by vyankatesh24** [comment]
@jddeep You can make PR right now. But PRs after 1st March will be counted in GSSoC'19 .

**Comment by Ni3verma** [comment]
If no one is assigned, I would like to work on this issue

**Comment by jddeep** [comment]
I am willing to work on this issue and i also approached to resolve it first. But i am waiting only for 1st March after which i shall make a PR. @Swati4star kindly confirm.

**Comment by Swati4star** [comment]
@jddeep commented first on this issue. You can start working on it & create a PR.
