### ISSUE TITLE
App crashes when invalid input is entered into Split PDF Fragment

### ISSUE THREAD

**Issue by Shivamdhuria** [Swati4star/Images-to-PDF#569]
<a href="url"><img src="https://user-images.githubusercontent.com/10262897/53320053-6c367b00-38fa-11e9-8283-8be4fb1a4a7f.png" align="left" width="300" ></a>
The Edit Text  in Split Fragment takes in the input in **1,2-3,5-7,8** format which then splits the pdf accordingly.    
When the user enters anything like alphabets,special characters etc the App crashes.The edittext input needs to be validated and user should be informed about incorrect input.

**Comment by quicksilver28** [comment]
Hello! I am a gssoc participant. I am interested in solving this issue!

**Comment by Ni3verma** [comment]
I would like to work on it

**Comment by Swati4star** [comment]
Sure @Ni3verma

**Comment by Ni3verma** [comment]
Everytime I click on split pdf, i get the snackbar saying "we were unable to access pdf, files may be encrypted or in the external storage".
I have tested with many different pdf files. Problem even happens if I open a pdf which I created using this app.
Running on miA1 android 9

**Comment by Shivamdhuria** [comment]
Hey, @Swati4star  I downloaded the app from the playstore on my One Plus ,Android 8 and I can't seem to access any of the features.So far I have tried to Remove Pages,Merge Files,Add water Mark,Split files,Invert colors but all of these give "file may be encrypted" snackbar.I tested all these features before on a Pixel 2 emulator where they worked smoothly.Perhaps a new issue for this needs to be created?

**Comment by Swati4star** [comment]
Did you select files from the bottom bar or using the orange slider?

**Comment by Shivamdhuria** [comment]
It is working when file is selected using orange slider ,but gives error when I try to select using "Select a File" (blue Button)

**Comment by Swati4star** [comment]
@Ni3Verma @shivandhuria
Let's this issue be as is. Select file using orange slider.

I'll create a different issue that sometimes files are not getting selected when we use blue button.

**Comment by Ni3verma** [comment]
Okay
