### ISSUE TITLE
History section shows wrong entry for Invert PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#570]
### Steps
- go to invert PDF section. select a PDf, invert it.
- go to history section

### actual behaviour
<img width="353" alt="screenshot 2019-02-26 at 10 45 41 pm" src="https://user-images.githubusercontent.com/9164477/53432313-499a8400-3a18-11e9-8b95-122b00ea7540.png">

### expected
- The entry should show 'Inverted', instead of 'The PDF could not be inverted'

**Comment by pranay2063** [comment]
Hi Swati, I could not find any invert PDF section. Do you mean reorder PDF? Also, when I try to select any PDF file (including the ones generated in the app or selected from drive), I get an error saying "We are unable to access PDF. File may be encrypted or in external storage". Please elaborate.

**Comment by Swati4star** [comment]
No. I mean invert PDF only. 
The feature is not yet there in play store app. Either you can enroll in beta program on playstore, or run the app by building it from Android studio.

**Comment by SGagan** [comment]
I would like to do this task. I am a GSSOC participant.

**Comment by Swati4star** [comment]
@SGagan sure, you can work on it 👍

**Comment by vyankatesh24** [comment]
Congratulations @SGagan for First Contribution to #Images-to-PDF
Happy Coding :+1:
