### ISSUE TITLE
V8.5.7 is available for download?

### ISSUE THREAD

**Issue by realrufans** [Swati4star/Images-to-PDF#572]
Hello PO, kudos to you and the rest of the contributors for this great project. I'd like to know if there's anyway i can get the latest version? or it's not officially released yet? because you are still working on it? Thank you as you reply.,😊

**Comment by Swati4star** [comment]
Hi. Thank you @realrufans 👍 

We dont directly release the latest update for all the users on playstore. If you want early access to the updates, you can enroll in our beta program on playstore: https://play.google.com/apps/testing/swati4star.createpdf
💯 

We roll out the update to production only after we feel it is bug free! :D

**Comment by realrufans** [comment]
Thank you ❤
