### ISSUE TITLE
Add color picker in `Filter Images` section

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#573]
<img width="335" alt="screenshot 2019-02-26 at 11 02 50 pm" src="https://user-images.githubusercontent.com/9164477/53433637-c6c6f880-3a1a-11e9-8678-619bb30e793d.png">

- select **Images to PDF**
- Select few images. select filter images option
- select brush icon

Currently, we can select only a limited number of colors for brush. 

### What to do?
- At the end of the color boxes that show up on selecting the brush, add an icon. 
- on selecting that icon, open up a color picker dialog (We already are using a color picker library in watermark section. So, use that only)

**Comment by jddeep** [comment]
@Swati4star I would like to work on this issue next as I resolved #571 . Do check my forked repo for the same. Kindly confirm and assign to me.

**Comment by jddeep** [comment]
@Swati4star then as #571 is approved by you. Please assign me this issue. I would like to work on this. Thanks

**Comment by Swati4star** [comment]
@jddeep please comment on one issue at a time. you have commented on https://github.com/Swati4star/Images-to-PDF/issues/574 too. 

First, get started with this one.

**Comment by jddeep** [comment]
Okay, I will get started with this. Thanks.

**Comment by jddeep** [comment]
@Swati4star I have added another button for the color palette on the seekbar. Can you help a bit on how to open up the pallete which you were saying was there in the watermark section?

**Comment by Swati4star** [comment]
Go to view files. Select a PDF. Select add watermark option. There is a color picker in the dialog
