### ISSUE TITLE
The Next button is not visible in Filter Images

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#574]
### Description
The Next button is not visible in Filter Images may be only on 5 inch or below screen phone.

### Steps
* Create PDF
* Select few files
* Select Filter Images.

### actual behaviour
The Next button is not visible
![4b5ef35f-380e-48e5-abed-c4a71a7c94eb](https://user-images.githubusercontent.com/18503975/53581195-205a2f00-3ba3-11e9-866c-25f7d4a5aa59.jpeg)

### expected behaviour
The Next button should be visible

**Comment by jddeep** [comment]
I would like to work on this issue.

**Comment by Swati4star** [comment]
Change the textview  **Save Current** to **Save**

**Comment by jddeep** [comment]
After resolving #573 I will get to this, Thanks,

**Comment by Swati4star** [comment]
You may work on this now @jddeep
