### ISSUE TITLE
Add `Add Watermark` option to navigation bar also

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#577]
- This option is already there on home page
- Add this to navigation bar also.
- The behaviour should be same as what happens when we select it from home page.

**Comment by Tanyavarshney16** [comment]
I would like to work on this issue..(gssoc P)

**Comment by Swati4star** [comment]
Sure 👍

**Comment by Swati4star** [comment]
Updates @Tanyavarshney16

**Comment by aqeelparpia** [comment]
Hello there, I have stated working on this issue assuming it hasn't been worked on yet.
I shall be able to get it done soon @Swati4star

**Comment by srv-twry** [comment]
> assuming it hasn't been worked on yet.

@aqeelparpia The issue was already claimed by someone else. You can't just assume it.
