### ISSUE TITLE
Error message is displayed when PDF is selected using blue button

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#579]
- In many of the features (Remove Pages,Merge Files,Add water Mark,Split files,Invert colors), we are getting following error message when PDF is selected using blue button
- This snackbar is displayed "we were unable to access pdf, files may be encrypted or in the external storage"

**Comment by jddeep** [comment]
@Swati4star I would like to work with this. Can you please a describe a bit more on how exactly to reproduce here on my device.

**Comment by Swati4star** [comment]
It's reproducible on my device also. (one plus 5)
- go to  compress PDF section from navigation drawer (or home page)
- press the blue button. File Explorer opens up. select a PDF
- Enter something in the text
- When you select 'Create PDF`, the snackbar opens up "PDF is password protected"


I think, It happens because, we are not parsing the file path correctly.

(Also, complete https://github.com/Swati4star/Images-to-PDF/pull/583 first)

**Comment by Shivamdhuria** [comment]
I found out if we select a Pdf using the blue button,the mPath String is     
document/primary:Download/doc.pdf    
while selecting from orange slider it is     
/storage/emulated/0/Download/agenda1.pdf
I would like ti further work on this if it's unassigned.

**Comment by Swati4star** [comment]
@jddeep is working on https://github.com/Swati4star/Images-to-PDF/issues/563
So, you can start with this issue @Shivamdhuria

**Comment by Shivamdhuria** [comment]
Alright!
