### ISSUE TITLE
Crop Images option is not working on going back once & pressing it again

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#58]
Steps to reproduce :
1. Press 'Select Images'
2. Select atleast 1 image
3. Press 'Crop Images' option
4. Press back button on top
5. Press 'Crop Images' again.
It does nothing.

**Comment by sbhandare3** [comment]
Hi, I am working on this issue. Resetting mImageCounter solves this issue. But if we crop images first time, come back and then press crop again, images are original. Is this the way it should be? Just wanted to know. Thanks!

**Comment by Swati4star** [comment]
@sbhandare3 , Pressing back means that user wants to cancel it. So, we can safely assume that on pressing 'Crop Images' again, user should get original images only.

**Comment by Swati4star** [comment]
@sbhandare3 Are you working on it?
