### ISSUE TITLE
Theme is not getting applied on Help Activity

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#581]
### Description
    Theme is not getting applied on Help Activity
### Steps to reproduce
   * Goto Settings
   * Change Theme
   * Now open Help Activity from Navigation Drawer
### Actual behaviour
![image](https://user-images.githubusercontent.com/18503975/53678651-44735880-3ce8-11e9-8338-166631decf78.png)
![image](https://user-images.githubusercontent.com/18503975/53678652-489f7600-3ce8-11e9-86c2-14963e3d4f83.png)

### Expected behaviour
    Theme should be applied.

**Comment by AfolabiDonko** [comment]
Hi, can i work on this issue?

**Comment by AfolabiDonko** [comment]
@Swati4star can i work on this issue??

**Comment by Swati4star** [comment]
Sure @AfolabiDonko 

(Also, are you a gssoc participant?)

**Comment by AfolabiDonko** [comment]
Thank you ! I am not yet a gssoc participant @Swati4star

**Comment by sidhuparas** [comment]
@AfolabiDonko How's the progress? Any updates?

**Comment by AfolabiDonko** [comment]
I am on it now. I will make a pull resquest soon
