### ISSUE TITLE
Invert PDF icons is different in navigation bar and home page

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#586]
Invert PDF icons is different in navigation bar and home page

### Steps to reproduce
<img width="275" alt="screenshot 2019-03-03 at 7 32 56 pm" src="https://user-images.githubusercontent.com/9164477/53696249-2e9a8c00-3deb-11e9-9e54-2c4afc0eac44.png">
 
<img width="361" alt="screenshot 2019-03-03 at 7 33 02 pm" src="https://user-images.githubusercontent.com/9164477/53696251-30644f80-3deb-11e9-9f0c-04a90b38d582.png">

### Expected behaviour
Icon for `Invert PDF` in navigation drawer should be same as home page

### Actual behaviour
They are different

**Comment by sseryani** [comment]
I will do this

**Comment by Swati4star** [comment]
Sure @sseryani

**Comment by Swati4star** [comment]
Congrats on your first contribution to this project! @sseryani
