### ISSUE TITLE
Error displayed when images are removed in `Rearrange images` section

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#587]
Describe your issue here.

### Steps to reproduce
- go to `images to PDF`
- select few images.
- go to `rearrange images`. Select `X` for every image
- press back button on title bar
- select `Create PDF` button

### Expected behaviour
- `create PDF` button should be disabled when no images are currently selected
- The textview at bottom which shows `X images selected` should also hide

### Actual behaviour
- Snackbar "Error on creating application folder" is displayed

### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by gateway2rohan** [comment]
I want to work on this issue.

**Comment by Swati4star** [comment]
Go ahead 👍

**Comment by gateway2rohan** [comment]
Done. Already made a pull request
