### ISSUE TITLE
Add `Filter` option in history section

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#588]
Add `Filter` option in history section

### Steps to reproduce
Go to history from navigation drawer or home page

### Expected behaviour
- add a `filter` menu option in the title bar 
- on selecting it, open up a dialog with checkboxes on following options:
Created, Deleted, Renamed, Rotated, Printed, Decrypted, Encrypted, Inverted
- By default, all the option should be checked
- Based on the options selected by the user, show corresponding items only.

**Comment by Ni3verma** [comment]
I want to work on it

**Comment by Swati4star** [comment]
Sure @Ni3verma 
You can work on it 👍

**Comment by Ni3verma** [comment]
@Swati4star 
should I persist filter settings in shared prefs **or** everytime user clicks on filter option, every checkbox should be selected by default ?

**Comment by Swati4star** [comment]
No. By default, the filter should be 'All'

add 'all' option also to the filters list
