### ISSUE TITLE
Error when creating grayscale pdf

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#590]
### Describe your issue here. 
Error occures "Error on creating application folder".

### Steps to reproduce
* Create PDF
* Select Images
* Create grayscale PDF.
* Enter Name and Press OK

### Expected behaviour
* PDF should be created correctly
* Images shouldn't become grayscale when `Cancel` is pressed.

### Actual behaviour
* Error occures "Error on creating application folder".
* Shows images count as it is but when we click on any enhancement option Snackbar shows "No images Selected".
* Create PDF remains Enabled.

**Comment by itnug987** [comment]
I want to work on this issue

**Comment by Swati4star** [comment]
Sure @itnug987

**Comment by sidhuparas** [comment]
@itnug987 How's the progress? Any updates?

**Comment by itnug987** [comment]
Installed the project in my local machine. Found out where the error is occurring. Trying to fix it.

**Comment by sidhuparas** [comment]
@itnug987 Updates?

**Comment by srv-twry** [comment]
@itnug987 It is not a fatal error. It might be because you're not following the conventions of the project. for eg. maybe you're not using variable names according to project convention or maybe using 2 space indentation etc.

**Comment by sidhuparas** [comment]
@itnug987 It's exactly what @srv-twry said. Just refer to the file `checkstyle.html` whose path is included in the error message. That will help you solve the error(s).

**Comment by itnug987** [comment]
Thank you so much @sidhuparas @srv-twry  for the guidance. I am able to follow the conventions of the project now. Regarding the update of the issue: Error is occurring because the new file is not created in saveCurrentImageInGrayscale() in imagetopdfFragment.java file. Here dir.mkdirs() is returning false. I am not understanding what should be the pathname to be given. I will try to fix it.
![Screenshot (32)](https://user-images.githubusercontent.com/28648172/54494763-be6c2a00-4903-11e9-8e38-57d719230b9e.png)

**Comment by sidhuparas** [comment]
Try something like this for debugging purposes: 
` File file = new File(
                Environment.getExternalStorageDirectory(), "/Folder");`

**Comment by itnug987** [comment]
Tried it. Not working.

**Comment by sidhuparas** [comment]
Make sure you have granted read and write permissions for external storage.

**Comment by itnug987** [comment]
Yes, I have granted read and write permissions for external storage also.

**Comment by vyankatesh24** [comment]
@itnug987 Any Progress?

**Comment by itnug987** [comment]
@vyankatesh24 I am able to create the pdf but not in grayscale. I am working on it.

**Comment by vyankatesh24** [comment]
> @vyankatesh24 I am able to create the pdf but not in grayscale. I am working on it.

The PDF is already getting created in grayscale, but when the `cancel` is clicked.

Any Progess Now?

**Comment by itnug987** [comment]
I am not working on this issue. Please make this issue open to everyone @vyankatesh24.

**Comment by Ni3verma** [comment]
@vyankatesh24 
assign it to me

**Comment by vyankatesh24** [comment]
Sure @Ni3verma :+1:
