### ISSUE TITLE
testing: Write unit tests for the user input validator(isInputValid) in PDFUtils

### ISSUE THREAD

**Issue by srv-twry** [Swati4star/Images-to-PDF#594]
The user input validator named `isInputValid` in PDFUtils is untested. It would be great if unit tests could be added with various test cases in order to test if the method works as expected.

Please write tests for the method with various user input cases.

**Comment by Ni3verma** [comment]
should be done after #603

**Comment by Ni3verma** [comment]
@srv-twry I'll try to do it
