### ISSUE TITLE
Write unit test for calculateFitSize method in ImageUtils

### ISSUE THREAD

**Issue by srv-twry** [Swati4star/Images-to-PDF#598]
The `calculateFitSize` method in ImageUtils is untested. It would be great if unit tests could be added with various test cases in order to test if the method works as expected.

Please write tests for the method with various input arguments.

**Comment by jddeep** [comment]
@Swati4star @srv-twry I would like to work on it. Can I proceed?

**Comment by jddeep** [comment]
@Swati4star I would take a look at #549 at a little later time. As I am a bit short on time now. The issue #549 remains open btw and if someone other wants can claim it in the mean time. Thank you.

**Comment by Swati4star** [comment]
Sure @jddeep 👍
