### ISSUE TITLE
Add action to Snackbar when PDF is Rotated

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#599]
### Description
When we rotate PDF the Snackbar shows `PDF Created!` but does not show `View` action.
### Steps to reproduce
* View Files
* Click on PDF the dialog will open
* Select Rotate Pages
* Select Angle and Click Ok

### Expected behavior
The snackbar should show  `View` action and on Clicking it the PDF should be Displayed.

### Actual behavior
Snackbar does not show `View` action.

**Comment by Ni3verma** [comment]
I would like to work on it

**Comment by srv-twry** [comment]
I don't have the access to assign you but you can go ahead with the issue and solve it.

**Comment by Ni3verma** [comment]
okay

**Comment by ahmedaboalata** [comment]
can i join

**Comment by Ni3verma** [comment]
@ahmedaboalata I have already made PR of this issue.
