### ISSUE TITLE
Cache is very large

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#6]
itext and TedPicker are generating a huge amount of cache and data in the app as the app starts. Need to figure out something to implement something similar to TedPicker.

**Comment by webnusapp** [comment]
Hello
I'm grateful for help and resolve the errors

**Comment by Swati4star** [comment]
Sure @webnusapp You can work on this.
Let me know...if you need some help

**Comment by Swati4star** [comment]
@webnusapp Are you working on this?

**Comment by mihudevcom** [comment]
@Swati4star I have about 1 MB of cache in the app after creating several pdfs. What cache memory are you refering to?

**Comment by Swati4star** [comment]
Seems like no one is facing this issue. I am gonna close this one.
Thank you @mihudevcom for mentioning. :+1:
