### ISSUE TITLE
Create PDF option can't be seen on creating PDF second time.

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#60]
1. Select few images, create a PDF
2. Click on Select Images. Select Few images, Click on check button.
When you come back to main screen, you can't see create PDF option again. The option should be available.

**Comment by sbhandare3** [comment]
Hello, 
I have created a pull request for this issue. 
Fixed this issue to morph 'Create Pdf' button as Square when coming back after selecting images.
