### ISSUE TITLE
Back button leads to Home Fragment when orange file selector is still open

### ISSUE THREAD

**Issue by Shivamdhuria** [Swati4star/Images-to-PDF#602]
This is more like a UX bug.
<a href="url"><img src="https://user-images.githubusercontent.com/10262897/53904382-efc73900-406b-11e9-9d4c-3cbdbf945b45.gif" align="left" width="300" ></a>

### Steps to reproduce
Go to any fragment such as invert pdf ,remove page etc wherever there's is the orange slider in use.Click on the slider to pull up.Click back button.

### Expected behaviour
Clicking on back button should pull the slider down while remaining on the same fragment.

### Actual behaviour
The back button leads to the Home Fragment.

**Comment by Shivamdhuria** [comment]
Again,This might just be intuitive for me.

**Comment by Swati4star** [comment]
This is a valid issue

**Comment by sidhuparas** [comment]
Would you like to work on this @Shivamdhuria?

**Comment by Shivamdhuria** [comment]
@sidhuparas ,a but busy so no.

**Comment by theabhishekavi** [comment]
@Swati4star @sidhuparas shall i work on this issue?

**Comment by sidhuparas** [comment]
@theabhishekavi Sure, go ahead!
