### ISSUE TITLE
Count of images doesn't update when images removed from 'Rearrange Images' option

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#605]
Count of images doesn't update when images removed from 'Rearrange Images' Enhancement option

### Steps to reproduce
* Images to PDF
* Select Images 
* Select `Rearrange Images` option from More Enhancement options
* Remove some images 
* press `Back`

### Expected behaviour
Count of file ` x images(s) selected` should update which is there at bottom of `ImagesToPDF Fragment` 
### Actual behaviour
Files get removed but count of file ` x images(s) selected` doesn't update

**Comment by ahmedaboalata** [comment]
can i join

**Comment by vyankatesh24** [comment]
@ahmedaboalata 
If you want to work on this issue, you may!

**Comment by SupreethBaliga** [comment]
Is @ahmedaboalata  still working on it? Or can I have a try?

**Comment by Swati4star** [comment]
@ahmedaboalata Are you working on this?

**Comment by SupreethBaliga** [comment]
@Swati4star Can i try this?

**Comment by Swati4star** [comment]
Sure @SupreethBaliga 👍

**Comment by SupreethBaliga** [comment]
Can you tell me the relevant files please?

**Comment by Swati4star** [comment]
You'll have to look through the code & get familiar. If you still face any issue, contact any mentor on slack.

**Comment by SupreethBaliga** [comment]
Ok sure. Thanks.

**Comment by vyankatesh24** [comment]
@SupreethBaliga Any Progress?

**Comment by SupreethBaliga** [comment]
I got familiar with most part of the code. Just not being able to find the part which displays "Images Rearranged" in the snackbar.

**Comment by Swati4star** [comment]
https://github.com/Swati4star/Images-to-PDF/blob/64b1cfeaccacc8a46f663b2db2b667a4dd2832f4/app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java#L380

You can just find the string in the whole project

**Comment by SupreethBaliga** [comment]
Ok thanks. Done.
