### ISSUE TITLE
Bug in Add Images Fragment

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#606]
`Create PDF` button becomes blue but does not get Enabled When Images Added.
`Create PDF` button becomes blue & Enabled after only the File is selected i.e. without adding images.

### Steps to reproduce
* Add Images
* Click on `ADD IMAGES` or `SELECT A FILE`

### Expected behaviour
The process should be in a flow 
* `Select A File` (Already enabled and Blue) others button should Disabled and Gray
* After file selection `Add Images` becomes Enabled and Blue 
* After adding images `Create PDF ` should be Enabled and should become Blue.

### Actual behaviour
`Select A File` and `Add Images` are Enabled and Blue 
`Create PDF` button becomes blue but does not get Enabled When Images Added.
`Create PDF` button becomes blue & Enabled after only the File is selected i.e. without adding images.

**Comment by vyankatesh24** [comment]
@Swati4star Have a look over Expected Behaviour.
Do suggest changes needed if any

**Comment by Swati4star** [comment]
@vyankatesh24 Good finding! The proposed actual behaviour looks good 👍

**Comment by kunalmulwani** [comment]
Anyone working on this issue?

**Comment by Swati4star** [comment]
No. You can @kunalmulwani 

Are you a gssoc participant?

**Comment by kunalmulwani** [comment]
No, I am not. Is it necessary to participate to work on this?

**Comment by Swati4star** [comment]
No no, it's not.
You can work on this issue 👍

**Comment by sidhuparas** [comment]
@kunalmulwani Are you working on this? Any updates?

**Comment by kunalmulwani** [comment]
I haven't started working on this yet.

**Comment by pankajpoply45** [comment]
I want to work on this issue as a gssoc participant. @sidhuparas  @Swati4star

**Comment by sidhuparas** [comment]
@kunalmulwani Please clear your stand if you really want to work on this. It's been a week and you haven't started. If you're not willing to work, @pankajpoply45 can be given a chance.

**Comment by kunalmulwani** [comment]
I am sorry. Please assign it to someone if they are available.

**Comment by Swati4star** [comment]
@pankajpoply45 You can start working on this issue

**Comment by pankajpoply45** [comment]
I think the issue has been resolved in updated version of the app. If not please elaborate it. @sidhuparas  @Swati4star

**Comment by theabhishekavi** [comment]
@pankajpoply45 are you working on this issue?

**Comment by pankajpoply45** [comment]
#641 please review it @Swati4star @sidhuparas
