### ISSUE TITLE
Add an option to create password protected PDFs

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#61]

**Comment by anandkumarkparmar** [comment]
Hi @Swati4star, is anyone working on this? Can you suggest the flow how do you want this? So, I can start.

**Comment by Swati4star** [comment]
Yeah sure. You can take it up. I'll share the flow soon. Can you search, how will you create password protected PDF by the time.

**Comment by anandkumarkparmar** [comment]
Yes, I have searched already. 

Please refer this: 
https://viralpatel.net/blogs/password-protect-pdf-itext-java/

**Comment by Swati4star** [comment]
Perfect.
So, the UI I have in mind is:
We can add this as similar to the 'image enhancement options'.
Right now, you can just add a button 'Add password to the PDF', which will open up a dialog with the entry for username & password.

The UI might look bad for now. (The 'image enhancement options' -> 'Crop Images' also look a bit weird right now) Just implement this, for now, I'll look some better UI options.
Please suggest if you have something else in mind.

**Comment by anandkumarkparmar** [comment]
My Suggestion:

1. Capture photo 
2. Press the button "Create PDF"
3. Show toggle button with text "Password protected PDF?" on "Creating PDF" dialog 
3.1. If Toggle is yes show one EditText for entering password, then create pdf with password provided.
3.2. Else don't show EditText and create pdf without password protected.

**Comment by Swati4star** [comment]
How does this look like for UI? 

We can add appropriate icons for the options.
![whatsapp image 2018-06-06 at 8 24 47 pm](https://user-images.githubusercontent.com/9164477/41046522-305fd24a-69c8-11e8-9414-e6e5571fa0f6.jpeg)


This will make adding further enhancement options also easier.

**Comment by anandkumarkparmar** [comment]
Looks great.

**Comment by anandkumarkparmar** [comment]
Great 👍

**Comment by Swati4star** [comment]
@anandkumarkparmar Are you working on this now?

**Comment by anandkumarkparmar** [comment]
@Swati4star yes.

**Comment by Swati4star** [comment]
Fixed by #101! Thanks to @anandkumarkparmar 👍
