### ISSUE TITLE
Wrong display of snackbar showing rearrange image 

### ISSUE THREAD

**Issue by theabhishekavi** [Swati4star/Images-to-PDF#613]
Snackbar shows images are rearranged even if they are not rearranged.

### Steps to reproduce
1.Select Images to PDF
2.Select Images
3.Select 2-3 images and click sure
4.Click Rearrange images and just press back button

### Actual behaviour
Snackbar displays images are rearranged although it is not arranged

### Expected behaviour
Message should be displayed only if images are rearranged

### Would you like to work on the issue?
Yes

**Comment by theabhishekavi** [comment]
@Swati4star should i work on this?

**Comment by Swati4star** [comment]
Sure @theabhishekavi
