### ISSUE TITLE
View beneath textview should not be clickable

### ISSUE THREAD

**Issue by theabhishekavi** [Swati4star/Images-to-PDF#615]
When we click a bottom textview the view beneath it is clicked

### Steps to reproduce
1.Open Images to pdf fragment
2.Select images and click sure
3.Now try to click the bottom text view showing number of images selected

### Actual behaviour
The view which is beneath the textview opens

### Expected behaviour
The view which is beneath the textview should not be clicked

### Would you like to work on the issue?
Yes

**Comment by theabhishekavi** [comment]
@Swati4star shall i work on this?

**Comment by theabhishekavi** [comment]
should i include the preview of selected images in onclick of textview or no work should be done on clicking the bottom textview ?

**Comment by Swati4star** [comment]
Nothing should be done on clicking the text views.
