### ISSUE TITLE
Navigation Drawer Items doesn't get highlighted.

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#618]
When we click on any navigation drawer items, Items doesn't get highlighted.

### Steps to reproduce
* Open App
* Navigation Drawer
* Select Any Item (Fragment)

### Expected behaviour
Selected Item should be highlighted.

### Actual behaviour
`Home` remains highlighted always.

**Comment by Ni3verma** [comment]
I'll solve it
