### ISSUE TITLE
[Favourites Menu] Actionbar gets removed

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#619]
Actionbar gets removed when clicked on Favourites menu.

### Steps to reproduce
* Open the App
* Click on Favourite menu.
* Click back(Phone's Button)

### Actual behaviour
There is no Actionbar on Activity after clicking back.

![image](https://user-images.githubusercontent.com/18503975/54089812-17334400-4393-11e9-9ad4-a6d479242a76.png)

### Expected behaviour
Actionbar should be there in Activity.

**Comment by theabhishekavi** [comment]
@vyankatesh24 there are some more issues in this favourite fragment:-
1.favourites items are not clickable
2.if we add favourite folders then again we get favourite button on the actionbar(although we are still in actionbar)
3.Shared peferences is not used properly in showing the favourite list(once we close the fragment all the favourite list are disappeared)
4.View of selecting the favourite folders from the recycler view is not good(although shared preference is used but it is not visible in favourite list)

**Comment by theabhishekavi** [comment]
@vyankatesh24 @Swati4star if you allow i want to solve all the above said issues

**Comment by Swati4star** [comment]
@theabhishekavi You can create a different combined issue for all the things you listed in the above comment. and can start working on it. 👍

**Comment by theabhishekavi** [comment]
Okay, thanks! i have submitted a new issue combining all the issues including issue number #619
