### ISSUE TITLE
New Feature : Merge 2 PDFs

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#62]

**Comment by Swati4star** [comment]
Sure. Go ahead 👍

**Comment by Swati4star** [comment]
- This is kind of a big feature, so adding it on long click in View files menu won't make it easily discoverable. I would suggest adding it somewhere on the home screen only, or adding it as a new option to navigation drawer

- I think, it should be extended to all the PDF files present in the user's device.

**Comment by Swati4star** [comment]
@Sabihashaik 
Add new option in navigation bar only : `Merge PDF`
and change `Home` to 'Create PDF`

**Comment by Sabihashaik** [comment]
@Swati4star Sure.

**Comment by Sabihashaik** [comment]
@Swati4star For the Icon for the Nav Menu which one do you prefer?

![baseline_picture_as_pdf_black_18dp](https://user-images.githubusercontent.com/21033484/42018215-6d2d2a8c-7ac2-11e8-8728-aa3b525d9be8.png)
![baseline_call_merge_black_18dp](https://user-images.githubusercontent.com/21033484/42018435-2a4e7f12-7ac3-11e8-8185-5a7cd36735bd.png)

**Comment by Swati4star** [comment]
The second one looks good. 👍

**Comment by Sabihashaik** [comment]
@Swati4star Hi! I'm still working on this issue, sorry for any delay since I was running into an issue with the PDF File Paths. I managed to get that working though. :)
I'll work on the layout a little bit and send a PR quite soon.
