### ISSUE TITLE
Redesign of the Favourite Menu

### ISSUE THREAD

**Issue by theabhishekavi** [Swati4star/Images-to-PDF#622]
## 1.Onclick folder issue:- 
Favourite folders are not clickable
 ## 2. Action bar issue:-
If we add favourite folders then again we get favourite button on the actionbar (although we are still in actionbar)
## 3. Shared Preference issue:-
Shared peferences is not used properly in showing the favourite list(once we close the fragment all the favourite list are disappeared)
## 4. UI of selecting favourite folders:-
View of selecting the favourite folders from the recycler view is not good(although shared preference is used. But there should be a done button after selecting the checkbox)

### Would you like to work on the issue?
Yes

**Comment by Swati4star** [comment]
Go ahead with this 👍

**Comment by sidhuparas** [comment]
@Swati4star It can be closed now.

**Comment by theabhishekavi** [comment]
@sidhuparas  i am still working on this.

**Comment by sidhuparas** [comment]
@theabhishekavi Oops... I picked wrong one. Fine, continue with it.

**Comment by theabhishekavi** [comment]
@sidhuparas i will try to solve this issue asap.
