### ISSUE TITLE
'Get Started' Button Opens 'ImagesToPDF' Fragment

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#626]
Earlier the `ImagesToPDF` fragment was the main fragment.
Now in a new design `HomeFragment` is the main fragment.

### Steps to reproduce
* Open `View Files` or `History Fragment`
* To see `Get Started` button you will delete all files/history.
* Click `Get Started`

### Expected behaviour
`HomeFragment` should open on `Get Started` Click

### Actual behaviour
`ImagesToPDF` opens up on `Get Started` Click

**Comment by piedcipher** [comment]
I would like to work on this issue @vyankatesh24
