### ISSUE TITLE
Add Font Colour Enhancement Option in Text to PDF fragment

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#629]
### What to do?
Add Font Colour Enhancement Option in Text to PDF fragment.

* Add New Enhancement Option
* Open colour chooser dialog on click
* Set the selected colour as Font colour for pdf.
* Add a checkbox `Set as default` also in the dialog.
* Set selected colour as default when `checkbox` is checked.
* Colour should be `Black` by default.

**Comment by Ni3verma** [comment]
@vyankatesh24 do we have a color chooser dialog somewhere else in app?

**Comment by vyankatesh24** [comment]
Yes in Add Watermark

**Comment by Ni3verma** [comment]
Okay. I'll start to work on this once my existing PR is merged
