### ISSUE TITLE
AppBar doesn't show name of current activity/fragment

### ISSUE THREAD

**Issue by bharatmk257** [Swati4star/Images-to-PDF#630]
how user will know which option he has selected
suppose user has selected Add Password option and user will redirected to the activity/fragment
but on the AppBar it should show name of fragment

### Steps to reproduce
if user has selected Add Password option and user will redirected to the activity/fragment

### Expected behaviour
Name of current fragment should be in AppBar, because user can know what is the purpose of current screen

### Actual behaviour
![20190317_133233](https://user-images.githubusercontent.com/37737418/54487261-f0f13500-48b9-11e9-9140-980b50230f3b.gif)

### Would you like to work on the issue?
Yes

**Comment by sidhuparas** [comment]
Sure @bharatmk257, you can start the work!

**Comment by bharatmk257** [comment]
ok

**Comment by vyankatesh24** [comment]
@bharatmk257 Are you a GSSoC participant?

**Comment by bharatmk257** [comment]
Yes
