### ISSUE TITLE
[View Files] Checkboxes get unchecked when scrolled

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#631]
### Steps to reproduce

![2019_03_17_17_23_36_trim](https://user-images.githubusercontent.com/18503975/54490266-653bd080-48da-11e9-8aa9-a5c8ed1ed512.gif)

### Expected behaviour
Files should remain selected even after scroll.

**Comment by piedcipher** [comment]
I would like to work on this issue. I'm a GSSoC 19 Participant. 
Slack Display Name - `tirth[P]`

**Comment by sidhuparas** [comment]
@piedcipher Go ahead!
