### ISSUE TITLE
Bug in Filter Images screen

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#635]
### Steps to reproduce
* Images to PDF
* Select Images
* Open Filter Images
* Apply any filter
* Click Reset
* Click Next/Previous

### Expected behaviour
On  Next/Previous Click
* Snackbar should not be displayed if `reset` is clicked after changes
* Next/Previous image should be displayed.

### Actual behaviour
Snackbar opens with message "Save current image first"

**Comment by pankajpoply45** [comment]
Can I work on this issue as a gssoc participant.?
@Swati4star @sidhuparas @vyankatesh24

**Comment by sidhuparas** [comment]
Yes sure @pankajpoply45, go ahead!

**Comment by pankajpoply45** [comment]
#641 Done with solving issue please  review it. @sidhuparas  @vyankatesh24  @Swati4star
