### ISSUE TITLE
Don't show delete all alert when no image is selected

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#64]
1. Go to view files
2. Don't select any PDF
3. Click on Delete button
4. An alert shows up, "Do you want to delete all selected files"
Instead, show a toast message that no PDF is selected

**Comment by eXeeLD** [comment]
Can i work on it ?

**Comment by Swati4star** [comment]
@eXeeLD Sure! You can work on this one.

**Comment by Swati4star** [comment]
Thanks to @eXeeLD !!
