### ISSUE TITLE
UI/UX Enhancements

### ISSUE THREAD

**Issue by marwahmanbir** [Swati4star/Images-to-PDF#642]
Various elements can be redesigned throughout the app interface to enhance the look and feel of the app. The following elements can be tweaked/added:
  - Button layout
  - On-click effect/feedback
  - Padding and margin across various activities
  - Splash screen, and more.

### Would you like to work on the issue?
Yes, I'll work on this issue.

**Comment by sidhuparas** [comment]
That's a lot of work in a single issue without even having a concept of redesign. @Swati4star New design elements can be thought one by one.

**Comment by marwahmanbir** [comment]
Sure, I can break down this issue into multiple ones.

**Comment by Swati4star** [comment]
The description is kind of vague. We can discuss more in this issue, like, what exactly do you wish in each enhancement.

**Comment by marwahmanbir** [comment]
To begin, I'm planning to make a splash screen that shows the app's logo and name for 2-3 seconds and then reverts to the main activity. I would require the app logo for that.

In the QR & Barcodes activity, there's some extra margin below the action bar that can be removed. 
![Screenshot_20190321-195707__01](https://user-images.githubusercontent.com/22788214/54759785-cafac600-4c14-11e9-95c8-f388e4fbaac0.jpg)

Similarly, in a few activities, the width of buttons do not match each other and the spacing between buttons is a bit inconsistent. For example in Add and Remove Password activities.
![Screenshot_20190321-195933__01](https://user-images.githubusercontent.com/22788214/54759835-e1088680-4c14-11e9-9d9c-ea688d0f928d.jpg)


Also, we can add flat rounded corner buttons in place of default buttons.
![Screenshot_20190321-195553__01](https://user-images.githubusercontent.com/22788214/54759853-eb2a8500-4c14-11e9-83d8-b06e6f0e22a5.jpg)

**Comment by piedcipher** [comment]
@marwahmanbir Why 2-3 seconds for a splash screen? Also can you tell us that why do we need a splash screen here? There should be some purpose behind having one, we just can't have splash screen for showing app logo. That's just bad UX, it wastes user's time. Checkout [this](https://android.jlelse.eu/right-way-to-create-splash-screen-on-android-e7f1709ba154) article.

**Comment by marwahmanbir** [comment]
@piedcipher I agree that the splash screen will take precious 2-3 seconds of user, but many apps, including apps by Google (e.g. Crowdsource) use a splash screen on app launch just as an eye-candy or an additional form of advertising. No worries, if you don't want one.

**Comment by bharatmk257** [comment]
if you want to change design do let me know I am graphics designer
