### ISSUE TITLE
feedback dialog "never" button doen't do it's work

### ISSUE THREAD

**Issue by Ni3verma** [Swati4star/Images-to-PDF#644]
feedback dialog opens up after every 15 app launches. we have "never" button there so that we are **never** asked to rate the app. however if we click on never button then this dialog will still appear on next 15th app launch. This is clearly a bug.

### Steps to reproduce

- clear the app data
- open it, click on never button on rate us dialog
- open and close app 15 times :sweat_smile: 
- dialog will still appear

### Expected behaviour
rate us dialog shouldn't appear if user clicks on **never**

### Actual behaviour
rate us dialog appear every 15th app launch

### Would you like to work on the issue?
yes

**Comment by Swati4star** [comment]
Sure. You can start working on it!
Good finding :)
