### ISSUE TITLE
prev button error in edit images

### ISSUE THREAD

**Issue by Ni3verma** [Swati4star/Images-to-PDF#647]
In edit images, prev button doesn't function properly

### Steps to reproduce

- open images to PDF
- select 5-6 images
- In enhancement options, select **edit images**
- click on prev image button at bottom right corner
- do it 2-3 times
- now click on next image button. It won't work for 2-3 clicks

### Expected behaviour
when we are on first image, then either prev button shouln't do anything or it should wrap around back to last image

### Would you like to work on the issue?
yes

**Comment by Ni3verma** [comment]
I think that on click of prev button, if we are on first image, then nothing should happen

**Comment by vyankatesh24** [comment]
@Ni3verma Start working on it.
Good Finding :+1: 

Expected behaviour
it should wrap around back to last image
