### ISSUE TITLE
PermissionsUtils Class

### ISSUE THREAD

**Issue by sidhuparas** [Swati4star/Images-to-PDF#652]
A new class is required to handle Permissions related code. In many places, permissions code is duplicated.

### Requirements
- Make at least two `static` functions. One to check if permissions are granted and one to ask for permissions
- Remove duplicate code and directly use utils class' code at all instances
- Function asking for permission should have argument(s) so as to specify which permissions have to be asked for (1, 2 or more). Check `getRuntimePermissions()` function of `MainActivity` class for more information. Also see how a function can take variable number of arguments.

### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by jddeep** [comment]
@Swati4star @sidhuparas I would like to work on this. Please give some tags to this issue.

**Comment by sidhuparas** [comment]
@jddeep Aren't you working on multiple issues at the same time?

**Comment by jddeep** [comment]
@sidhuparas I have already resolved #164 in the form of #648 . It is waiting to get merged.

**Comment by jddeep** [comment]
@sidhuparas Please confirm me should I proceed?

**Comment by sidhuparas** [comment]
@jddeep Go ahead!

**Comment by piedcipher** [comment]
Just a suggestion, we can use [Dexter](https://github.com/Karumi/Dexter) library for Runtime Permissions.

**Comment by sidhuparas** [comment]
@Swati4star Should we go for basic permissions implementation or should we use `Dexter` library as @piedcipher suggested?

**Comment by Swati4star** [comment]
@sidhuparas @piedcipher We should go for our implementation only. There is no added benefit of using Dexter, apart from easy-to-implement
