### ISSUE TITLE
[Edit Images] Few UI Changes

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#653]
Few UI changes in Edit Images option of ImagesToPDF Fragment

### Changes to be done
* Increase size of `prev` and `next` buttons
* Remove left and right margin of `Rotate` and `Save Current` button 
* Change text `Crop Image No. i` to `Crop Image i of n`
* Remove Toast `Images Sucessfully Croped` as Snackbar is there with same message.

**Comment by piedcipher** [comment]
I would like to work on this. I'm GSSoC 19 Participant. Slack Display name - `tirth[P]`

**Comment by vyankatesh24** [comment]
Sure @piedcipher :+1:
