### ISSUE TITLE
Add Page Colour Enhancement Option in Text to PDF and Images To PDF fragment.

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#654]
## What to do?

* Add New Enhancement Option
* Open colour chooser dialog on click
* Set the selected colour as Page colour for pdf.
* Add a checkbox `Set as default` also in the dialog.
* Set selected colour as default when `checkbox` is checked.
* Colour should be `White` by default.

## Reference
https://stackoverflow.com/questions/30206160/how-can-i-add-page-background-color-of-pdf-using-itext-in-java

**Comment by Ni3verma** [comment]
I'll do it
