### ISSUE TITLE
[Favourites] Show Lottie Animation when there are no favourite items

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#659]
### Changes to be done
* Change FAB `+` icon colour to white.
* When there aren't any favourite items show following Lottie animation.
      https://lottiefiles.com/347-like
* Change animation's colour from Red to App's Theme using Lottie Editor

**Comment by piedcipher** [comment]
I would like to work on this issue. I'm GSSoC 19 Participant. 

Slack Display Name - `tirh[P]`

**Comment by sidhuparas** [comment]
Sure, @piedcipher!
