### ISSUE TITLE
Demo apk is continuously getting crash

### ISSUE THREAD

**Issue by patelrohan22** [Swati4star/Images-to-PDF#66]
Demo apk getting crashed on each opening

**Comment by Swati4star** [comment]
Thanks for reporting the issue!

You can download the app from playstore. I will update the demo apk link.

**Comment by Swati4star** [comment]
I'll be removing the sample-apk link, as we already have playstore link for the folks who wish to download the app. There is no need of updating the sample-apk link.

**Comment by patelrohan22** [comment]
Thanks for quick update. In  our project, we are going to add feature which
allows user to create pdf from selected images. During going through your
project I noticed that you have used "

'com.itextpdf:itextg:5.5.9' library."

I have following queries can you please can help out.

1. Is itext library paid?

2. Any alternate free pdf creator lib. which works same as iText?

3. What is the subscription cost?

4. Do we need to compress images?

5. If i create pdf of large size images, is lib throw Out of Memory error?


Please give your answer on above queries. I appreciate your efforts.

**Comment by Swati4star** [comment]
You should first checkout this link : https://developers.itextpdf.com/itextg-android
