### ISSUE TITLE
bug in text to pdf "create PDF" button

### ISSUE THREAD

**Issue by Ni3verma** [Swati4star/Images-to-PDF#662]
create PDF button won't work when you click on it the first time

### Steps to reproduce

- open TEXT to PDF fragment
- select a text file
- now click on create PDF
- **nothing will happen**
- click on it again and then name of new file will be asked

### Expected behaviour
create pdf dilaog where we enter the file name should be opened when we click on **create PDF** the first time. but because of some weird reason, it doesn't. I still need to figure out why

### Would you like to work on the issue?
yes

**Comment by Ni3verma** [comment]
@Swati4star should I start to work on this?
also add appropriate labels

**Comment by vyankatesh24** [comment]
> @Swati4star should I start to work on this?
> also add appropriate labels

@Ni3verma 
Good Finding :+1: 
You may start working on it.
