### ISSUE TITLE
Bug in Reorder Pages

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#663]
### Steps to reproduce
* Reorder Pages
* Select PDF
* Click `Create PDF`
* Click `back` (New File gets created even if we don't change the order of pages.)
* Select New File using `Bottom Sheet`. (`View PDF` button remains visible after selecting the next pdf.)

### Expected behaviour
* New File shouldn't get created even if we don't change the order of pages.
* `View PDF` should become invisible after selecting next pdf.

### Actual behaviour
* New File gets created even if we don't change the order of pages.
* `View PDF` button remains visible after selecting the next pdf.

**Comment by JohnoverBoard** [comment]
Can I work on this issue? Pointers on how to go about would be appreciated

**Comment by sidhuparas** [comment]
@JohnoverBoard Go ahead, it’s easy.

**Comment by vyankatesh24** [comment]
@JohnoverBoard Any progress?

**Comment by JohnoverBoard** [comment]
I was busy last 3 days. Kindly grant me time till 2nd April and I will updatw status

**Comment by rob729** [comment]
@JohnoverBoard Are you still working on this issue?

**Comment by JohnoverBoard** [comment]
Yes I have forked the repo and am trying to work on it. Pardon my slow pace as I am trying to figure out android app development in parallel. I'll do my best to deliver by Friday but if I still delay it would be best for the organisation if someone else took it from Saturday. Please give me last 2 more days chance.

**Comment by JohnoverBoard** [comment]
I am consistently running in to document has password error hence cannot test and see. It would be better if someone else worked on this issue as fixing is taking excessive time. Apologies for the delay. I shall try to be better equipped before volunteering to fix next time

**Comment by rob729** [comment]
@vyankatesh24 PR #686 Solves this issue also.
I have the attach the GIF below for the same.
![2xutxm](https://user-images.githubusercontent.com/31350501/55646742-992f5500-57f9-11e9-9c32-166128626d5d.gif) ![2xutbd](https://user-images.githubusercontent.com/31350501/55646749-9e8c9f80-57f9-11e9-90ee-c1b774552735.gif)

**Comment by vyankatesh24** [comment]
@rob729 
Yeah, actually the fragments beneath are the same.

**Comment by rob729** [comment]
@vyankatesh24 so will I get the points for solving this issue as well?

**Comment by vyankatesh24** [comment]
> @vyankatesh24 so will I get the points for solving this issue as well?

No!
