### ISSUE TITLE
Navigation Drawer Items doesn't get highlighted.

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#664]
When we open any fragment by clicking any item in favourites, Navigation Drawer Item doesn't get highlighted.

### Steps to reproduce
* Open App
* Favourite
* Click Any Item (Add Items to Favourites if there isn't any)

### Expected behaviour
Opened Item/Fragment should be highlighted in Navigation Drawer.

### Actual behaviour
The `item` remains highlighted which is selected earlier.

**Comment by Ni3verma** [comment]
I will solve it
