### ISSUE TITLE
PermissionsUtils Improvements

### ISSUE THREAD

**Issue by sidhuparas** [Swati4star/Images-to-PDF#669]
A new method is required in `PermissionsUtils` class and some minor refactors are required.

## Bug Fix
After the implementation of `PermissionsUtils` class, `onRequestPermissionsResult()` is not getting executed in Fragment class. There's a workaround though.

- Modify the existing method as:
``` 
public static void requestRuntimePermissions(Object context, List<String> permissions,
                                                 int requestCode) {
        if (context instanceof Activity) {
            ActivityCompat.requestPermissions(((AppCompatActivity) context),
                    permissions.toArray(new String[permissions.size()]), requestCode);
        } else if (context instanceof Fragment) {
            ((Fragment) context).requestPermissions(permissions.toArray(new String[permissions.size()]),
                    requestCode);
        }
    }
```

- Introduce the new method:
```
 private static Context retrieveContext(Object context) {
        if (context instanceof AppCompatActivity)
            return ((AppCompatActivity) context).getApplicationContext();
        else
            return ((Fragment) context).requireActivity();
    }
```
- Use it wherever necessary like this:
`                if ((ContextCompat.checkSelfPermission(retrieveContext(context),...`
- Modify the function arguments as required for `checkRuntimePermissions()` to use `Object` instead of `Activity` as first argument.
- Update Javadoc comments.

## Other Requirements
- Merge `checkRuntimePermissions()` and `requestRuntimePermissions()` methods (latter into former)
- Refactor `checkRuntimePermissions()` to `requestRuntimePermissions()`
- Create a new method `checkRuntimePermissions()` which returns `true` if the permission is granted and `false` if not.
- Modify Javadoc comments as required.
- Use PermissionsUtils in `ZipToPdfFragment` and `TextToPdfFragment`  

If you are confused by above points, read them in order from top to bottom.

### Would you like to work on the issue?
Tell us if you would like to work on this issue

Thanks to @Ni3verma for pointing it out. Since you have pointed it out, you are given a preference if you want to work on this issue.

**Comment by Ni3verma** [comment]
Yes, I'll work on it

**Comment by sidhuparas** [comment]
Sure @Ni3verma, go ahead but have a look at the last new requirement added.

**Comment by Ni3verma** [comment]
@sidhuparas 
there is one more probem, if we use PermissionUtils class then **OnPermissionResults** overloaded method in fragment is not running

**Comment by sidhuparas** [comment]
@Ni3verma That's a big point out. I just checked and found that `onRequestPermissionsResult()` isn't being called in fragment class but when we use `PermissionsUtils`, `onRequestPermissionsResult()` is directly getting called in Activity class. Quick google search revealed it to be an issue with Android.

@Swati4star you should have a look here. Although I was having a look at `PermissionsUtils` PR but I didn't approve it but somehow it got merged. @jddeep Didn't you test this behaviour?

The possible solution seems to be 
```
boolean permissionGranted = PermissionsUtils.checkRuntimePermissions(...);

if (permissionGranted){
  // onRequestPermissionsResult() code here
} else {
   --------
}
```

**Comment by jddeep** [comment]
@sidhuparas I had made all the changes you asked for in that PR and after that it got merged. I thought of testing it in the app itself and in the meantime, you opened this issue as improvements needed. So I shall test it now. Please allow me work on this issue and make all the asked improvements here and test as you mentioned. Thanks

**Comment by Ni3verma** [comment]
@sidhuparas 
yes it's a huge bug. I suggest to revert that whole PR. and moreover according to me it's best to request permission in fragment. we should use permissionUtils to only check whether permission is granted or not. **onRequestPermissionsResult** is a very important callback so requesting permission should be done in fragment itself.

**Comment by sidhuparas** [comment]
@jddeep When we make changes to our app, we test it regularly after changing a thing or two. You made a whole lot of changes and didn't test it even once and considering the fact that PR wasn't merged for 4-5 days at least.

**Comment by sidhuparas** [comment]
@Ni3verma I am also thinking of reverting that PR but let @Swati4star have a look at it to decide what's best.

**Comment by jddeep** [comment]
@sidhuparas @Ni3verma why to revert that PR? It has got all the asked changes that were required by @sidhuparas at that time. I get that the permissions needed to be tested i ln the app but i was not informed/reminded about that. I get that it was probably a mistake from my side. But that is the reason this issue is here. @sidhuparas allow me to work on this. Thanks.

**Comment by jddeep** [comment]
But if it such a desperate measure as of to revert the whole PR you can go ahead with that.

**Comment by Ni3verma** [comment]
@jddeep I am suggesting to revertit because by requesting permission outside the fragment, we are lossing a very important callback. think about a case when we want to execute some piece of code, when user grants permission. or in future if we want to do different thing when user grants storage and different thing when he grants camera permission.

**Comment by jddeep** [comment]
Yes @Ni3verma I completely get what you are saying. Actually while coding the PermUtils class i was focused only on the code. And forgot about the issues in fragments. I will be happy to work on it fixing and testing everything if you have no problem buddy. Cheers!

**Comment by Ni3verma** [comment]
@jddeep what do you mean by **fixing** it? can you work something out and solve the problem that I have written in the previous comment?
only way I can think of it is by requesting and handling permission in fragment itslef. In-short reverting previous PR.

**Comment by jddeep** [comment]
@Ni3verma Yes i might come up with a better solution. Currently i am a bit busy with my internals. I will let you know tomorrow. If not pull the upstream with the PR merged making modifications in the fragments. Hint : There aren't many changes. Android studio is clever and will help you finding with the permission requests in the fragments. This idea was given by @sidhuparas

**Comment by sidhuparas** [comment]
Hi @jddeep and @ni3verma, sorry for the delay as the team members were busy. We've decided to revert the existing PR and undo the changes. As @jddeep has created that PR, kindly revert that PR and also remove the uses of `PermissionsUtils` from other places like `ExcelToPDF`.

**Comment by sidhuparas** [comment]
I looked for a solution and I think I have found a better solution than reverting that PR. I initially assigned this to @Ni3verma so please have a look at updated issue description and comment if you would like to work on it.

**Comment by jddeep** [comment]
@sidhuparas So can you let me work on this?

**Comment by sidhuparas** [comment]
@jddeep Sorry but as the bug is pointed out by @Ni3verma, he will get priority if he wishes to work on this. If he doesn't want to work on this, @jddeep you can then go ahead.

**Comment by Ni3verma** [comment]
@sidhuparas I'll work on it.

**Comment by sidhuparas** [comment]
@ni3verma Go ahead :+1:
