### ISSUE TITLE
Add an action to snackbar to view created PDF in Add Watermark

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#670]
### Description
When we add watermark to PDF the Snackbar shows `Watermark Added` but does not show `View` action.

### Steps to reproduce
* View Files
* Click on PDF the dialog will open
* Select Add Watermark
* Enter text and click `Ok`

### Expected behavior
The snackbar should show  `View` action and on Clicking it the PDF should be Displayed.

### Actual behavior
Snackbar does not show `View` action.

**Comment by piedcipher** [comment]
I would like to work on this issue.

**Comment by vyankatesh24** [comment]
Sure :+1:
