### ISSUE TITLE
Add Watermark not working

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#672]
`Add Watermark` is not working when used explicitly from an option on `Home Fragment` but works when applied while creating PDF in `ImagesToPDF Fragment`. 

### Steps to reproduce 
* Add Watermark
* Select File 
* Choose add watermark option
* Enter text and click Ok

### Expected behaviour
The watermark should be applied

### Actual behaviour
The watermark doesn't get applied

**Comment by rob729** [comment]
@vyankatesh24 Can you help me by telling what should be done to solve this issue?

**Comment by vyankatesh24** [comment]
> @vyankatesh24 Can you help me by telling what should be done to solve this issue?

Actually, I haven't also seen where the problem is.
Can you please try finding where the problem is? If you don't get message here or on slack

**Comment by rob729** [comment]
![](https://media.giphy.com/media/1kTI6cuWF6EzBxjRK6/giphy.gif)
@vyankatesh24

**Comment by vyankatesh24** [comment]
> ![](https://camo.githubusercontent.com/36819a55ad61375c6c9b4a61acbc00489b2e915a/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f316b5449366375574636457a42786a524b362f67697068792e676966)
> @vyankatesh24

Yeah, this is the actual behaviour in an app.
The expected behaviour is watermark should be applied.
