### ISSUE TITLE
Add Rotate Pages option to Navigation Drawer

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#675]
`Rotate Pages` is missing from Navigation Drawer add this option to Navigation Drawer in `Enhance Created PDFs` section.

**Comment by piedcipher** [comment]
I would like to work on this issue. I'm back GSSoC 19 Participant.

Slack Display Name - `tirth[P]`

**Comment by Swati4star** [comment]
sure @piedcipher 👍
