### ISSUE TITLE
[Split PDF] PDF is getting created even when there is one page in PDF

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#678]
In `Split PDF` PDF is getting created even when there is one page in PDF.

### Steps to reproduce
* Open `Split PDF`
* Select PDF (Which has only one page)
* Click `Split PDF` button.

### Actual behaviour
New PDF gets created with by suffixing `_1` to it's name.

### Expected behaviour
New PDF shouldn't be created and some warning message must be displayed

**Comment by piedcipher** [comment]
I would like to work on this issue. I'm a GSSoC 19 Participant.

Slack Display Name - `tirth[P]`

**Comment by vyankatesh24** [comment]
Sure @piedcipher :+1:

**Comment by piedcipher** [comment]
Why it is reopened?

**Comment by vyankatesh24** [comment]
> Why it is reopened?

Will be closed by your new PR.
