### ISSUE TITLE
Crash while rearranging pdfs.

### ISSUE THREAD

**Issue by BismeetSingh** [Swati4star/Images-to-PDF#680]
Crash while rearrranging the pdfs:  java.lang.IndexOutOfBoundsException
RearrangePdfPages.java:124

### Expected behaviour
The pdf should  be rearranged as per user selection.

### Actual behaviour
Crashes sometimes.
![image](https://user-images.githubusercontent.com/13601266/55496295-54ba8280-565c-11e9-993a-c7d191c1f30e.png)

![image](https://user-images.githubusercontent.com/13601266/55568816-11284d00-571e-11e9-93b9-56f0493e5391.png)

**Comment by vyankatesh24** [comment]
@BismeetSingh 
Good Finding :+1: 
Can you please elaborate steps to reproduce?

**Comment by BismeetSingh** [comment]
Unable to find the point of exact occurrence but it has occurred twice.
