### ISSUE TITLE
[Reorder Pages] Input value not accepted for large pdfs.

### ISSUE THREAD

**Issue by BismeetSingh** [Swati4star/Images-to-PDF#682]
I have a pdf  of size 3 mb having around 549 pages. It fails to rearrange the pages. The file is named book.pdf

### Steps to reproduce
A medium sized pdf will do.

### Expected behaviour
Should rearrange.

Input value is not valid error
![image](https://user-images.githubusercontent.com/13601266/55569266-e25ea680-571e-11e9-8c1f-a6ccfb185925.png)

**Comment by vyankatesh24** [comment]
Error `File Name too long` 
Solution: Keep Name as `PreviousName_rearranged.pdf`

**Comment by BismeetSingh** [comment]
I am working on this.

**Comment by vyankatesh24** [comment]
Sure @BismeetSingh :+1:

**Comment by vyankatesh24** [comment]
> Error `File Name too long`
> Solution: Keep Name as `PreviousName_edited.pdf` (No need of adding page no.s)

**Comment by vyankatesh24** [comment]
@BismeetSingh Any progress?

**Comment by vyankatesh24** [comment]
> > Solution: Keep Name as `PreviousName_edited.pdf` (No need of adding page no.s)

The better solution can be: Keep Name as PreviousName_edited.pdf (No need of adding page no.s) only if a name (with page no.s) exceeds certain no.s of characters (say 50).
