### ISSUE TITLE
Warn User when similar Font and Page Color is used.

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#684]
In `Text To PDF` warn the user (using dialog ) when the user selects similar (not only equal) Font and Page Color.

**Comment by piedcipher** [comment]
I would like to work on this issue. I'm a GSSoC 19 Participant.
Slack Display Name - `tirth[P]`

**Comment by piedcipher** [comment]
Can I start working on it?

**Comment by vyankatesh24** [comment]
Sure :+1:

**Comment by piedcipher** [comment]
Can you elaborate a bit on "similar" colors?

**Comment by sidhuparas** [comment]
@piedcipher You can check: [https://i.stack.imgur.com/o6Wdq.png](url)

In short, they should be visibly similar.

**Comment by Swati4star** [comment]
@sidhuparas Can you provide a mathematical formula or something that will decide if 2 colors are visibly similar?

**Comment by sidhuparas** [comment]
@Swati4star Yes sure.

**Comment by vyankatesh24** [comment]
```
One of the best methods to compare two colors by human perception is CIE76. The difference is called Delta-E. When it is less than 1, the human eye can not recognize the difference.

There is wonderful color utilities class ColorUtils (code below), which includes CIE76 comparison methods. It is written by Daniel Strebel,University of Zurich.

From ColorUtils.class I use the method:

static double colorDifference(int r1, int g1, int b1, int r2, int g2, int b2)
```
https://stackoverflow.com/questions/9018016/how-to-compare-two-colors-for-similarity-difference



See if this helps!

**Comment by sidhuparas** [comment]
The method provided above seems good. When I looked at Wikipedia: https://en.wikipedia.org/wiki/Color_difference#CIE76, I found that the returned `double` value should be <= 2.3. Here `2.3` is just noticeable difference.

**Comment by piedcipher** [comment]
Hi! Thank you all for the help but I won't be able to work on this issue. Please make this issue up-for-grabs by anyone.

**Comment by shalishi** [comment]
Hello, I'd like work on this issue. Can I?

**Comment by vyankatesh24** [comment]
@shalishi Sure :+1:

**Comment by shalishi** [comment]
Hello, I just finished this issue. How can I submit my work?

**Comment by Swati4star** [comment]
https://github.com/Swati4star/Images-to-PDF/blob/master/CONTRIBUTING.md#6-make-a-pull-request

**Comment by shalishi** [comment]
@Swati4star hello, I got a permission problem when i want to push my new branch. I don't have permission to access your projet yet. Could you check that, please?

**Comment by Swati4star** [comment]
Please google, "how to create a Pull Request", and if you still have issues, connect with a mentor on slack

**Comment by shalishi** [comment]
It was not a problem of pull request itseilf. Bbefore do a pull request I have to public my branche, right? But I could't do it because i have no permission. I totally follow the guide page that you showed me nefore

**Comment by Swati4star** [comment]
please connect on slack. let's not spam the issue with contribution related problems.

**Comment by shalishi** [comment]
OK. I have to creat a accout firstly. How can I find you guys on slack,
with a team name?

**Comment by Swati4star** [comment]
Are you not a gssoc participant? (if not, we can have a discussion over mail : swati4star@gmail.com)
Also, there shouldnt be any need for you to have permission to access my repo.
You are supposed to fork this repo, push the commit there & create a Pull request

**Comment by shalishi** [comment]
it's done. Thank you for your help
