### ISSUE TITLE
Update screenshots in Welcome Activity

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#692]
### What to do?
* Add Fragment for `Excel to PDF` Feature.
* Update screenshots on the available fragments (most of them are older)
* Use same device image, for all screenshot to embed into (It is different for some now).

**Comment by jddeep** [comment]
@vyankatesh24 I would like to do this.

**Comment by Swati4star** [comment]
Go ahead @jddeep
