### ISSUE TITLE
Add ExcelToPDF in Favourites

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#693]
### Steps to reproduce
* Open App
* Click Favourite Menu in ActionBar
* Click FAB
* There isn't `ExcelToPDF` option in an opened screen.

### What to do?
* Add option in favourites
* Also, Title should change when opened an `ExcelToPDF` fragment through Favourites.

**Comment by rob729** [comment]
@vyankatesh24 I want to work on this issue.

**Comment by vyankatesh24** [comment]
Sure @rob729
