### ISSUE TITLE
Actionbar title is not changing when Excel to PDF option is clicked

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#694]
Title is not changing when opened an `ExcelToPDF` fragment through navigation drawer or Home Fragment.

### Steps to reproduce
* Open an `ExcelToPDF` fragment through navigation drawer or Home Fragment.

### Expected behaviour
* Title should change.

### Actual behaviour
* The title does not change.

**Comment by rob729** [comment]
@vyankatesh24 I would like to work on this issue.

**Comment by vyankatesh24** [comment]
Sure :+1:
