### ISSUE TITLE
Add more information on favourites page

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#698]
<img width="352" alt="Screenshot 2019-04-11 at 3 29 48 PM" src="https://user-images.githubusercontent.com/9164477/55948697-b7200e00-5c6e-11e9-932a-b5b78afef858.png">

### Steps to reproduce
Select heart icon on title bar (on top right)

### Expected behaviour
Add a message below the animation "Select + icon to add your favourite features!"

**Comment by rob729** [comment]
@Swati4star @vyankatesh24 I would like to work on this issue.

**Comment by sidhuparas** [comment]
Sure @rob729

**Comment by Swati4star** [comment]
@rob729 You have commented on https://github.com/Swati4star/Images-to-PDF/issues/694 also. Take up only one at a time. Finish first one before & then work on this

**Comment by rob729** [comment]
@Swati4star I have made a PR for issue #694.

**Comment by vyankatesh24** [comment]
As PR #699 for issue #694 got merged, you may start working on this now :+1:
