### ISSUE TITLE
6.0 Force stop problem

### ISSUE THREAD

**Issue by pharidali** [Swati4star/Images-to-PDF#7]
Hello.

6.0 android force stop problem.

**Comment by Swati4star** [comment]
@pharidali How exactly are you facing the problem?
I tested it on android 6.0
Can you post logs or screenshot ?

**Comment by pharidali** [comment]
![screenshot_20170312-211104](https://cloud.githubusercontent.com/assets/24604834/23833100/1f68d530-0769-11e7-97e4-37875a8f1f77.png)

**Comment by pharidali** [comment]
????

**Comment by Swati4star** [comment]
Did you download the app from fdroid?

**Comment by pharidali** [comment]
Yes.
Fdroid Also Same problem..
And App-debug also Same Problem.

**Comment by Swati4star** [comment]
Hi. Please see the apk on this link
https://dl.dropboxusercontent.com/s/ugpju98f0y2t947/app-debug.apk

I have resolved the issue.
Thanks for noticing :+1:
