### ISSUE TITLE
[Images to PDF] Add Set as Default option in Show page numbers

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#702]
### Steps to reproduce
* Open app 
* Create PDF
* Select Images
* Show page numbers (a dialog will open)

### What to do?
 * Add a checkbox at the bottom: `Set as default`
 * If that checkbox is checked, set the currently selected option as a default option.

**Comment by jeannewangxin** [comment]
Hello,I'll work on this issue.Thanks.

**Comment by vyankatesh24** [comment]
Sure :+1: @jeannewangxin

**Comment by jeannewangxin** [comment]
> Sure 👍 @jeannewangxin

I have a problem:
if I have set the default option in show page numbers, where can I preserve the currently option.In DataBase?

**Comment by vyankatesh24** [comment]
> > Sure +1 @jeannewangxin
> 
> I have a problem:
> if I have set the default option in show page numbers, where can I preserve the currently option.In DataBase?

Use shared preferences.

**Comment by jeannewangxin** [comment]
> shared preferences.

OK,thanks

**Comment by jeannewangxin** [comment]
Hello,I have finished the task, can you create a new branch, and I can make a push.Or if you have other method, please tell me, thanks

**Comment by Swati4star** [comment]
https://github.com/Swati4star/Images-to-PDF/blob/master/CONTRIBUTING.md#6-make-a-pull-request
