### ISSUE TITLE
Addition of pdf editor

### ISSUE THREAD

**Issue by peerzadaaabid** [Swati4star/Images-to-PDF#703]
Describe your issue here.

Hi 
I find the app quite interesting as it has the ability to play with pdf files. The thing I noticed is that this app is unable to edit the pdf. So I want to suggest that app should be able to edit pdf files  too.
Moreover I will provide a proposal description if you want it to implement.

**Comment by Swati4star** [comment]
We dont have any library which can do this directly.
If you have that, I'll be happy to continue ahead with this feature implementation.
