### ISSUE TITLE
Suggest new Ui/UX for "Whats new" dialog

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#704]
### Steps to reproduce
- update the app & whats new dialog will be shown

<img width="418" alt="Screenshot 2019-04-15 at 4 36 26 PM" src="https://user-images.githubusercontent.com/9164477/56128217-a9cf9000-5f9c-11e9-80aa-dfda2a5b5229.png">

**Comment by jddeep** [comment]
@Swati4star What kind of UX/UI you want for the Dialog? Like the current dialog looks fair and matches the theme of the App.

**Comment by jddeep** [comment]
@Swati4star @vyankatesh24 Please discuss so that I can move forward.

**Comment by Swati4star** [comment]
The current dialogue looks okayish only. If you have some suggestions for the dialogue, you can share.
This issue is for suggestions only. If I have had a UI in mind, I would have created an issue for implementing that,

**Comment by jddeep** [comment]
@Swati4star How I about a sliding Dialog? With a cool UI. Like users can swipe through the new updates knowing more details about them OR could just `continue`

**Comment by Swati4star** [comment]
It'll be better if you share screenshots or some type of mock up design

**Comment by jddeep** [comment]
![Screenshot (193)](https://user-images.githubusercontent.com/43133646/56302279-0c6c8b80-6157-11e9-9830-d18a0376447c.png)

@Swati4star Please have a look. The right arrow is there to indicate that this can be slid across.

**Comment by jddeep** [comment]
[ImageToPdfDialog.zip](https://github.com/Swati4star/Images-to-PDF/files/3090462/ImageToPdfDialog.zip)

@Swati4star For a better quality of my design you can check the actual prototype. Thanks.

**Comment by jddeep** [comment]
@Swati4star Any Feedback?

**Comment by Swati4star** [comment]
Need a few more suggestions. These doesnt look that good

**Comment by jddeep** [comment]
@Swati4star Do you want a more minimal design? Like do you think this is to "colory"?

**Comment by jddeep** [comment]
@Swati4star You didn't tell anything?
