### ISSUE TITLE
 v8.6.4 freezes while converting from Excel to pdf

### ISSUE THREAD

**Issue by realrufans** [Swati4star/Images-to-PDF#707]
#### Expected behavior
I excepted th Excel to Pdf tool to succefully convert excel file without freezing the device.

#### Actual behavior
PDF Converter v8.6.3 freezes the device, and crashed the device. While v8.6.4 only freezes the device during conversion.

#### How to reproduce
- Lunch PDF Converter v8.6.3, or v8.6.4
- locate excel to pdf tool
- select the execel file that is needed to be converted
- click on excel to pdf, and set the file name
- click on okay, and watch it freeze. (v8.6.3 crashes, v8.6.4 freezes during the conversion process, then back to normal after converting)

* Browser/App version:
Android 8.1

**Comment by realrufans** [comment]
I would have provided a crash logcat for v8.6.3 but i decided not to. Because there's v8.6.4 already and it doesn't crash, it freezes only.

**Comment by jddeep** [comment]
@Swati4star I would like to work on this. Can I?

**Comment by Swati4star** [comment]
sure @jddeep
