### ISSUE TITLE
The ExcelToPdf needs to be clicked twice.

### ISSUE THREAD

**Issue by jddeep** [Swati4star/Images-to-PDF#709]
Describe your issue here.
The ExcelToPdf needs to be clicked twice.

### Steps to reproduce
Go to Excel to PDF.
Select a excel file.
The Excel to PDf button needs to be clicked twice before anything happens.
### Expected behaviour
It should work at once.

### Would you like to work on the issue?
Yes.

**Comment by jddeep** [comment]
@Swati4star Please provide difficulty tags. I would work on this.

**Comment by Swati4star** [comment]
@jddeep Are you working on this?

**Comment by jddeep** [comment]
Yes will make a PR soon.
