### ISSUE TITLE
[History] Add entry for excel to PDF creation.

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#713]
Add entry as operation type `Created` when PDF is created using `Excel To PDF` option.

**Comment by vyankatesh24** [comment]
@archi14
Are you interested to work on this issue?

**Comment by archi14** [comment]
@vyankatesh24 I would like to work on this.

**Comment by vyankatesh24** [comment]
Sure @archi14 :+1:

**Comment by Swati4star** [comment]
@archi14 Work on this one first
