### ISSUE TITLE
Improve the checkRangeValidity method of PDF Utils

### ISSUE THREAD

**Issue by srv-twry** [Swati4star/Images-to-PDF#716]
The `checkRangeValidity` method of `PDFUtils` can be improved a bit according to the suggestions by Code climate.

[https://github.com/Swati4star/Images-to-PDF/blob/9a613a3784f2e9b7a8940ef52b78afb4d6f670cc/app/src/main/java/swati4star/createpdf/util/PDFUtils.java#L656](https://github.com/Swati4star/Images-to-PDF/blob/9a613a3784f2e9b7a8940ef52b78afb4d6f670cc/app/src/main/java/swati4star/createpdf/util/PDFUtils.java#L656) 

## Expected outcome
Code climate complains about too many return statements. Please use a variable called `returnValue` and instead of return statements assign that value to this variable. Simply return this variable in the end.

**Note: This issue is for absolute beginners(Less than 2 PRs).**

**Comment by py93** [comment]
@srv-twry Hi, could you please assign me this issue if it's available?

**Comment by vyankatesh24** [comment]
Sure @py93 :+1:
