### ISSUE TITLE
Add `More enhancement options` in `Excel to PDF` : Password protect

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#720]
### Steps to reproduce
- open `Excel to PDF` using navigation drawer/home page

### Expected behaviour
- Add `More enhancement options` section (similar to Merge PDF)
- Add option to create password protected PDF

**Comment by rob729** [comment]
@Swati4star I would like to work on this issue.

**Comment by Swati4star** [comment]
sure @rob729 👍

**Comment by rob729** [comment]
@Swati4star I am trying to convert excel file to PDF but the app is showing "Error occured'.
So, what should I do?

**Comment by Swati4star** [comment]
It would be nice if you could debug it. I can't say what exactly is the issue. mPath could be turning out to be null

**Comment by vyankatesh24** [comment]
> @Swati4star I am trying to convert excel file to PDF but the app is showing "Error occured'.
> So, what should I do?

@rob729 
Mostly the issue will be with the path conversion from URI.

**Comment by rob729** [comment]
@vyankatesh24 so how should I solve this issue?

**Comment by vyankatesh24** [comment]
> @vyankatesh24 so how should I solve this issue?

Maybe you create a new issue for it. by stating the URI in the issue description. and solve that.
or just create an issue and use path directly for testing purpose.

**Comment by vyankatesh24** [comment]
@rob729 Any updates?

**Comment by rob729** [comment]
@vyankatesh24 Actually I was quite busy for the past 2-3 days so I was not able to devote time to this issue.
Please give me 2-3 days more to work on this issue.
