### ISSUE TITLE
Add `show page numbers` in `Settings` section

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#722]
Add the option added in https://github.com/Swati4star/Images-to-PDF/issues/702 to settings section also

**Comment by jddeep** [comment]
@Swati4star I would like to work on this.

**Comment by sidhuparas** [comment]
@jddeep Try to claim one issue at a time. I have assigned you the other one.

**Comment by jddeep** [comment]
@Swati4star Updated my PR for the other issue. Please have a look there, so I can start working on this, Thanks.

**Comment by Swati4star** [comment]
@jddeep you are still commenting on multiple issues at a time!

**Comment by jddeep** [comment]
@Swati4star I am very sorry. I forgot to keep track. I thought this issue would have been taken by somebody.

**Comment by jddeep** [comment]
@Swati4star I would like to keep this issue open. New Developers can work on this. I would work on #729

**Comment by jddeep** [comment]
@Swati4star Is it okay? And be sure I won't be commenting more than 1 issue from now on and keep a track.

**Comment by Swati4star** [comment]
Sure

**Comment by Ni3verma** [comment]
I'll work on it

**Comment by Swati4star** [comment]
sure @Ni3verma
