### ISSUE TITLE
[ PDF CONVERTER  version 8.6.5]  Text to Pdf button is not working properly 

### ISSUE THREAD

**Issue by XAMIR555** [Swati4star/Images-to-PDF#729]
#### Project Information
* Repository    :  https://github.com/Swati4star/Images-to-PDF
* Project Name  :  PDF CONVERTER
* Publisher     : Swati Garg

#### Expected behavior

I Expected that when I use the text to pdf option  in this  application the text document  should be converted into PDF file 

#### Actual behavior

The  Text to Pdf button is not working properly  while i convert the file text to pdf error come  you can see in bug video properly 

#### How to reproduce
* [Download ](https://play.google.com/store/apps/details?id=swati4star.createpdf)letest version and install it 
* open the application and click on Text To PDF  option
* select your text file 
* click on create PDF
* enter the  new file name  
* Note the Bug
* Browser/App version:   8.6.5
* Operating system:  8.0.0

#### Recording Of The Bug
https://youtu.be/3oLsUD_2tXg
#### GitHub Account
https://github.com/XAMIR555

# logcat
[logcat.txt](https://github.com/Swati4star/Images-to-PDF/files/3103498/logcat.txt)

**Comment by jddeep** [comment]
@Swati4star I would like to work on this,

**Comment by Ni3verma** [comment]
@Swati4star I don't think that this issue is present anymore. It was because of wrong implementation of permissionUtils. I have corrected that in my previous pull request so this issue should be automatically solved as app is working perfect now. but still double check it @Swati4star @jddeep @vyankatesh24

**Comment by Swati4star** [comment]
Did you check this @vyankatesh24 ?

**Comment by jddeep** [comment]
@Swati4star the issue here is a little different here than related to permssions which I thought. It was rightly pointed out by @vyankatesh24 . We are working on it.

**Comment by vyankatesh24** [comment]
> Did you check this @vyankatesh24 ?

Yes, checking the log provided. I think this issue is device based not in app. 
What do you think?

**Comment by Swati4star** [comment]
Fixed in latest build
