### ISSUE TITLE
Actionbar Title is not changing when 'Get Started' click.

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#732]
### Steps to reproduce
* Open `View Files` or `History`
* Click `Get Started` Button (delete all files to see the button)

### Expected behaviour
The Action bar title should change.

### Actual behaviour
The Action bar title does not change.

**Comment by NVlad1** [comment]
Hi, I would like to work on this issue. Is it available?

**Comment by vyankatesh24** [comment]
Go ahead @NVlad1 :+1:
