### ISSUE TITLE
Add ZipToPdf in Favourite

### ISSUE THREAD

**Issue by Ni3verma** [Swati4star/Images-to-PDF#734]
No option to add zip to pdf in favourite

### Steps to reproduce
* Open App
* Click Favourite Menu in ActionBar
* Click FAB
* There isn't ZipToPDF option in an opened screen.

### Expected behaviour
There should be a option to add it.

### Would you like to work on the issue?
Yes

**Comment by Swati4star** [comment]
go ahead @Ni3verma
