### ISSUE TITLE
Bug in View Files

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#736]
Count of selected files is not shown every time.

### Steps to reproduce
* View Files
* Select All (count will be shown in action bar)
* Deselect all
* Again Select All (count will not be shown in action bar)

### Expected behaviour
Count of selected files should be shown every time in the action bar.

### Actual behaviour
Count of selected files is not shown every time.

**Comment by jddeep** [comment]
@vyankatesh24 Can I work on this?

**Comment by rob729** [comment]
@vyankatesh24 I would like to work on this issue.

**Comment by vyankatesh24** [comment]
@jddeep 
I have commented on #727 with the error log found on my phone. Have a look.

**Comment by vyankatesh24** [comment]
@rob729 You may start working on it.
