### ISSUE TITLE
Password reset bug in merge pdf

### ISSUE THREAD

**Issue by rob729** [Swati4star/Images-to-PDF#741]
### Describe your issue here.
In Merge PDF option, the password setting is not getting reset after the creation of a pdf.

### Steps to reproduce
![2zllin](https://user-images.githubusercontent.com/31350501/56853046-3a648380-6940-11e9-911a-7ab7df5f48da.gif)

### Expected behaviour
Password setting should reset after PDF creation,

### Actual behaviour
The next PDF will also be password protected by default.

### Would you like to work on the issue?
Yes

**Comment by rob729** [comment]
@Swati4star Please provide difficulty tags. I would work on this.

**Comment by Swati4star** [comment]
go ahead @rob729
