### ISSUE TITLE
Add 'Add Text' option

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#746]
Add `Add Text` option in `Enhance Created PDFs` section.

There should be an option to `Select PDF file`, `Select Text File` and `Create PDF` button.
On clicking `Create PDF` button new PDF should be created by appending the text in a text file to selected PDF.

Maybe this can be useful : [https://www.javamadesoeasy.com/2016/06/how-to-modify-add-text-to-existing-pdf.html](https://www.javamadesoeasy.com/2016/06/how-to-modify-add-text-to-existing-pdf.html)

**Comment by jddeep** [comment]
@vyankatesh24 I will work on it now.

**Comment by vyankatesh24** [comment]
Sure :+1:

**Comment by jddeep** [comment]
@vyankatesh24 This is completely new feature with lots of work, this should have been a `hard` label issue like other new features.

**Comment by vyankatesh24** [comment]
> @vyankatesh24 This is completely new feature with lots of work, this should have been a `hard` label issue like other new features.

There is not 'lots of work'  in this issue. Mostly everything is ready just copy and paste is required.

**Comment by jddeep** [comment]
.

> > @vyankatesh24 This is completely new feature with lots of work, this should have been a `hard` label issue like other new features.
> 
> There is not 'lots of work' in this issue. Mostly everything is ready just copy and paste is required.

Okay @vyankatesh24 Will see then how things workout. 👍
