### ISSUE TITLE
Bug in View Files

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#747]
Bug in the file selection

### Steps to reproduce
* Select Any file 
* Now click `Select All` menu.

### Expected behaviour
All files get selected.

### Actual behaviour
Files get Deselected.

**Comment by archi14** [comment]
@vyankatesh24 please assign this to me.

**Comment by Swati4star** [comment]
Sure @archi14 (if you have not commented on any other open issue currently)

**Comment by archi14** [comment]
Yes working on it.

**Comment by vyankatesh24** [comment]
> Yes working on it.

:+1:

**Comment by vyankatesh24** [comment]
@archi14 
Any updates?

**Comment by Swati4star** [comment]
@archi14 Updates please? the issue is a very small one.
If you are stuck somewhere, let us know.

**Comment by archi14** [comment]
@Swati4star Yes, I am stuck,  still trying to find out the solution.

**Comment by vyankatesh24** [comment]
@archi14  If you need any help, discuss on the slack channel!

**Comment by archi14** [comment]
@vyankatesh24 I am unable to figure out the solution. please assign to someone else.

**Comment by sunnyjain** [comment]
Hi, I would like to solve this issue.

**Comment by vyankatesh24** [comment]
Sure :+1:
