### ISSUE TITLE
Add an option in 'View Files' to sort images by 'size' too

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#75]
Currently, we can sort the file on the basis of date and name only. Add 'size' also an additional option.

**Comment by anandkumarkparmar** [comment]
Can I take this up, @Swati4star ?

**Comment by Swati4star** [comment]
@anandkumarkparmar Yeah sure. Go ahead! 👍

**Comment by anandkumarkparmar** [comment]
@Swati4star Do you want files in increasing order or decreasing order in size?

**Comment by Swati4star** [comment]
![image](https://user-images.githubusercontent.com/9164477/40984564-db9ee304-68ff-11e8-947f-541c1b446209.jpg)
As attached in the screenshot, (see the name ⬆️ ).

Add both options for size:
1. Size ⬆️: increasing order
2. Size ⬇️: decreasing order

**Comment by Swati4star** [comment]
Fixed by 9e47711626c2e660e66866a1c4ededfea6fa4b1b.
Thanks to @anandkumarkparmar 👍

**Comment by anandkumarkparmar** [comment]
@Swati4star Suggest me any other project(s) as well, where I can contribute. Thanks.

**Comment by Swati4star** [comment]
You can start digging into this project: https://github.com/project-travel-mate/Travel-Mate
