### ISSUE TITLE
[Split PDF] PDF gets created even when there is one page in PDF

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#750]
In `Split PDF` PDF is getting created even when there is one page in PDF.

### Steps to reproduce
* Open `Split PDF`
* Select PDF (Which has only one page)
* Click `Split PDF` button.

### Actual behaviour
* New PDF gets created with by suffixing `_1` to its name and only the snackbar is shown `PDF has only one page can't be split...` 

* The snackbar is shown even when there are multiple pages in PDF and we create only one split of it.

### Expected behaviour
New PDF shouldn't be created.

**Comment by rob729** [comment]
@vyankatesh24 I would like to work on this issue.
