### ISSUE TITLE
Bug in Split PDF

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#751]
### Steps to reproduce
* Split PDF 
* Select PDF (encrypted)
* Snackbar shows "PDF is password protected."
* `Create PDF` becomes blue/enabled.

### Expected behaviour
`Create PDF` button should not become blue/enabled.

### Actual behaviour
`Create PDF` button becomes blue/enabled.

**Comment by vyankatesh24** [comment]
@gateway2rohan 
Any progress?

**Comment by gateway2rohan** [comment]
Sorry informing you that I was not well since last few days, so was unable
to look into the issue. I started today only and I'm trying to submit it
ASAP.
