### ISSUE TITLE
Reset Page Colour and Font Colour after PDF Creation.

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#755]
Reset `Page Colour` after PDF Creation in `Images To PDF` fragment.
Reset `Page Colour` and `Font Color` after PDF Creation in `Text To PDF` fragment.

### Steps to reproduce
1. Select images/text file
2. Apply Page Color/ Font Color
3. Create PDF
4. Select images/text file again
5. Don't apply Page Color/ Font Color
6. Create PDF.

### Expected behaviour
The second PDF should get the default Page Color/ Font Color.

### Actual behaviour
The second PDF gets the same Page Color/ Font Color.

**Comment by Swati4star** [comment]
Sure @rob729
