### ISSUE TITLE
[Split PDF] History entry not created properly

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#757]
History entry not created properly.
It gets created in some cases, in some cases, it does not.

**Comment by rob729** [comment]
@vyankatesh24 I would like to work on this issue.

**Comment by vyankatesh24** [comment]
Sure :+1:

**Comment by rob729** [comment]
@vyankatesh24 Can you please tell what should I do to solve this issue as I am not able to understand how to approach this issue?

**Comment by vyankatesh24** [comment]
Are you able to reproduce issue? 

Just add database entry using `DataBaseHelper` class. When PDF(s) is created.

**Comment by rob729** [comment]
@vyankatesh24 sorry for the late reply.
Actually, I am not able to reproduce the error as whenever I am trying to make a PDF it is been mentioned in history.

**Comment by vyankatesh24** [comment]
Try with range `1,2` or something like this, history entry is not created for this.
Check if there are more such cases.

It works for `1-5` like cases.
