### ISSUE TITLE
Bug in Merge PDF in file selection

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#759]
### Steps to reproduce
* Open `Merge PDF`
* Select files using BottomSheet
* Remove Files using `X` icon
* Open Bottom Sheet
* The files which were selected, remain checked 
* Now Uncheck them, They get added in `selected files`

### Expected behaviour
The files which were removed using `X` icon, should be unchecked.

### Actual behaviour
The files which were removed using `X` icon, remain checked.

**Comment by rob729** [comment]
@vyankatesh24 I would like to work on this issue.

**Comment by vyankatesh24** [comment]
Sure :+1:

**Comment by rob729** [comment]
@vyankatesh24 Can you please tell me how to proceed in this issue?
I am not able to find a solution to this issue.

**Comment by vyankatesh24** [comment]
Check for selected files in bottom sheet when opened.
Uncheck the ones which are not in selected files.

**Comment by rob729** [comment]
@vyankatesh24 please remove the 'in progress' tag as I am not working on this issue.

**Comment by wictors** [comment]
Hello. This is my first issue. I would like to try to solve this if it is still open.

**Comment by Swati4star** [comment]
Sure @wictors

**Comment by Swati4star** [comment]
@wictors Any updates here?

**Comment by wictors** [comment]
I have problems. I thought the error was in my devices, but not. I downloaded the current code from GitHub, but I can't run it. There's a error . Check the photo. I cannot run the application via AndroidStudio and debug.

Then I downloaded the application from GooglePlay. It was OK, but the actual behavior is different. I can't reproduce the issue. Check the video. There are different issues.

Some help ? :/

**Link with photos and video :** http://leteckaposta.cz/843572718

**Comment by Swati4star** [comment]
@wictors In which locale are you running this app? I am not able to get the exact issue. 
Instead of sending the photo, can you copy paste the logs here?

**Comment by wictors** [comment]
I am from Slovakia - Central Europe. 
This is complete logs from app. 

[Issue.txt](https://github.com/Swati4star/Images-to-PDF/files/3752798/Issue.txt)

**Comment by Swati4star** [comment]
Please pull the latest code. The crash is now fixed with https://github.com/Swati4star/Images-to-PDF/pull/833

**Comment by Swati4star** [comment]
@wictors Are you still facing this issue?
Any updates here?

**Comment by wictors** [comment]
Yes. I need a week. Maximum. Then I'll close it with the update.

**Comment by Swati4star** [comment]
duplicate of https://github.com/Swati4star/Images-to-PDF/issues/881
