### ISSUE TITLE
[View Files] Wrong Action bar Title

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#763]
After Deleting files ActionBar title resets to `PDF Converter`.

### Steps to reproduce
- View Files
- Select Files
- Delete Files
-  ActionBar title resets to `PDF Converter`.

### Expected behaviour
 `ActionBar` title resets to `View Files`.

### Actual behaviour
 `ActionBar` title resets to `PDF Converter`.

**Comment by sunnyjain** [comment]
Alright, will cover this as I am working in the same file.
