### ISSUE TITLE
Bug in the View Files when the user returns from Favourites to View Files Section.

### ISSUE THREAD

**Issue by sunnyjain** [Swati4star/Images-to-PDF#766]
### Steps to reproduce

- Go in the `View Files`

- Select All Files

- Now click the `Favourites icon` from the toolbar

- Press the Back button.

### Expected behavior
Either all the icons in the toolbar should reset or all files get selected, basically maintaining the state that was left.

### Actual behavior
All the files get Deselected but the icons in the toolbar are unchanged.

### Would you like to work on the issue?
yes.

**Comment by vyankatesh24** [comment]
Good Finding :+1: @sunnyjain 
You may work on this :+1:

**Comment by Swati4star** [comment]
@vyankatesh24 Can you add labels also to this issue?
