### ISSUE TITLE
[Split PDF] Last PDF gets hidden behind Bottom Sheet

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#767]
The last created PDF gets hidden behind Bottom Sheet

As in below image 13th PDF is not getting shown on screen

![image](https://user-images.githubusercontent.com/18503975/58250832-e357a000-7d7f-11e9-9e4f-e729efbdb346.png)

**Comment by rob729** [comment]
@vyankatesh24 I would like to work on this issue.

**Comment by vyankatesh24** [comment]
Sure :+1:

**Comment by rob729** [comment]
@vyankatesh24 will it be ok if I use 'layoutMarginBelow' to push the layout above the bottom sheets as I am not able to find any other alternative solution while using coordinate layout as a parent layout?

**Comment by vyankatesh24** [comment]
> @vyankatesh24 will it be ok if I use 'layoutMarginBelow' to push the layout above the bottom sheets as I am not able to find any other alternative solution while using coordinate layout as a parent layout?

OK :+1:
