### ISSUE TITLE
[View Files] Merge PDF not working

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#769]
### Steps to reproduce
* Open View Files 
* Select Files
* Merge Files menu enables. 
* Click Merge Files 
* Snackbar shows message 'we are unable access PDF....' 

### Expected behaviour
Merge PDF should be created. 

### Actual behaviour
Snackbar shows message 'we are unable access PDF....'

**Comment by rob729** [comment]
@vyankatesh24 I would like to work on this issue.

**Comment by vyankatesh24** [comment]
Sure :+1:
