### ISSUE TITLE
[Add Text] Add Enhancement Option 'Font Size'

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#774]
### What to do?
Add Enhancement Option 'Font Size' in `Add Text` Fragment  (as in Text To PDF)

* Add New Enhancement Option
* Open dialog on click to enter size
* Set the entered size as Font size for pdf.
* Add a checkbox `Set as default` also in the dialog.
* Set selected size as default when `checkbox` is checked.
* If size not entered then default size should be applied.

**Comment by rob729** [comment]
@vyankatesh24 I would like to work on this issue.

**Comment by vyankatesh24** [comment]
Sure :+1:

**Comment by rob729** [comment]
@vyankatesh24 Is it fine if I solve issue #775 in the same PR?
