### ISSUE TITLE
PDF file selection not working for some URIs

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#778]
- PDF file selection not working for some URIs in `Split PDF` and other fragments where PDF selection is required. 
- Error while converting URI to Path.
 - Error:
``` Unknown URI: content://downloads/public_downloads/3798 ```

**Comment by Swati4star** [comment]
Is this just in "split PDF" or somewhere else too?

**Comment by vyankatesh24** [comment]
All fragments where we have to select PDF file(s). Like Merge PDF, Invert PDF, Add Password... etc.

**Comment by ioshomebrew** [comment]
Can you give me a sample URL to work with?

**Comment by Swati4star** [comment]
@ioshomebrew It's already there in issue description.

**Comment by ioshomebrew** [comment]
Ok, looking thru source code now to diag issue

**Comment by ioshomebrew** [comment]
Found the issue, it appears that the RealPathUtil.getRealPath is adding extra data to the selected file

**Comment by ioshomebrew** [comment]
The issue seems to be with some file explorer apps, with EZ File Explorer it didn't work because it added extra characters to the Uri, but with EX File Manager it worked fine

**Comment by Swati4star** [comment]
@vyankatesh24 Are you facing the issue with just EX file explorer or other explorers too?
cc\ @ioshomebrew

**Comment by ioshomebrew** [comment]
I've only tested 2 explorers so far

**Comment by ioshomebrew** [comment]
Just found a potential fix

**Comment by ioshomebrew** [comment]
I added in a feature to replace extra characters with /

**Comment by ioshomebrew** [comment]
It worked with the 2 file explorers I used

**Comment by ioshomebrew** [comment]
The Fix is now on my forked repo

**Comment by Swati4star** [comment]
@ioshomebrew Can you create a PR?

**Comment by ioshomebrew** [comment]
Just did it
