### ISSUE TITLE
[Text To PDF] Suggest Txt/Doc File name as PDF name.

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#779]
When text is selected and the `Create PDF` button has clicked a dialog opens to ask file name.

The UX can be improved with the following functionalities:
- Fill `File Name` textbox on dialog with text/doc file name (can also attach `_pdf`)

- Add an option in `Settings` to enable directly name the PDF as text/doc file name and save. So, now the file name dialog will not appear and directly file will be created with text/doc file name.

**Comment by sudeshim3** [comment]
Is this enhancement open, would love to contribute

**Comment by Swati4star** [comment]
Yes @sudeshim3
This is open. You can pick it up.

**Comment by sudeshim3** [comment]
@vyankatesh24 are you sure about this
 
"_Add an option in Settings to enable directly name the PDF as text/doc file name and save. So, now the file name dialogue will not appear and directly file will be created with text/doc file name._"

Well, I would suggest that we must prompt the file name as it will act as a confirmation note. 
also, it will help them identify quickly if they want to access it in explorer. 

Many Popular application that deals with file conversion prompt auto-filled name before the user takes any action. try some apps like WPS reader they follow this approach.

@Swati4star  what do you think about this ux flow.

**Comment by Swati4star** [comment]
@sudeshim3 I agree. We should prompt the file name. (just like we already do)
The enhancement would be to auto-fill.

**Comment by sudeshim3** [comment]
Text-to-pdf name autofill: 
https://github.com/Swati4star/Images-to-PDF/pull/820
