### ISSUE TITLE
UI enhancement when there are no PDFs

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#78]
When there are no PDFs, it just shows an empty screen with a text message saying 'No PDFs right now'. Enhance this UI.

Few examples of such enhancement is :
<img width="246" alt="screen shot 2018-06-05 at 11 16 29 pm" src="https://user-images.githubusercontent.com/9164477/40993291-d0fd1ce2-6916-11e8-9003-9f69cc78ee44.png">

<img width="251" alt="screen shot 2018-06-05 at 11 16 50 pm" src="https://user-images.githubusercontent.com/9164477/40993292-d12d7ed2-6916-11e8-8847-dc6b83826fe0.png">

Propose a new UI for this empty screen.

**Comment by Sabihashaik** [comment]
Hi! I'd like to work on a few UI Screens :)

**Comment by Swati4star** [comment]
@Sabihashaik Sure. Go ahead. You can post the screen sample here on this thread only.

**Comment by Sabihashaik** [comment]
![proposed](https://user-images.githubusercontent.com/21033484/41812141-48906bcc-772e-11e8-955b-f324c8cb1dbd.png)
![proposed2](https://user-images.githubusercontent.com/21033484/41812147-68037440-772e-11e8-96fb-e11a2ae38e46.png)
I've Attached Proposed UI Screens. @Swati4star

**Comment by Swati4star** [comment]
The screens look really good. @Sabihashaik Great job!!
 I have a few questions & suggestions:
- What will happen when user clicks on 'Get Started now'. That looks a lot like a button.
- Use a lighter version of the orange color.
- Add some space between the circular view & the text after that.

**Comment by Sabihashaik** [comment]
-  Maybe it could be a button to take the users to the main page?<br> I can make it look like normal text if you don't want to put a button on that screen.
- Sure,  made the above mentioned changes.
<img src=https://user-images.githubusercontent.com/21033484/41812308-92f989ac-7731-11e8-8150-6c988e38d857.png width=555px height=800/>

**Comment by Swati4star** [comment]
Yes. Don't make it like a button. 

Change 'No PDFs Yet' to 'No PDFs to show'

**Comment by Swati4star** [comment]
@Sabihashaik A suggestion for the code. Keep all these strings in strings.xml file only. For other locales, you can add the english translation only.

**Comment by Sabihashaik** [comment]
@Swati4star Great! :) 
Do I send a PR with the updated UI Screen?

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/123
Thanks to @Sabihashaik 👍
