### ISSUE TITLE
Wrong paper sizes for DIN A(x) formats in "Set Page Size" dialogue

### ISSUE THREAD

**Issue by just-Nob** [Swati4star/Images-to-PDF#780]
When someone wants to convert a picture into a PDF using "PDF Converter", the paper size can be chosen using the eponymous dialogue "Set Paper Size".
When choosing the bullet point "A0 to A10" (which presumably means the standard paper size formats described e.g. [here](https://en.m.wikipedia.org/wiki/Paper_size)) one can select one of these formats via a drop down menu, whose content is as follows:
- A0 (2384 x 3370)
- A1 (1684 x 2384)
- A2 (1191 x 1684)
- A3 (842 x 1191)
- A4 (595 x 842)
- A5 (420 x 595)
- A6 (297 x 420)
- A7 (210 x 297)
- A8 (148 x 210)
- A9 (105 x 148)
- A10 (73 x 105)

The numbers in brackets probably define the page's dimensions in millimeters (mm).
If the assumptions made so far are correct, the DIN-A-format mismatches the size:
![size chart illustrating the ISO A page size series](https://upload.wikimedia.org/wikipedia/commons/f/f6/A_size_illustration2_with_letter_and_legal.svg)

### Steps to reproduce

1. Select "Images to PDF" in section "Create new PDF".
2. Select one or more images to convert into a PDF.
3. Select "Set Page Size".
4. Open pop up / drop down menu near bullet point "A0 to A10".

### Expected behaviour
The format name should match the correct page size.

### Actual behaviour
Wrong format name (A0, A1, A2...) or wrong page size is displayed (up to now, I haven't checked which one is the correct one, i.e. which one is the one that's being used in the resulting document).

### Would you like to work on the issue?
Unfortunately, currently I neither have the skills, nor the time to work on that issue.
Anyway, I'll try to configure out the "real" page size of the resulting document.

**Comment by laurameck** [comment]
Investigating this, can you assign this to me @Swati4star?
