### ISSUE TITLE
Add "Recently used features" section on home page

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#788]
Add "Recently used features" section on home page

### Expected behaviour
- This should be hidden initially
- When the user starts using the features, add those cards in an LRU manner (maximum 3 cards)
- On clicking these cards, the respective feature should open up.

**Comment by kunalmulwani** [comment]
@Swati4star should this section be persistent or in memory?

**Comment by Swati4star** [comment]
@kunalmulwani It should be persistent.
Using sharedpreferences to store this should work.

**Comment by Swati4star** [comment]
@kunalmulwani Are you interested in working on this issue?

**Comment by kunalmulwani** [comment]
@Swati4star If it is time-bounded then I would want someone with the time guarantee to take over. Although I did try to reuse an existing card which was accessed, I got an error of card being associated with a parent. Do we have a place in code where we have mappings of names and icons for functions stored somewhere which can be reused?

**Comment by Swati4star** [comment]
@kunalmulwani It isn't time bound.
I will be able to help better if you could share the code & error you are facing. You can create a work in progress PR.

**Comment by Swati4star** [comment]
@kunalmulwani Are you working on this?

**Comment by kunalmulwani** [comment]
@Swati4star No. I haven't got a chance. It is free to take over.

**Comment by sunnyjain** [comment]
@Swati4star I would like to work on this issue. But wanted to ask about the UI for the same. Does "Recent Used Feature" on the top "Create new PDF" works?

**Comment by Swati4star** [comment]
@sunnyjain Yes, It should be on top.

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/885
