### ISSUE TITLE
Change delete icon in 'View Files' section

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#79]
The delete icon looks a bit odd.
![list](https://user-images.githubusercontent.com/9164477/40993396-2a12e000-6917-11e8-80ba-ec7777bc547e.jpg)

Change this icon to look more like the 'sort' icon. Sort icon was downloaded from http://www.google.com/design/icons/

You can search for a delete icon also from there only.

**Comment by anandkumarkparmar** [comment]
Hi @Swati4star, How about this icon?

![whatsapp image 2018-06-05 at 23 51 03](https://user-images.githubusercontent.com/20661863/40994968-66785d5a-691b-11e8-9639-252a9775e075.jpeg)

**Comment by Swati4star** [comment]
Fixed!
