### ISSUE TITLE
app:transformDexArchiveWithExternalLibsDexMergerForDebug -> java.lang.OutOfMemoryError 	

### ISSUE THREAD

**Issue by Arsalankhan1212** [Swati4star/Images-to-PDF#790]
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by Swati4star** [comment]
Please add crash logs too.

**Comment by Arsalankhan1212** [comment]
> Please add crash logs too.

![image](https://user-images.githubusercontent.com/53042787/64165357-5c29c600-ce5e-11e9-859e-c1eb684575a5.png)

**Comment by Swati4star** [comment]
This is a build issue. and our build is working perfectly fine.
You can try to google this issue. There must be some changed required in your Android Studio settings
