### ISSUE TITLE
File selection does not work properly

### ISSUE THREAD

**Issue by nu111** [Swati4star/Images-to-PDF#791]
When I select a PDF from the downloads dir of the phone for the remove password feature, the file is not selected and the wrong path is shown, if I put he file in a subdir it works again
Here is a video reproducing the issue 
https://drive.google.com/file/d/10irvh4LMb5tPuex5Fu8lzptTd3Y51_tA/view?usp=drivesdk

**Comment by hector2** [comment]
Hey! I can try to solve this

**Comment by Swati4star** [comment]
Sure @hector2 👍
