### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by darkdragon-001** [Swati4star/Images-to-PDF#792]
[Latest Github release](https://github.com/Swati4star/Images-to-PDF/releases): 8.6.7
[Latest Google Play release](https://play.google.com/store/apps/details?id=swati4star.createpdf): 8.6.9 _(how can this be newer!?)_
[Latest F-Droid release](https://f-droid.org/packages/swati4star.createpdf/): 8.5.6 _(with error [NoSourceSince](https://f-droid.org/wiki/page/Antifeature:NoSourceSince))_

Could you please make sure that versions have the same numbers everywhere and all repositories are up to date?

Thanks!

**Comment by Swati4star** [comment]
I will try to do so from next release on!

**Comment by Swati4star** [comment]
Taking care of this from next release onwards.

**Comment by Swati4star** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/1838

**Comment by amo13** [comment]
As per the link above it looks like this could get resolved very soon

**Comment by Swati4star** [comment]
@amo13 I am busy with my work for some time.
Would you be interested in picking up the issue to fix builds on fdroid?

**Comment by amo13** [comment]
I would love to help and I just took a look at it, but I have not even a clue of what exactly needs to be done here. Never did android development or gradle, but if you think it's not too difficult, maybe you can point me in the right direction?

**Comment by Swati4star** [comment]
@amo13 I am exactly sure on how to fix the build on fdroid.
Based on your previous comment (`it looks like this could get resolved very soon`), I assumed you are aware of the fix.
