### ISSUE TITLE
"Error on creating application folder" when selected circular morphed button.

### ISSUE THREAD

**Issue by sudeshim3** [Swati4star/Images-to-PDF#794]
After the successful conversion of image to pdf selecting the morphed success, button prompts will prompt conversion dialogue which fails with the above error message.

### Steps to reproduce
1. Convert an image to pdf
2. Click the success morphed button

### Expected behaviour
Success button shouldn't respond to user input

### Would you like to work on the issue?
Yes, will work on it, by blocking and unblocking the touch when necessary.

**Comment by Swati4star** [comment]
Great @sudeshim3 👍
