### ISSUE TITLE
Remove Android Lint:Performance warning in ViewFilesFragment.java

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#80]
- Open the project in Android Studio
- Go to Analyze --> Inspect Code.
- We are getting this warning in **Android Lint:Performance**
Do not place Android context classes in static fields; this is a memory leak (and also breaks Instant Run)

<img width="1462" alt="screen shot 2018-06-05 at 11 32 08 pm" src="https://user-images.githubusercontent.com/9164477/40994014-b7331a94-6918-11e8-9eda-e209b2b1fc65.png">

We just can't remove the static from this variable. Figure out a way to solve this.

**Comment by anandkumarkparmar** [comment]
Hi @Swati4star, Can I take this up?

**Comment by Swati4star** [comment]
Sure. Go ahead! 👍

**Comment by Swati4star** [comment]
Fixed 👍
