### ISSUE TITLE
Build Failure: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

### ISSUE THREAD

**Issue by sudeshim3** [Swati4star/Images-to-PDF#805]
Describe your issue here.
After updating the fork from master I am unable to build the project due to DexMerger's failure to merge external libraries

### Steps to reproduce
Clone from GitHub and build on the master branch. If successfully built please post here with android version so that we can narrow down the issue.

### Temporary Fix
Downgrade build tool from 3.4.2 to 3.2.1 in project-level dependencies.

`dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }`

and gradle distribution from gradle-5.1.1 to gardle-4.6

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`

@Swati4star can you clone the repo and build it on your machine. 
This issue is blocking me from pushing updates.

**Comment by sudeshim3** [comment]
![Screenshot 2019-10-08 at 11 56 19 PM](https://user-images.githubusercontent.com/34063388/66423327-16e25080-ea29-11e9-9ef0-ce5ded7cfdb4.png)

**Comment by Swati4star** [comment]
@sudeshim3 I did clone the repo and everything is working fine on my machine.

You can try out the options mentioned in https://stackoverflow.com/questions/49254785/apptransformdexarchivewithexternallibsdexmergerfordebug-in-android-studio-3-0-1

Seems to be some issue with Android studio only.
