### ISSUE TITLE
Replace aspose jar file with gradle

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#806]
Aspose is being used to convert excel to PDF
Currently, we have added a jar file in code https://github.com/Swati4star/Images-to-PDF/tree/a21bd7298a84427fb04fa7ea3a45851771216167/app/libs

### Todo:
Use aspose gradle repo instead:
https://mvnrepository.com/artifact/com.aspose/aspose-cells/18.4

// https://mvnrepository.com/artifact/com.aspose/aspose-cells
compile group: 'com.aspose', name: 'aspose-cells', version: '9.0.0'

**Comment by kaaquist** [comment]
I can do this for you.

**Comment by ankitmaheswari** [comment]
@Swati4star Are you just looking for changing the dependency to be pulled from maven instead of jar file locally in the `libs/` folder? I can pick this change.

**Comment by Swati4star** [comment]
Yes @ankitmaheswari 
You may pick up some other issue. This one is already resolved.
