### ISSUE TITLE
Empty file getting created in "Extract text"

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#808]
- Select "Extract text" from navigation drawer in "more options"
- select a PDf which does not have any text and select "Extract text"
- an empty text file gets created.

The expected behaviour is: show a snackbar or toast saying that the PDF does not have any text.

**Comment by vherasme** [comment]
Can I start working on this?

**Comment by theparselmouth** [comment]
Hi, this is my first issue. Could I take this up ?

**Comment by Swati4star** [comment]
Sure @theparselmouth

**Comment by theparselmouth** [comment]
Is this issue done ?

**Comment by Swati4star** [comment]
Yes! by https://github.com/Swati4star/Images-to-PDF/pull/817
