### ISSUE TITLE
Add a FAQ section in app

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#811]
Add a FAQ section in app just before the settings section

**Comment by nfatma** [comment]
I would like to work on it.

**Comment by Swati4star** [comment]
Sure. You can take help from https://github.com/Swati4star/Images-to-PDF/blob/master/FAQs.md
But the above version is somewhat outdated. You'll have to go through the app to include all the features.

**Comment by Swati4star** [comment]
Updates @nfatma ?

**Comment by drigio** [comment]
@Swati4star I would like to work on this if possible.

**Comment by Swati4star** [comment]
yes @drigio 
You can start working on this.

**Comment by nfatma** [comment]
hey @Swati4star apologies for the delay. if this issue is still available for work, I can totally do it this weekend.
