### ISSUE TITLE
App crashes on startup in the recent update.

### ISSUE THREAD

**Issue by sudeshim3** [Swati4star/Images-to-PDF#812]
`java.lang.RuntimeException: Unable to instantiate application android.support.multidex.MultiDexApplication: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication"`

### Probable Reason
[commit Line](https://github.com/Swati4star/Images-to-PDF/commit/e5b591b0f8e4c582ffaf8fb3375b5ff0498b5e3f#r35473863) (multidex dependency removed)

On adding multidex dependency everything works fine.
`implementation 'com.android.support:multidex:1.0.3'`

### Steps to reproduce
Clone the repo and build, the application will crash with the following report in logcat.

**Comment by Swati4star** [comment]
@sudeshim3 Thank you for noticing this. This is completely my fault for doing this.
Would you like to create a PR to fix this? 
or I can fix it tonight.

TODO: I think we should add some automated UI tests so that a crash on launch is detected automatically.

**Comment by sudeshim3** [comment]
Yes, I will create a PR.

**Comment by sudeshim3** [comment]
I like the application and planning for a long term commitment to it, already thought about automating UI testing and various other changes. Would you prefer migrating to kotlin gradually?

This will enable us to support coroutine, extension functions and will help minimize verbosity
