### ISSUE TITLE
Extract Text: [Bug]Extracting text failes

### ISSUE THREAD

**Issue by svignesh93** [Swati4star/Images-to-PDF#816]
when choosing the pdf file from a "Select PDF File" Button. Only works when choosing PDF from a Bottom Sheet

### Steps to reproduce
1) Go to Extract Text Feature either from Home Screen or from Navigation Slider.
2) Tap "Select PDF File" Button and choose any PDF Doc.
3) A Dialog would appear and give the new text file name.
3) Tap "Extract Text" Button.

### Expected behaviour
PDF Text should be extracted to new text file.

### Actual behaviour
New text file was not created and text was not extracted.

### Device used
Nokia 6.1, Android Pie

### Would you like to work on the issue?
I'd love to, But working on other issue for now

**Comment by Swati4star** [comment]
@svignesh93 What is the location of your PDF file?
There are issues with getting path of files from some folders?

**Comment by svignesh93** [comment]
The file was chosen from /internal storage/Downloads/some_name.pdf. The same file was used when selecting it from the bottom sheet

**Comment by Swati4star** [comment]
Can you check if this issue is still there after merging this PR https://github.com/Swati4star/Images-to-PDF/pull/799 ?

**Comment by svignesh93** [comment]
Yes, It does solves this bug and it works.
