### ISSUE TITLE
extend Kotlin support.

### ISSUE THREAD

**Issue by sudeshim3** [Swati4star/Images-to-PDF#819]
Would like to add new features using kotlin language. This will enable  support coroutine, extension functions and will help minimize verbosity

Any plans of supporting kotlin right now?

_Originally posted by @sudeshim3 in https://github.com/Swati4star/Images-to-PDF/issues/812#issuecomment-541386492_

**Comment by Swati4star** [comment]
Any reason for closing this issue on your own? @sudeshim3

**Comment by sudeshim3** [comment]
As my contributions will be slow(just weekends) I don’t want to see the repo with few kotlin files here and there. So until unless there are multiple contributors, it won’t add value as migrating will consume significant time and require proper testing so as not to introduce bugs to already working features. 
So I thought closing would be better.
