### ISSUE TITLE
Use `Singleton Design pattern` for Utils classes

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#830]
Utils classes are present at: (ending with *utils.java)
https://github.com/Swati4star/Images-to-PDF/tree/master/app/src/main/java/swati4star/createpdf/util

For reference:
Use method 3 Lazy initialization from below link for implementation:
https://www.geeksforgeeks.org/java-singleton-design-pattern-practices-examples/

**Comment by ardlank** [comment]
@Swati4star can I do this?

**Comment by Swati4star** [comment]
Sure @ardlank 👍

**Comment by Swati4star** [comment]
Use 6th implementation: Bill Pugh Singleton Implementation for this

**Comment by akhil-ghatiki** [comment]
@Swati4star 
Implemented Bill Pugh Singleton implementation for AddTextEnhancementOptionUtils, BrushUtils, ColorUtils, CommonCodeUtils. Rasied a PR for the same. Look into it once the checks have passed.

**Comment by ardlank** [comment]
Implemented Bill Pugh Singleton implementation for DialogUtils and RealPathUtil. 

PR: #834

**Comment by sebastianjooo** [comment]
Hi there, 
can i grab and contribute to that issue?

**Comment by Swati4star** [comment]
@sebastianjooo sure

**Comment by sebastianjooo** [comment]
#890

**Comment by sebastianjooo** [comment]
i hope, thats it
