### ISSUE TITLE
Change in the existing UI (Home Screen)

### ISSUE THREAD

**Issue by anandkumarkparmar** [Swati4star/Images-to-PDF#84]
![abc](https://user-images.githubusercontent.com/20661863/41048053-8f0a15c8-69cb-11e8-8e7d-42a00cd3bc3c.jpeg)
[](url)

Make it like this.

**Comment by Swati4star** [comment]
Create a custom view for the elements ( 'Crop Images' , 'Password Protected PDF')

We will reuse this view for adding new features in the UI

**Comment by anandkumarkparmar** [comment]
What is the Accent color for the app?

**Comment by Swati4star** [comment]
You can check the colors here : 
https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/res/values/colors.xml

**Comment by anandkumarkparmar** [comment]
Do you want to change the button color? ( 'Crop Images' , 'Password Protected PDF')

**Comment by Swati4star** [comment]
If you think changing the color looks good, you can post the screenshot here. We can decide the final UI here now.

**Comment by anandkumarkparmar** [comment]
![](https://i.imgur.com/ybndnpl.png)

**Comment by Swati4star** [comment]
This is actually great. :+1:

Just a few suggestions :
1. The grey color of 'select images' button make it look like it is disabled. Can we change it back to blue only?
2. Make the text 'password *protect* PDF'
3. Password protect PDF is not a image enhancement option, so change the heading to 'More enhancement options'

**Comment by Swati4star** [comment]
Change 'crop images' to 'Edit images' 

This is because that option allows us to crop as well as rotate the images.

**Comment by anandkumarkparmar** [comment]
Is this fine?

![](https://i.imgur.com/Oc40TCC.png)

**Comment by Swati4star** [comment]
Yes. Perfect!
