### ISSUE TITLE
Add more and updated FAQs to the application.

### ISSUE THREAD

**Issue by rutujaac** [Swati4star/Images-to-PDF#840]
More FAQs can be added to the application to provide more information regarding frequent concerns like:
*  What is the format of the images extracted from the PDF?
*  Can I compress the images before creating a PDF? 
    and many more.

**Comment by Swati4star** [comment]
@rutujaac Great suggestion.
Do you think we should categorize FAQs feature-wise? It'll be easier to troubleshoot in that case.

**Comment by rutujaac** [comment]
Yes. We could do this. I would like to add a few FAQs first, get well acquainted with the repository and then go onto creating categories. We could even try to add a search filter after that and maybe
have a separate issue for this.
