### ISSUE TITLE
Add key value pairs for ques-answer in strings.xml for FAQ

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#846]
Currently, we have 2 different arrays for questions and answers to FAQ queries.
- https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/res/values/strings.xml#L530
- https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/res/values/strings.xml#L563

Follow this link: https://stackoverflow.com/a/28580502/3623128
Convert above 2 arrays to a single one using a delimiter: "#####"

**Comment by harshalkh** [comment]
I can take this.

**Comment by Swati4star** [comment]
Sure!
