### ISSUE TITLE
Bug - Images which have not been cropped do not get added to pdf. 

### ISSUE THREAD

**Issue by aayushinigam** [Swati4star/Images-to-PDF#85]
Steps to produce the bug - 
1. Choose multiple images.
2. Click on Crop Images option
3. Crop only a few of them
4. Create pdf
5. Pdf is created only for those which have been cropped.Other images are discarded.

**Comment by ashish4321** [comment]
Can i work on it?

**Comment by Swati4star** [comment]
Sure. Go ahead 👍

**Comment by ashish4321** [comment]
Can you explain what has to be done?

**Comment by Swati4star** [comment]
- Are you able to reproduce the issue? Follow the steps mentioned above.
- Figure out why is it happening.

**Comment by Swati4star** [comment]
@ashish4321 Any updates? It's a cakewalk issue. Shouldn't take 5 days.

**Comment by ashish4321** [comment]
Which images to chose and how to crop the images?? I am not getting any idea?? Cn you pls help?? What has to be done and how?

**Comment by Swati4star** [comment]
Did you even download the app? 
( Connect on slack. )

**Comment by Swati4star** [comment]
Fixed by ee949163bf3ea62af5e4df340e7c60730e1a0902
