### ISSUE TITLE
Update gif being used in readme

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#855]
Gif path:
https://github.com/Swati4star/Images-to-PDF/blob/master/screenshots/image_to_pdf.gif

### WHY?
The current gif does not have all the features

The gif size shouldn't be greater than 2MB as this decreases the page load size then.

**Comment by aasutossh** [comment]
Hi, I could do this.

**Comment by Swati4star** [comment]
Sure @aasutossh
