### ISSUE TITLE
[Code Refactor] Reorder strings in strings.xml according to feature they are used in

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#856]
Currently, all strings are random. Reorder them as per the feature
https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/res/values/strings.xml

- Separate the strings of same feature together and add apt comments (see Ref below)

### Ref
See `Separate` section in https://medium.com/google-developer-experts/android-strings-xml-things-to-remember-c155025bb8bb

**Comment by pedroandrades** [comment]
Hi! I will do this.

**Comment by Swati4star** [comment]
@pedroandrades Any updates here?

**Comment by phoenix30s** [comment]
hey, can I take this issue??

**Comment by Swati4star** [comment]
sure @phoenix30s

**Comment by phoenix30s** [comment]
Hey, Swati I have not started it yet, but I will start it soon.

**Comment by maharishi1** [comment]
Can i do?

**Comment by Swati4star** [comment]
yes @maharishi1
