### ISSUE TITLE
New feature : Add option to 'Show details' in PDF Actions

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#86]
![screenshot_20180607-154157](https://user-images.githubusercontent.com/9164477/41093647-82310048-6a69-11e8-96b7-f5a721a72c9e.jpg)

Add one more option in this dialog 
'Show details'

On clicking this option, we will get another dialog with the following details about the selected PDF :
1. Name
2. Path
3. Size
4. Date Modified
5. Date created

An example of this dialog : 
![screenshot_20180607-154352](https://user-images.githubusercontent.com/9164477/41093807-e22b3356-6a69-11e8-8fc2-9b64f2379165.jpg)

**Comment by sholkay** [comment]
I created a dialog which will show the following details about the selected PDF:
- _Name_
- _Path_
- _Size_
- _Date Created_ 
But I am unable to understand and implement the _Date Modified_ part.

**Comment by Swati4star** [comment]
You can leave the date modified part. 

The other 4 fields are enough.

**Comment by Swati4star** [comment]
Also, try to make these fields copyable. so that the user can copy the file path.

**Comment by tanvidadu** [comment]
@Swati4star I think it would be helpful if we display some information like size, date of creation in the pdf converter list too. Would love to know your opinion!

**Comment by Swati4star** [comment]
@tanvidadu Yes. It does sound good. You can create a different issue for that.

**Comment by ac491** [comment]
I would like to try to solve this issue

**Comment by Swati4star** [comment]
@sholkay Are you working on this issue?

( @ac491 , If he is not working on this issue, you can pick it up)

**Comment by sholkay** [comment]
@ac491 Go ahead, I am working on something else right now.

**Comment by ac491** [comment]
![details_screen](https://user-images.githubusercontent.com/31413484/41831888-2ece34d2-7867-11e8-8499-82f5981b167c.png)
@Swati4star, Is this alright?

**Comment by Swati4star** [comment]
looks good. Can you add on icon(copy icon) after the path, so that the user is able to click on the icon & copy path.

**Comment by ac491** [comment]
I'll try it out.

The path is selectable though.

**Comment by Swati4star** [comment]
I hope it's not editable.
After selecting, can I copy it?

**Comment by ac491** [comment]
yes, it's not editable and it can be copied.
![copy](https://user-images.githubusercontent.com/31413484/41833003-3453f4d2-786c-11e8-8902-1906f72580dc.png)

**Comment by Swati4star** [comment]
Coo. You can leave the icon then.
There is a lot of difference between left margin of content & heading. Move the `Details` heading a bit to the left.

**Comment by ac491** [comment]
![screenshot_2018-06-25-12-17-35-768_swati4star createpdf](https://user-images.githubusercontent.com/31413484/41834429-e3aaafde-7871-11e8-9466-a4c7c3bb0e33.png)

**Comment by Swati4star** [comment]
looks good. You can create a PR for this.
