### ISSUE TITLE
[Code Refactor] Improve code climate for file utils class

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#864]
https://codeclimate.com/github/Swati4star/Images-to-PDF/app/src/main/java/swati4star/createpdf/util/FileUtils.java
Try to bring the rating from D to A 

### Some suggestion
- Number of lines in this file is huge - try to separate some relevant functions in different utils file

**Comment by Caps-Looking** [comment]
Can I take this one, please?

**Comment by Swati4star** [comment]
Sure @Caps-Looking 
Please go ahead.
If you get stuck somewhere, we can discuss here.

**Comment by Swati4star** [comment]
@Caps-Looking Updates?

**Comment by sebastianjooo** [comment]
I'd like to go on with this one

**Comment by priyapotnis** [comment]
can I take this one?

**Comment by Swati4star** [comment]
Yes @priyapotnis

**Comment by navkumar258** [comment]
I am looking for my first contribution, is it still open..?? thanks !

**Comment by Shobu908** [comment]
I am interested in helping you out to refactor the code @Swati4star

**Comment by zdennisz** [comment]
@Swati4star Can i take this one too ?

**Comment by Swati4star** [comment]
@navkumar258 @ShobhitTripathi @zdennisz The issue is open. You can check the label `up-for-grabs` to check it's availability. Please comment that you are working on the issue, and get started with it :)

**Comment by WilliamDann** [comment]
I am going to try this.

**Comment by jestes0** [comment]
I want to take a crack at this since it is still open and see what I can come up with.

**Comment by seshasaisuhashdesu** [comment]
I would like to work on this.

**Comment by mbokinala** [comment]
Can I also try this?

**Comment by nenzan** [comment]
I would like to try work on this

**Comment by Swati4star** [comment]
You can start working on this issue, and mention here than you are working on it.

**Comment by priyanshnama** [comment]
@Swati4star can you assign this to me plzz

**Comment by umairayub79** [comment]
I'm gonna give it a shot too

**Comment by Swati4star** [comment]
@priyanshnama Are you working to bring the rating further down to A? (It's B now :) )

**Comment by priyanshnama** [comment]
@Swati4star 
Sorry was a bit busy in other repo...
but was looking into it..
basically i think we need to omit or club some function in order bring it down.

**Comment by PapailleEnQueue** [comment]
I would like to try work on this.
