### ISSUE TITLE
[Code Refactor] Improve code climate

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#865]
https://codeclimate.com/github/Swati4star/Images-to-PDF/code?sort=maintainability

Try to bring up the rating of files which have a rating worse than B to `A`

**Comment by rvhamed** [comment]
Hi, please let me refactor code. can you assign it to me, please?

**Comment by Swati4star** [comment]
Sure @rvhamed

**Comment by Swati4star** [comment]
@rvhamed updates?

**Comment by rvhamed** [comment]
it's not complete. I still working on it, but slowly.

**Comment by dutta14** [comment]
Hi @Swati4star , I would like to pick these up if it is not being actively worked upon. I can pick up files one at a time, starting from F down to B, and can keep updating this thread as I progress.

**Comment by Swati4star** [comment]
@dutta14 You can start working on this. The issue is not being actively worked upon.

**Comment by dutta14** [comment]
Would it be better to break this issue into individual issues per Java file so that I can send incremental pull requests to different issues?

**Comment by dutta14** [comment]
@Swati4star Would it be better to break this issue into individual issues per Java file so that I can send incremental pull requests to different issues?

**Comment by Swati4star** [comment]
@dutta14 Yes that seems good.
Whenever you create a PR related to refactoring any file, you can create an issue with that.

**Comment by dutta14** [comment]
Created issue #898  for refactoring ImageToPdfFragment.

**Comment by ksurulo** [comment]
@Swati4star Is anyone working on this issue? If no, I would like to pick it up. Should I also create a separate issue for any file?

**Comment by Swati4star** [comment]
@ksurulo Sure, go ahead.
You can just comment here the file on which you are working.

**Comment by GlitchyDev** [comment]
I just finished a refactor of WatermarkUtils, I did so by breaking the 73 line code into 3 methods.

I'm a bit new to working in open source. How should I go about merging this in and making sure its all good? Merge ( Or Request Pull ) into origin/PDFOpen or upstream/PDFOpen?

**Comment by ksurulo** [comment]
I am working on TextToPDFUtils

**Comment by Swati4star** [comment]
@GlitchyDev You can see the steps here: https://github.com/Swati4star/Images-to-PDF/blob/master/CONTRIBUTING.md#6-make-a-pull-request

**Comment by ksurulo** [comment]
@Swati4star I made a pull request. Please review
