### ISSUE TITLE
Add drawables according to density

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#866]
Currently, only few of the drawables are arranged as per screen density.
do it for all drawables.

**Comment by ryanqfeeney** [comment]
Can you elaborate a little bit? This seems like a good starting point and I'd like to get involved but I'm not sure I fully understand the issue.

**Comment by Swati4star** [comment]
@ryanqfeeney Check this link: https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp

Give it a read. If there is some doubt, do comment on this issue

**Comment by ryanqfeeney** [comment]
There is still a little confusion. I understand the link you provided. Can you give me an example of a file in the project that is already done correctly and one that is not? 

There are all of the various transformation example webp files in the xxhdpi folder that dont appear anywhere else, like black.webp and auto_fix.webp should those be edited for the lower densities?

**Comment by Swati4star** [comment]
@ryanqfeeney Yes, you are correct. The files which are not present in lower densities should be edited for those.

You can take help of this plugin to create this: https://medium.com/code-yoga/create-drawables-from-a-large-scale-image-automatically-2128dde61ad9

**Comment by 6point022** [comment]
I want to start working on this issue. I see drawable directories for three different pixel densities, i.e. `hdpi`, `xxhdpi` and `xxxhdpi`. For every `.webp` image inside the `xxhdpi` directory, we have to generate an `hdpi` and `xxxhdpi` version of it. For `circle.webp`, inside `xxxhdpi` directory we have to generate an `hdpi` and `xxhdpi` version. Please let me know if I have understood the issue correctly and if there's anything I missed.

**Comment by Swati4star** [comment]
Yes Correct @6point022

**Comment by 6point022** [comment]
> You can take help of this plugin to create this: https://medium.com/code-yoga/create-drawables-from-a-large-scale-image-automatically-2128dde61ad9

I am trying to use this plugin, however, it will only convert existing `.webp` images to `.png` or `.jpg`. What should I do?

**Comment by Swati4star** [comment]
@6point022 What's the issue then? you do have to do that only...
