### ISSUE TITLE
hello can i publish app in play store with using app in advisement ??

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [Swati4star/Images-to-PDF#872]
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by Swati4star** [comment]
No. This will be a copyright violation. :)

**Comment by Swati4star** [comment]
Also, the app is already published on playstore. I don't see a point in publishing the exact thing again.

**Comment by Jaymin-Bhadani** [comment]
Sorry so why you put gpl 3 licence it is free to publish same copy or
modication with using commercial
