### ISSUE TITLE
[Suggestion] Apply for Njack Winter of Code 2019

### ISSUE THREAD

**Issue by drigio** [Swati4star/Images-to-PDF#873]
Not really an Issue. However I think this repository can definitely benefit from the upcoming **NJACK WOC.** It's like a *mini GSoC* by IIT Patna. 

If it feels appropriate, please have a look into it. Last date for mentors to apply is **22nd Nov**.
[Link to NJACK Winter of Code](https://njackwinterofcode.github.io/)

**Comment by Swati4star** [comment]
@drigio Thank you for the suggestion!
The thing is, I am kind of unavailable during the coding period (most of December).

**Comment by drigio** [comment]
Well, I guess this issue can be closed then.
