### ISSUE TITLE
Show a confirmation dialog when deleting single File

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#874]
### Steps to reproduce
- go to `View Files`
- select a file. Options show up
- select `Delete File`

### Expected behaviour
A confirmation dialog "Are you sure you want to delete <filename>?" should show up.

### Actual behaviour
No confirmation dialog. File is deleted directly.

**Comment by xxrain-makerxx** [comment]
Hi, I can do this.

**Comment by Swati4star** [comment]
Yeah. Sure :)

**Comment by xxrain-makerxx** [comment]
when the file is deleted should it show the snackbar to undo the delete?

**Comment by Swati4star** [comment]
That is already there. We should have the snack bar.

Regards,
Swati Garg

**Comment by xxrain-makerxx** [comment]
[https://github.com/Swati4star/Images-to-PDF/pull/876](url)

**Comment by xxrain-makerxx** [comment]
#876

**Comment by xxrain-makerxx** [comment]
[https://github.com/Swati4star/Images-to-PDF/pull/876#issue-348697753](url)

**Comment by xxrain-makerxx** [comment]
please review #876

**Comment by xxrain-makerxx** [comment]
I updated the PR. Please check.
