### ISSUE TITLE
Updating FAQs

### ISSUE THREAD

**Issue by iprithvitharun** [Swati4star/Images-to-PDF#879]
Update grammatical errors and rephrase existing sentence to make it concise.

### Would you like to work on the issue?
Yes.

**Comment by iprithvitharun** [comment]
@Swati4star How can I apply bold to texts?

**Comment by Swati4star** [comment]
@iprithvitharun 
You can use html formatting.
Reference: https://stackoverflow.com/questions/14371092/how-to-make-a-specific-text-on-textview-bold/14371107

**Comment by iprithvitharun** [comment]
@Swati4star Can I add watermark to PDFs or only to images?

**Comment by Swati4star** [comment]
@iprithvitharun You can add watermarks to PDFs only for now,
