### ISSUE TITLE
"Select Files" button in Merge PDF doesn't work

### ISSUE THREAD

**Issue by jz9888** [Swati4star/Images-to-PDF#881]
My cellphone is Android 9.
### Steps to reproduce
1. Click "Merge PDF"
2. Click "SELECT FILES"
3. Select a file from your local file

### Expected behaviour
A file has been added to the list successfully.

### Actual behaviour
The dialog tells me a file has been added to the list successfully. However, the file name is blank. After two files are added, click "MERGE FILES". The dialog tells me "We were unable to access PDF. Files may be encrypted or in the external storage".

### Would you like to work on the issue?
Currently I am working on another project, so I don't have time to work on this issue.

**Comment by ana-nyaa** [comment]
@jz9888 I would like to work on this issue.may I?

**Comment by Swati4star** [comment]
Sure. Go ahead with it @ana-nyaa

**Comment by Swati4star** [comment]
@ana-nyaa Are you working on this?
