### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#883]
At a number of places, we show to user "error occurred" in toast messages.
This isn't helpful.

Change this message to appropriate error message in these places:
https://github.com/Swati4star/Images-to-PDF/search?q=error_occurred&unscoped_q=error_occurred

**Comment by iprithvitharun** [comment]
@Swati4star I'm working on it.

**Comment by Swati4star** [comment]
@iprithvitharun  Are you working on this issue?

**Comment by wetHands04** [comment]
@Swati4star I can work on it.

**Comment by Swati4star** [comment]
@wetHands04 Sure..

**Comment by rns350** [comment]
Is this issue still up for grabs?  Or is someone actually still working on it.  I can take a look and fix this for you guys.

**Comment by Swati4star** [comment]
@rns350 this issue is open. You can take it up.

**Comment by rvhamed** [comment]
Yes, This issue still up for grabs and nobody working on it.  Thanks so
much.

**Comment by neil4droid** [comment]
@rns350 are you working on this issue? There is still an up for grabs label on the issue.

**Comment by Swati4star** [comment]
@neil4droid It's open.

**Comment by jayvishaalj** [comment]
I am working on this issue

**Comment by moumini-creator** [comment]
Hello, I want to fix this bug

**Comment by jayvishaalj** [comment]
@moumini-creator Sorry, I am already working on this issue
