### ISSUE TITLE
Add option to rearrange the images selected for creating the PDF

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#89]

**Comment by Swati4star** [comment]
Sure.

And do one thing, add this option in preview screen & not on the home screen.

**Comment by vyankatesh24** [comment]
Ok

**Comment by vyankatesh24** [comment]
Shall I add it as a menu or on the viewport as a button?

**Comment by Swati4star** [comment]
Add it as an option above the place where it is written `swipe left to view next` in preview activity

( We'll add more options also over there later)

**Comment by vyankatesh24** [comment]
Ok

**Comment by vyankatesh24** [comment]
"As an option" do you mean in RecyclerView?

**Comment by vyankatesh24** [comment]
Or just simple button is Ok

**Comment by Swati4star** [comment]
It would be better if you add it in recycler view (similar to filters in filters screen)

**Comment by vyankatesh24** [comment]
Ok

**Comment by Swati4star** [comment]
Also, how do you plan to allow users to rearrange images? I don't have any specific UI in mind. You can share whatever you do, and we can discuss on that further.

**Comment by vyankatesh24** [comment]
@Swati4star 
Have a  look.

![screenshot_2018-07-26-17-02-38-335_swati4star createpdf](https://user-images.githubusercontent.com/18503975/43260041-de9f07e6-90f5-11e8-8c2e-84f4b3b14416.png)

![screenshot_2018-07-26-17-02-07-959_swati4star createpdf](https://user-images.githubusercontent.com/18503975/43260061-efe8802c-90f5-11e8-9c8c-84192522ea56.png)

**Comment by Swati4star** [comment]
@vyankatesh24 
Looks perfect! Just a few UI changes
- Add a back arrow on top left corner in the second preview screen
- In the first screen, give a card type look to the rearrange button.

**Comment by vyankatesh24** [comment]
![screenshot_2018-07-26-17-22-09-170_swati4star createpdf](https://user-images.githubusercontent.com/18503975/43261102-30ee2736-90f9-11e8-97bf-32a41f0052ee.png)



![screenshot_2018-07-26-17-26-34-402_swati4star createpdf](https://user-images.githubusercontent.com/18503975/43261107-33582076-90f9-11e8-91fc-119347868fb9.png)

**Comment by Swati4star** [comment]
@vyankatesh24 Looks good. Create a PR! 👍
