### ISSUE TITLE
Purpose of two continuous integration services?

### ISSUE THREAD

**Issue by veyndan** [Swati4star/Images-to-PDF#9]
CircleCI support was added in [this commit](460aa2bfddce0482e392e8eb0f6af9514fa4f72f) but I don't see the point considering Travis is already in use. Also when making a PR, only Travis is run and CircleCI doesn't appear to be in use.

My suggestion would be to delete `circle.yaml` as it doesn't appear to be adding any benefit to the code base. Even if CircleCI was set up correctly, the use of two CI services seems overkill.

**Comment by Swati4star** [comment]
Thanks for the suggestion. This actually seems sensible. I will remove circle.yaml :+1:
