### ISSUE TITLE
Check code quality

### ISSUE THREAD

**Issue by mariosj99** [Swati4star/Images-to-PDF#906]
Hello, I'm a third year student of Aristotle University of Thessaloniki, in Greece. We have been given a task to analyze the quality of the code of an open source project. Your project seems interesting so I'd like to analyze the quality if that's ok with you!

**Comment by Swati4star** [comment]
@mariosj99 Is there any input required on this from my side?
This is an open source project. You are free to analyse quality, and if something seems bad, you can let us know, and we'll try to improve on that.

Also, we are already using codeclimate (https://codeclimate.com/github/Swati4star/Images-to-PDF) to analyse code quality.
