### ISSUE TITLE
[Code Refactor] Improve Watermark Utils Readability

### ISSUE THREAD

**Issue by GlitchyDev** [Swati4star/Images-to-PDF#910]
https://codeclimate.com/github/Swati4star/Images-to-PDF/app/src/main/java/swati4star/createpdf/util/WatermarkUtils.java

**Comment by GlitchyDev** [comment]
Alright it appears there are further refactoring that will need to be done. I'll see to working on those changes then squashing them

**Comment by GlitchyDev** [comment]
Looking into fixing the Codestyle and Complexity issues, I'm not seeing much in terms of potential progress. Both helper methods can't reduce parameters any further without breaking the lambda they both carry apart. Any potential suggestions or should I just work on going through the checklist and getting it ready otherwise

**Comment by Swati4star** [comment]
Let's leave this file then, and work on some other ones.
