### ISSUE TITLE
gradle issue

### ISSUE THREAD

**Issue by rushichatur** [Swati4star/Images-to-PDF#913]
Steps to reproduce
It appears when you use gradle 4.0.0

Expected behaviour
It should work with gradle version 4.0.0

Actual behaviour
The option android.enableSeparateAnnotationProcessing is deprecated. 
The current default is false. 
It was removed in version 4.0 of the Android Gradle plugin.
This feature was removed in AGP 4.0

Would you like to work on the issue?
Yes

**Comment by Swati4star** [comment]
@rushichatur You can work on this. Submit a PR.

**Comment by mohamedelkashif** [comment]
Still opened? @Swati4star

**Comment by Swati4star** [comment]
This issue is open :)

**Comment by gaurav9822** [comment]
@Swati4star Please assign this issue to me. It is getting covered as part of #939 

Please review #942
