### ISSUE TITLE
Cannot donate

### ISSUE THREAD

**Issue by antenore** [Swati4star/Images-to-PDF#914]
First of all thanks so much for this amazing application!!!

I'd like to donate some money, but the "Buy me a coffee" page says that as you don't have set a payment method I cannot do the payment.

As you deserve it, please set one and consider that most of the people that would like to donate money won't let you know that it doesn't work ;-)

Liberapay may be another light option if you like.

All the best!!!

**Comment by Swati4star** [comment]
@antenore Thank you for the encouraging words. 

I've updated the BuyMeACoffee link now :)
