### ISSUE TITLE
F-Droid still on 8.5.6

### ISSUE THREAD

**Issue by qoheniac** [Swati4star/Images-to-PDF#920]
Version on F-Droid is 8.5.6 while the most recent release here is 8.8.1.

### Steps to reproduce
Go to [F-Droid repo](https://f-droid.org/app/swati4star.createpdf) and look up most recent version there. Then go to [GitHub repo](https://github.com/Swati4star/Images-to-PDF/releases) and look up most recent version there.

### Expected behaviour
Version numbers are the same.

### Actual behaviour
F-Droid has 8.5.6 while GitHub is at 8.8.1.

### Would you like to work on the issue?
No.

**Comment by HenriDellal** [comment]
The reason is that it depends on a proprietary library since 8.6.3 according to F-Droid data:

https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/swati4star.createpdf.yml
