### ISSUE TITLE
Improve code climate for CommonCodeUtils

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#932]
https://codeclimate.com/github/Swati4star/Images-to-PDF/app/src/main/java/swati4star/createpdf/util/CommonCodeUtils.java

The file currently has rating of D. Try to bring it down to B atleast

**Comment by m4tr1k** [comment]
Hi @Swati4star can I take a look at this issue?

**Comment by Swati4star** [comment]
sure @m4tr1k
