### ISSUE TITLE
Add unit test for BrushUtils class

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#934]
https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/java/swati4star/createpdf/util/BrushUtils.java

**Comment by gaurav9822** [comment]
Hi @Swati4star I would like to take this issue. Please assign it to me.

**Comment by gaurav9822** [comment]
@Swati4star BrushUtils is a Singleton and has an API to return a list of brush items.
Tests -
1. If there is only one instance
2. If the respective brush items are returned.

Any other tests than that?

Also, getBrushItems() creates a new ArrayList object each time. Can there be a refactoring to return a static list only?

**Comment by Swati4star** [comment]
Let's have test for this one method only.

static list sounds good, but initialize that list only when instance of this method is requested.

**Comment by gaurav9822** [comment]
Please review the pull request #940
