### ISSUE TITLE
New feature : Set page size & margin options

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#94]
Refer this : 
https://developers.itextpdf.com/examples/itext5-building-blocks/page-size

**Comment by vyankatesh24** [comment]
@Swati4star 
I would like work on it.
Will you please elaborate issue.
For page size, should I give option to choose page sizes given PageSize class of itext library or custom size height and width.

**Comment by vyankatesh24** [comment]
A0 to A10
B0 to B10
static PageSize | Default
static PageSize | EXECUTIVE
static PageSize | LEDGER
static PageSize | LEGAL
static PageSize | LETTER
static PageSize | TABLOID

**Comment by Swati4star** [comment]
We can add a new option in the home page, in the enhancement options list only. `Set Page Size`
On clicking this, open up a dialog/activity. It should have the options for above page sizes :

All the options should be in  radio buttons.
Default should be selected by selected.
Add all other options in radio buttons.
For A1 to A

**Comment by Swati4star** [comment]
Sorry, closed this issue by mistake.

Also, mention the page size (like actual heigth & width) below each page size option also.

**Comment by vyankatesh24** [comment]
Ok

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Images-to-PDF/pull/195
