### ISSUE TITLE
Requesting permissions is not done everywhere

### ISSUE THREAD

**Issue by McModknower** [Swati4star/Images-to-PDF#957]
While making PR #956 i noticed not all fragments requested permission when the permission was not already given. After looking a bit into it, the analysis showed me that the following classes are NOT asking for storage/camera permissions when they need:
- HistoryFragment
- InvertPdfFragment
- MergeFilesFragment
- PdfToImageFragment
- QrBarcodeScanFragment (camera gets asked, but not storage for saving)
- RemoveDuplicatePagesFragment
- RemovePagesFragment
- SplitFilesFragment

### Steps to reproduce

1. Remove storage/camera permissions for the app
  a. hold the icon long
  b. click the small i in the top right corner
  c. click on "Permissions" (or how its named)
  d. turn off storage/camera
2. Open the app
3. click on any of the listed fragments
4. try to do something that requires the permission, for example try to open a PDF in the SplitFilesFragment

### Expected behaviour
A permission request should show up asking for storage permission.

### Actual behaviour
The snackbar shows up with the R.string.encrypted_pdf message.

### Would you like to work on the issue?
I would work on the issue if no one else wants to do it and i improved the code climate of ImagesToPdfFragment to something better than F.

PS: the behaviour of #881 can not only be caused by the Parent folder not existing but also by this

**Comment by JohnX4321** [comment]
I would like to work on this

**Comment by Swati4star** [comment]
@JohnX4321 Sure, go ahead.

**Comment by KAbhijeet2105** [comment]
Is this issue still open? I would like to work on this issue.

**Comment by KAbhijeet2105** [comment]
Is this issue still open? I would like to work on it.

**Comment by Swati4star** [comment]
yes, the issue is still open (It's not closed :) )
@KAbhijeet2105

**Comment by JohnX4321** [comment]
#965 Sorry for delay. My system was configured to run androidx . so to work with legacy support library required lot of redownloading and configuration
