### ISSUE TITLE
Convert to AnroidX

### ISSUE THREAD

**Issue by kashifkhanbaloch** [Swati4star/Images-to-PDF#966]
Describe your issue here.
When we convert to androidx project crash on image to pdf when we select image and Add image to pdf.

**Comment by Swati4star** [comment]
I don't get the issue here.

You want to convert the project to adroidX?

**Comment by errohitdev** [comment]
When we convert to androidx project crash on image to pdf when we select image and Add image to pdf. And in some device after image to pdf conversion pdf not open it show " Error occurred".
![Screenshot_20201021-063439](https://user-images.githubusercontent.com/53206054/96660643-bdb13a80-1367-11eb-9c66-6f6c099c7ef8.png)

**Comment by Swati4star** [comment]
It means you converted to androidx incorrectly. What do you expect to be fixed in this current project?
