### ISSUE TITLE
Merge feature is describes 2 times in introduction

### ISSUE THREAD

**Issue by PatelVatsalB21** [Swati4star/Images-to-PDF#975]
Merge feature fragment is shown at 3rd and 9th position.

### Steps to reproduce
On app start for first time. 

### Expected behaviour
It should be on 3rd or 9th page. 

![Screenshot_20201205-115000](https://user-images.githubusercontent.com/70195106/101235665-3d188480-36f0-11eb-9a7e-b0169b82400e.jpeg)
![Screenshot_20201205-115008](https://user-images.githubusercontent.com/70195106/101235667-40ac0b80-36f0-11eb-9321-818a330bd299.jpeg)

**Comment by Nahoyhp** [comment]
Hi, I am new to contributing to OSS and I will like to contribute.
Any help on how to set up this project locally?

**Comment by porelsoumen** [comment]
I have a PR ready and would like to contribute. Please allow me.

**Comment by WilliamCheng12345** [comment]
Hi, I am interested in solving this issue. Has the issue been resolved? Thank you!

**Comment by Nahoyhp** [comment]
I have made a PR about it. Waiting for review.

**Comment by SayanDas92** [comment]
I want to solve this issue. I'm new to open-source contribution. Thank you!

**Comment by SmritiSharmaBG** [comment]
Hello. I am new to Open Source and GitHub in general. I made some changes to fix the bug and made the pull request. What should be my next step? How do I know that these changes are incorporated in the app or in this repo?

**Comment by milosagasdc11** [comment]
Hello, I see that it is open. Can I work on this?

**Comment by camo0112** [comment]
I know what causing this.
in res>layout>fragment_excelto_pdf.xml
        the value for text attribute for TextView with id tv_desc is  "@string/welcome_merge_message" which is wrong for this 
        activity 
To fix 
-> create a new string value with id welcome_excel_to_pdf_message with appropriate value in different languages
->change in res>layout>fragment_excelto_pdf.xml
        the value for text attribute for TextView with id tv_desc to  "@string/welcome_excel_to_pdf_message"

**Comment by sergey-levv** [comment]
It looks like the issue has already been fixed and is no longer reproducible.
