### ISSUE TITLE
Editing Images with Text

### ISSUE THREAD

**Issue by Shreya479** [Swati4star/Images-to-PDF#986]
Sometimes when we convert some images to pdf , we need to photoshop them. This feature can be added which allow people to edit their documents.  

### Steps to reproduce
We can simply add this feature like we reorder pages in the associated app likewise there can be an option where we will edit the content.

### Expected behaviour
We can expect the change in the editing section of the file.

### Actual behaviour
Tell us what happens instead

### Would you like to work on the issue?
Yes, i want to work on this issue.

**Comment by Shreya479** [comment]
Yes !!!
We can have a photo merging option. Like we can add text or some sort of
images in between the pages.

**Comment by Swati4star** [comment]
@Shreya479  - If you have any library in mind to implement this, please share?
