### ISSUE TITLE
Crop feature similar to cam scanner

### ISSUE THREAD

**Issue by Rautarchit001** [Swati4star/Images-to-PDF#987]
I want to change the crop feature to work like camscanner crop can we do it?

**Comment by Swati4star** [comment]
@Rautarchit001 - Is there any existing library you plan on using?
Please share the plans here to have this feature.

**Comment by Rautarchit001** [comment]
openCVLibrary & documentscanner library can be used to add advanced crop feature like Cam Scanner.

You can check this repository for that library repository [https://github.com/kajalsinhait/camScanner-India](https://github.com/kajalsinhait/camScanner-India)

**Comment by HenryZhang0222** [comment]
Had this feature been implemented, I can work on this issue.
