### ISSUE TITLE
Maigrate the project to androidx

### ISSUE THREAD

**Issue by hhhh-max** [Swati4star/Images-to-PDF#988]
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by Swati4star** [comment]
Can you mention the utility of migrating to androidx?

**Comment by Rautarchit001** [comment]
for updating to API 29 or 30 wen need to migrate to androidx

**Comment by Swati4star** [comment]
We have enable android x in our project. There are no issues in migrating it to API 29/30
