### ISSUE TITLE
After updating to API 29 Image does not show in preview and also does not create pdf.

### ISSUE THREAD

**Issue by Rautarchit001** [Swati4star/Images-to-PDF#989]
Image Picker issue resolve by updating image picker library but now there is another isuue after picking/selection image does not show in preview and also does not create pdf.

_Originally posted by @Rautarchit001 in https://github.com/Swati4star/Images-to-PDF/issues/973#issuecomment-803522379_

**Comment by AvneeshGupta1** [comment]
Hi Rautarchait001 i have release kotlin code with same function.
Please check this.
Let me know if you have any issue

https://github.com/AvneeshGupta1/DocScanner
