### ISSUE TITLE
Code Cleanup : Move utility functions from ViewFilesAdapter to a new class 'FileUtils'

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#99]
- Move all files related functions from https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/java/swati4star/createpdf/fragment/ViewFilesFragment.java like `sortByNameAlphabetical ` , `sortFilesByDateNewestToOldest `, `sortFilesBySizeIncreasingOrder ` , `sortFilesBySizeDecreasingOrder ` , `getPdfsFromPdfFolder ` and more to a new class 'FileUtils'.

Purpose : 
- Code cleanup
- Improving code maintainability

**Comment by ac491** [comment]
I would like to work on this.

**Comment by Swati4star** [comment]
Sure. Go ahead! 👍

**Comment by Swati4star** [comment]
Fixed by 06e5bb6f99fda5122a4ce05578bce9f1217477e0

**Comment by Swati4star** [comment]
Thanks to @ac491 👍
