### ISSUE TITLE
Add a new feature: PDF Search Engine

### ISSUE THREAD

**Issue by Rautarchit001** [Swati4star/Images-to-PDF#992]
As this is PDF Toolkit so there should be one more feature like PDF Search and download, so can I do research on that and add it to this project? @Swati4star  and all others please respond so that I can add it.

**Comment by Swati4star** [comment]
Hey @Rautarchit001 - Can uou elaborate more on this feature? - "PDF search and download"

**Comment by Rautarchit001** [comment]
Users can search pdf through pdf search engine and download them directly from search results itself.

**Comment by Swati4star** [comment]
- Download the PDF from where?
- Do you have a repository of PDFs?

I dont understand the utility of this feature. This app is more about creating or editing a PDF.

**Comment by Rautarchit001** [comment]
Like google bing which are Search engine of whole web there are pdf search engine too so we can add that using chrome custom tab so that our user can not only create or edit pdf but now they can also search and download pdf too.

**Comment by Swati4star** [comment]
- I am not sure this feature will be helpful.
- Adding a custom chrome tab to the app will just make it a search engine also. Is there any specific PDF search engine you have in mind? : Can you share that.

**Comment by Rautarchit001** [comment]
One of that type of search engine which i manage is https://pdfdrivesearch.com

**Comment by Swati4star** [comment]
This looks like a great project on it's own. But, I am not so keen on adding this as a tab in the app.

You can pick up some other issue, or suggest a new issue?

**Comment by Rautarchit001** [comment]
Ohhk np 👍

**Comment by Rautarchit001** [comment]
Did you got solution of updating target sdk to 29 does not create pdf?

**Comment by Swati4star** [comment]
You are talking about this - https://github.com/Swati4star/Images-to-PDF/pull/990

I updated API to 29 locally, but didnt update the matisse library. I think the issue is with that.

**Comment by Rautarchit001** [comment]
After updating library then also that error occurr while creating pdf
