### ISSUE TITLE
The method `getExternalStoragePublicDirectory()` is deprecated since API 29 !

### ISSUE THREAD

**Issue by codegsaini** [Swati4star/Images-to-PDF#996]
### According to [Android Documentationon on `getExternalStoragePublicDirectory()`](https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String))
> This method was deprecated in API level 29.
To improve user privacy, direct access to shared/external storage devices is deprecated. When an app targets Build.VERSION_CODES.Q, the path returned from this method is no longer directly accessible to apps. Apps can continue to access content stored on shared/external storage by migrating to alternatives such as Context#getExternalFilesDir(String), MediaStore, or Intent#ACTION_OPEN_DOCUMENT.

### What should be the solution?
**Instead of saving PDF files by this method we should use [`MediaStore` API](https://developer.android.com/reference/android/provider/MediaStore).**

**Comment by Swati4star** [comment]
@codegsaini  - Are you loooking into this?

**Comment by codegsaini** [comment]
@Swati4star I'm not working on this issue because I will remove this method once I get solution of entire storage related problem to satisfy android's new [Scoped storage](https://developer.android.com/about/versions/11/privacy/storage) policy. 
This `getExternalStoragePublicDirectory()` method is not future proof, So I'm still working on the entire storage related solution that fits the android's new Scoped storage policy.
**This method is for the buffer period unless I propose the future proof solution of entire storage related solution.**

**Comment by codegsaini** [comment]
Actually this issue is useless because this method is for short term. I am working to solve the problem while saving files using scoped storage. After I'll get solution, this method will be removed thus the deprecation issue will be gone.
As this issue is temporary because the root cause of this issue ( the method ) will be removed in near future. So I'm closing this issue!
