### ISSUE TITLE
Page numbering UI is broken with black theme

### ISSUE THREAD

**Issue by cewbdex** [Swati4star/Images-to-PDF#999]
Theming issue

![IMG_20210419_093558](https://user-images.githubusercontent.com/9021297/115200374-6f051300-a0f4-11eb-8085-7641e8642a7b.jpg)

### Steps to reproduce
Switch to black theme and navigate to page numbering.

### Expected behaviour
Text should be visible and background black.

### Actual behaviour
It's broken.

### Would you like to work on the issue?
Sure, but don't know how 🙄

**Comment by MariaGiannaki** [comment]
Hello, I was interested in contributing by solving this issue but I cannot reproduce it on my phone. Has this issue already been fixed?
![Screenshot_20210427_194919_swati4star createpdf](https://user-images.githubusercontent.com/57483777/116281768-b2195300-a792-11eb-9bc6-528992200743.jpg)

**Comment by cewbdex** [comment]
@MariaGiannaki 
Try light theme on phone, but dark in-app. Makes a little sense, but it's still a bug u would say.

**Comment by codegsaini** [comment]
> @MariaGiannaki
> Try light theme on phone, but dark in-app. Makes a little sense, but it's still a bug u would say.

@cewbdex Still cannot be reproduced.

## SideNote ~
It look like you are working on old version of repo. Please work on latest fetched !
